INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:06,  4.39it/s]  7%|▋         | 2/30 [00:00<00:05,  4.91it/s] 10%|█         | 3/30 [00:03<00:31,  1.18s/it] 17%|█▋        | 5/30 [00:04<00:21,  1.16it/s] 20%|██        | 6/30 [00:04<00:17,  1.37it/s] 23%|██▎       | 7/30 [00:06<00:24,  1.06s/it] 33%|███▎      | 10/30 [00:06<00:15,  1.26it/s] 37%|███▋      | 11/30 [00:07<00:14,  1.34it/s] 40%|████      | 12/30 [00:08<00:12,  1.49it/s] 43%|████▎     | 13/30 [00:08<00:09,  1.82it/s] 47%|████▋     | 14/30 [00:08<00:07,  2.04it/s] 50%|█████     | 15/30 [00:08<00:06,  2.43it/s] 53%|█████▎    | 16/30 [00:09<00:08,  1.66it/s] 57%|█████▋    | 17/30 [00:11<00:12,  1.07it/s] 63%|██████▎   | 19/30 [00:12<00:08,  1.26it/s] 70%|███████   | 21/30 [00:14<00:07,  1.28it/s] 73%|███████▎  | 22/30 [00:14<00:04,  1.71it/s] 83%|████████▎ | 25/30 [00:14<00:02,  2.27it/s] 87%|████████▋ | 26/30 [00:15<00:02,  1.36it/s] 93%|█████████▎| 28/30 [00:16<00:01,  1.65it/s]100%|██████████| 30/30 [00:17<00:00,  1.79it/s]
  0%|          | 0/226 [00:00<?, ?it/s]INFO:__main__:Requesting https://artsexperiments.withgoogle.com/nasasvisualuniverse
INFO:__main__:Getting metadata for https://artsexperiments.withgoogle.com/nasasvisualuniverse
  0%|          | 1/226 [00:00<00:26,  8.37it/s]INFO:__main__:Requesting https://web-in-security.blogspot.com/2019/02/how-to-spoof-pdf-signatures.html
INFO:__main__:Getting metadata for https://web-in-security.blogspot.com/2019/02/how-to-spoof-pdf-signatures.html
  1%|          | 2/226 [00:00<00:43,  5.13it/s]INFO:__main__:Requesting https://helpx.adobe.com/acrobat/using/certificate-based-signatures.html#certifying_and_signing_documents
INFO:__main__:Getting metadata for https://helpx.adobe.com/acrobat/using/certificate-based-signatures.html#certifying_and_signing_documents
  1%|▏         | 3/226 [00:01<01:36,  2.30it/s]INFO:__main__:Requesting https://www.pdf-insecurity.org/signature/viewer.html
INFO:__main__:Getting metadata for https://www.pdf-insecurity.org/signature/viewer.html
  2%|▏         | 4/226 [00:05<05:02,  1.36s/it]INFO:__main__:Requesting https://www.nsa.gov/ghidra
INFO:__main__:Getting metadata for https://www.nsa.gov/resources/everyone/ghidra/
  2%|▏         | 5/226 [00:05<04:15,  1.16s/it]INFO:__main__:Requesting https://docs.binary.ninja/about/license/index.html
INFO:__main__:Getting metadata for https://docs.binary.ninja/about/license/index.html
  3%|▎         | 6/226 [00:06<03:33,  1.03it/s]INFO:__main__:Requesting https://www.hex-rays.com/cgi-bin/quote.cgi
INFO:__main__:Getting metadata for https://www.hex-rays.com/cgi-bin/quote.cgi
  3%|▎         | 7/226 [00:10<06:54,  1.89s/it]INFO:__main__:Requesting https://github.com/BinaryAnalysisPlatform/bap
INFO:__main__:Getting metadata for https://github.com/BinaryAnalysisPlatform/bap
  4%|▎         | 8/226 [00:11<06:34,  1.81s/it]INFO:__main__:Requesting https://github.com/IDArlingTeam/IDArling/
INFO:__main__:Getting metadata for https://github.com/IDArlingTeam/IDArling/
  4%|▍         | 9/226 [00:12<05:37,  1.55s/it]INFO:__main__:Requesting https://www.pnfsoftware.com
INFO:__main__:Getting metadata for https://www.pnfsoftware.com
  4%|▍         | 10/226 [00:14<05:34,  1.55s/it]INFO:__main__:Requesting https://github.com/radare/radare2
INFO:__main__:Getting metadata for https://github.com/radare/radare2
  5%|▍         | 11/226 [00:16<05:52,  1.64s/it]INFO:__main__:Requesting https://github.com/radareorg/cutter
INFO:__main__:Getting metadata for https://github.com/radareorg/cutter
  5%|▌         | 12/226 [00:17<05:23,  1.51s/it]INFO:__main__:Requesting https://github.com/radareorg/radeco
INFO:__main__:Getting metadata for https://github.com/radareorg/radeco
  6%|▌         | 13/226 [00:18<05:08,  1.45s/it]INFO:__main__:Requesting https://news.ycombinator.com/newsguidelines.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/newsguidelines.html
  6%|▌         | 14/226 [00:19<04:48,  1.36s/it]INFO:__main__:Requesting https://github.com/NationalSecurityAgency/ghidra/issues/6
INFO:__main__:Getting metadata for https://github.com/NationalSecurityAgency/ghidra/issues/6
  7%|▋         | 15/226 [00:23<07:08,  2.03s/it]INFO:__main__:Requesting https://www.battelle.org/
INFO:__main__:Getting metadata for https://www.battelle.org
  7%|▋         | 16/226 [00:23<05:15,  1.50s/it]INFO:__main__:Requesting https://ghidra-sre.org/
INFO:__main__:Getting metadata for https://ghidra-sre.org
  8%|▊         | 17/226 [00:24<04:05,  1.17s/it]INFO:__main__:Requesting https://github.com/NationalSecurityAgency/ghidra
INFO:__main__:Getting metadata for https://github.com/NationalSecurityAgency/ghidra
  8%|▊         | 18/226 [00:25<03:46,  1.09s/it]INFO:__main__:Requesting https://github.com/NationalSecurityAgency/ghidra/
INFO:__main__:Getting metadata for https://github.com/NationalSecurityAgency/ghidra/
  8%|▊         | 19/226 [00:26<03:46,  1.10s/it]INFO:__main__:Requesting https://twitter.com/hackerfantastic/status/1103087869063704576
INFO:__main__:Getting metadata for https://twitter.com/hackerfantastic/status/1103087869063704576
  9%|▉         | 20/226 [00:27<04:00,  1.17s/it]INFO:__main__:Requesting https://github.com/redhawksdr
INFO:__main__:Getting metadata for https://github.com/redhawksdr
  9%|▉         | 21/226 [00:29<04:34,  1.34s/it]INFO:__main__:Requesting https://www.hex-rays.com/products/ida/support/download_freeware.shtml
INFO:__main__:Getting metadata for https://www.hex-rays.com/products/ida/support/download_freeware.shtml
 10%|▉         | 22/226 [00:30<04:01,  1.18s/it]INFO:__main__:Requesting https://github.com/NationalSecurityAgency/ghidra/blob/master/NOTICE
INFO:__main__:Getting metadata for https://github.com/NationalSecurityAgency/ghidra/blob/master/NOTICE
 10%|█         | 23/226 [00:31<03:53,  1.15s/it]INFO:__main__:Requesting https://github.com/NationalSecurityAgency/ghidra/blob/master/INTENT.md
INFO:__main__:Getting metadata for https://github.com/NationalSecurityAgency/ghidra/blob/master/INTENT.md
 11%|█         | 24/226 [00:32<03:39,  1.08s/it]INFO:__main__:Requesting https://ghidra-sre.org/GhidraGettingStartedVideo/GhidraGettingStartedVideo_player.html?embedIFrameId=embeddedSmartPlayerInstance&theme=dusk
INFO:__main__:Getting metadata for https://ghidra-sre.org/GhidraGettingStartedVideo/GhidraGettingStartedVideo_player.html?embedIFrameId=embeddedSmartPlayerInstance&theme=dusk
 11%|█         | 25/226 [00:32<02:53,  1.16it/s]INFO:__main__:Requesting https://github.com/avast-tl/retdec
INFO:__main__:Getting metadata for https://github.com/avast-tl/retdec
 12%|█▏        | 26/226 [00:33<03:32,  1.06s/it]INFO:__main__:Requesting https://binary.ninja/purchase/
INFO:__main__:Getting metadata for https://binary.ninja/purchase/
 12%|█▏        | 27/226 [00:34<03:05,  1.07it/s]INFO:__main__:Requesting https://github.com/SELinuxProject
INFO:__main__:Getting metadata for https://github.com/SELinuxProject
 12%|█▏        | 28/226 [00:35<03:01,  1.09it/s]INFO:__main__:Requesting https://github.com/nationalsecurityagency
INFO:__main__:Getting metadata for https://github.com/nationalsecurityagency
 13%|█▎        | 29/226 [00:36<03:00,  1.09it/s]INFO:__main__:Requesting https://wikileaks.org/ciav7p1/cms/page_51183656.html
INFO:__main__:Getting metadata for https://wikileaks.org/ciav7p1/cms/page_51183656.html
 13%|█▎        | 30/226 [00:39<05:01,  1.54s/it]INFO:__main__:Requesting https://coincircle.com/l/50VVxbObg3
INFO:__main__:Getting metadata for https://coincircle.com/earn?r_id=836cf082-a068-4579-8242-b454ba3bb8ab&source=earn&channel=POST_TO_POST_TO_HACKER_NEWS&beta=coincircle123
 14%|█▎        | 31/226 [00:39<04:01,  1.24s/it]INFO:__main__:Requesting https://twitter.com/hackerfantastic/status/1103087869063704576?s=21
INFO:__main__:Getting metadata for https://twitter.com/hackerfantastic/status/1103087869063704576?s=21
 14%|█▍        | 32/226 [00:40<03:40,  1.14s/it]INFO:__main__:Requesting https://ghidrace.github.io/
 15%|█▍        | 33/226 [00:40<02:39,  1.21it/s]INFO:__main__:Requesting https://github.com/withzombies?tab=following
INFO:__main__:Getting metadata for https://github.com/withzombies?tab=following
 15%|█▌        | 34/226 [00:41<02:41,  1.19it/s]INFO:__main__:Requesting https://cppcrypt.tumblr.com/post/168134225802
INFO:__main__:Getting metadata for https://cppcrypt.tumblr.com/post/168134225802
 15%|█▌        | 35/226 [00:42<02:19,  1.37it/s]INFO:__main__:Requesting https://cppcrypt.tumblr.com/archive
INFO:__main__:Getting metadata for https://cppcrypt.tumblr.com/archive
 16%|█▌        | 36/226 [00:43<03:02,  1.04it/s]INFO:__main__:Requesting https://blog.acolyer.org/2019/03/06/keeping-calm-when-distributed-consistency-is-easy/
ERROR:__main__:Could not reach https://blog.acolyer.org/2019/03/06/keeping-calm-when-distributed-consistency-is-easy/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 16%|█▋        | 37/226 [00:43<02:14,  1.41it/s]INFO:__main__:Requesting https://vadosware.io/post/paxosmon-gotta-concensus-them-all
INFO:__main__:Getting metadata for https://vadosware.io/post/paxosmon-gotta-concensus-them-all/
 17%|█▋        | 38/226 [00:45<03:08,  1.00s/it]INFO:__main__:Requesting https://www.researchgate.net/publication/320371248_Pure_Operation-Based_Replicated_Data_Types
 17%|█▋        | 39/226 [00:45<02:28,  1.26it/s]INFO:__main__:Requesting https://www.nationalgeographic.com/culture/2019/03/maya-ritual-balamku-cave-stuns-archaeologists/
ERROR:__main__:Could not reach https://www.nationalgeographic.com/culture/2019/03/maya-ritual-balamku-cave-stuns-archaeologists/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nationalgeographic.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nationalgeographic.com', port=443): Read timed out. (read timeout=6)
 18%|█▊        | 40/226 [00:51<07:22,  2.38s/it]INFO:__main__:Requesting https://imgur.com/EHrwHs3.jpg
INFO:__main__:Getting metadata for https://i.imgur.com/EHrwHs3.jpg
 18%|█▊        | 41/226 [01:17<28:46,  9.33s/it]INFO:__main__:Requesting https://gfycat.com/responsibleboweddalmatian-exploration-caving-nope
INFO:__main__:Getting metadata for https://gfycat.com/responsibleboweddalmatian-exploration-caving-nope
 19%|█▊        | 42/226 [01:17<20:11,  6.59s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=FAY-t32vyds
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=FAY-t32vyds
 19%|█▉        | 43/226 [01:18<14:59,  4.92s/it]INFO:__main__:Requesting https://i.imgur.com/BkmpH9v.jpg
INFO:__main__:Getting metadata for https://i.imgur.com/BkmpH9v.jpg
 19%|█▉        | 44/226 [01:24<15:55,  5.25s/it]INFO:__main__:Requesting https://www.deseretnews.com/article/705347362/Man-trapped-in-Utah-Countys-Nutty-Putty-cave-dies.html
INFO:__main__:Getting metadata for https://www.deseretnews.com/article/705347362/Man-trapped-in-Utah-Countys-Nutty-Putty-cave-dies.html
 20%|█▉        | 45/226 [01:29<15:22,  5.10s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Chaac
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Chaac
 20%|██        | 46/226 [01:30<11:43,  3.91s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Tl%C4%81loc
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Tl%C4%81loc
 21%|██        | 47/226 [01:31<09:14,  3.10s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Maya_codices
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Maya_codices
 21%|██        | 48/226 [01:32<07:28,  2.52s/it]INFO:__main__:Requesting https://www.washingtonpost.com/health/2019/02/28/weekend-catch-up-sleep-is-lie/
ERROR:__main__:Could not reach https://www.washingtonpost.com/health/2019/02/28/weekend-catch-up-sleep-is-lie/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 22%|██▏       | 49/226 [01:39<10:34,  3.59s/it]INFO:__main__:Requesting https://www.huffingtonpost.com/entry/7-scary-ways-sleep-deprivation-affects-teen-physical-and-mental-health_us_55a7bd07e4b04740a3df0fb3
INFO:__main__:Getting metadata for https://www.huffingtonpost.com/entry/7-scary-ways-sleep-deprivation-affects-teen-physical-and-mental-health_us_55a7bd07e4b04740a3df0fb3
 22%|██▏       | 50/226 [01:39<07:34,  2.58s/it]INFO:__main__:Requesting https://www.huffpost.com/entry/teen-sleep-crimes-adults_n_58b70880e4b019d36d0fec64
INFO:__main__:Getting metadata for https://www.huffpost.com/entry/teen-sleep-crimes-adults_n_58b70880e4b019d36d0fec64
ERROR:__main__:Could not get metadata for https://www.huffpost.com/entry/teen-sleep-crimes-adults_n_58b70880e4b019d36d0fec64
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 324, in _decode
    data = self._decoder.decompress(data)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 77, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 466, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 329, in _decode
    "failed to decode it." % content_encoding, e)
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 755, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))
 23%|██▎       | 51/226 [01:39<05:36,  1.92s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Circadian_rhythm
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Circadian_rhythm
 23%|██▎       | 52/226 [01:41<05:39,  1.95s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pubmed/10849238
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pubmed/10849238
 23%|██▎       | 53/226 [01:44<06:43,  2.33s/it]INFO:__main__:Requesting https://www.washingtonpost.com/news/speaking-of-science/wp/2018/05/23/people-who-sleep-in-on-weekends-avoid-dying-young-study-suggests/?utm_term=.283730348877
ERROR:__main__:Could not reach https://www.washingtonpost.com/news/speaking-of-science/wp/2018/05/23/people-who-sleep-in-on-weekends-avoid-dying-young-study-suggests/?utm_term=.283730348877
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 24%|██▍       | 54/226 [01:50<09:53,  3.45s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Replication_crisis
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Replication_crisis
 24%|██▍       | 55/226 [01:52<08:08,  2.86s/it]INFO:__main__:Requesting https://www.sciencealert.com/replication-results-reproducibility-crisis-science-nature-journals
INFO:__main__:Getting metadata for https://www.sciencealert.com/replication-results-reproducibility-crisis-science-nature-journals
 25%|██▍       | 56/226 [01:53<06:11,  2.18s/it]INFO:__main__:Requesting https://onlinelibrary.wiley.com/doi/full/10.1111/jsr.12712
INFO:__main__:Getting metadata for https://onlinelibrary.wiley.com/doi/full/10.1111/jsr.12712
 25%|██▌       | 57/226 [02:00<10:15,  3.64s/it]INFO:__main__:Requesting https://onlinelibrary.wiley.com/doi/pdf/10.1111/jsr.12712
INFO:__main__:Getting metadata for https://onlinelibrary.wiley.com/doi/pdf/10.1111/jsr.12712
 26%|██▌       | 58/226 [02:12<17:26,  6.23s/it]INFO:__main__:Requesting https://www.goodreads.com/book/show/34466963
INFO:__main__:Getting metadata for https://www.goodreads.com/book/show/34466963-why-we-sleep
 26%|██▌       | 59/226 [02:13<13:06,  4.71s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5639921/#!po=7.85124
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5639921/#!po=7.85124
 27%|██▋       | 60/226 [02:15<10:21,  3.74s/it]INFO:__main__:Requesting https://www.goodreads.com/book/show/34466963-why-we-sleep
INFO:__main__:Getting metadata for https://www.goodreads.com/book/show/34466963-why-we-sleep
 27%|██▋       | 61/226 [02:16<08:02,  2.93s/it]INFO:__main__:Requesting https://www.aumilight.com/
INFO:__main__:Getting metadata for https://www.aumilight.com
 27%|██▋       | 62/226 [02:16<05:56,  2.18s/it]INFO:__main__:Requesting https://shop.hatchbaby.com/pages/rest
INFO:__main__:Getting metadata for https://shop.hatchbaby.com/pages/rest
 28%|██▊       | 63/226 [02:16<04:25,  1.63s/it]INFO:__main__:Requesting https://www.keenglow.com/
INFO:__main__:Getting metadata for https://www.keenglow.com
 28%|██▊       | 64/226 [02:17<03:20,  1.24s/it]INFO:__main__:Requesting https://archive.fo/0ruX4
ERROR:__main__:Could not reach https://archive.fo/0ruX4
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/opt/python/3.6.3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='archive.fo', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 757, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='archive.fo', port=443): Read timed out.
 29%|██▉       | 65/226 [02:24<07:51,  2.93s/it]INFO:__main__:Requesting https://www.cell.com/current-biology/fulltext/S0960-9822(19)30098-3
INFO:__main__:Getting metadata for https://www.cell.com/current-biology/fulltext/S0960-9822(19)30098-3
 29%|██▉       | 66/226 [02:29<10:07,  3.80s/it]INFO:__main__:Requesting https://github.com/xgdsmileboy/SimFix
INFO:__main__:Getting metadata for https://github.com/xgdsmileboy/SimFix
 30%|██▉       | 67/226 [02:30<07:52,  2.97s/it]INFO:__main__:Requesting https://github.com/quantifiedcode/quantifiedcode
INFO:__main__:Getting metadata for https://github.com/quantifiedcode/quantifiedcode
 30%|███       | 68/226 [02:31<06:09,  2.34s/it]INFO:__main__:Requesting https://www.theverge.com/transportation/2019/3/5/18250996/sikorsky-autonomous-helicopter-flying-taxi-lockheed
INFO:__main__:Getting metadata for https://www.theverge.com/transportation/2019/3/5/18250996/sikorsky-autonomous-helicopter-flying-taxi-lockheed
 31%|███       | 69/226 [02:31<04:28,  1.71s/it]INFO:__main__:Requesting https://www.bostonglobe.com/metro/2019/03/04/the-backyard-mechanic-who-taking-tesla/Sv1l8q2sxpQvTFMp13VFwM/story.html
INFO:__main__:Getting metadata for https://www.bostonglobe.com/metro/2019/03/04/the-backyard-mechanic-who-taking-tesla/Sv1l8q2sxpQvTFMp13VFwM/story.html
 31%|███       | 70/226 [02:32<03:15,  1.25s/it]INFO:__main__:Requesting https://www.teslarati.com/do-you-own-a-tesla-or-does-a-tesla-own-you/
INFO:__main__:Getting metadata for https://www.teslarati.com/do-you-own-a-tesla-or-does-a-tesla-own-you/
 31%|███▏      | 71/226 [02:32<02:45,  1.07s/it]INFO:__main__:Requesting https://www.wired.com/2015/04/dmca-ownership-john-deere/
INFO:__main__:Getting metadata for https://www.wired.com/2015/04/dmca-ownership-john-deere/
 32%|███▏      | 72/226 [02:33<02:07,  1.21it/s]INFO:__main__:Requesting https://www.youtube.com/channel/UCfV0_wbjG8KJADuZT2ct4SA
INFO:__main__:Getting metadata for https://www.youtube.com/channel/UCfV0_wbjG8KJADuZT2ct4SA
 32%|███▏      | 73/226 [02:36<03:52,  1.52s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Fiesta_(dinnerware)#Radioactive_glazes
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Fiesta_(dinnerware)#Radioactive_glazes
 33%|███▎      | 74/226 [02:37<03:31,  1.39s/it]INFO:__main__:Requesting https://discdepotstandrews.co.uk/copy-iphone-screens-vs-originals/
INFO:__main__:Getting metadata for https://discdepotstandrews.co.uk/copy-iphone-screens-vs-originals/
 33%|███▎      | 75/226 [02:41<05:44,  2.28s/it]INFO:__main__:Requesting https://www.hotshot.repair/mo/columbia/office-banter/lets-talk-about-the-difference-between-original-and-aftermarket-iphone-screens/
INFO:__main__:Getting metadata for https://www.hotshot.repair/mo/columbia/office-banter/lets-talk-about-the-difference-between-original-and-aftermarket-iphone-screens/
 34%|███▎      | 76/226 [02:43<05:06,  2.04s/it]INFO:__main__:Requesting https://youtu.be/NuAMczraBIM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=NuAMczraBIM&feature=youtu.be
 34%|███▍      | 77/226 [02:44<04:22,  1.76s/it]INFO:__main__:Requesting https://www.bbc.com/news/science-environment-39482342
INFO:__main__:Getting metadata for https://www.bbc.com/news/science-environment-39482342
 35%|███▍      | 78/226 [02:44<03:17,  1.34s/it]INFO:__main__:Requesting https://www.reddit.com/r/askscience/comments/6tzy80/graphene_can_do_just_about_anything_except_leave/
ERROR:__main__:Could not reach https://www.reddit.com/r/askscience/comments/6tzy80/graphene_can_do_just_about_anything_except_leave/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=6)
 35%|███▍      | 79/226 [02:50<06:45,  2.76s/it]INFO:__main__:Requesting https://arstechnica.com/science/2011/08/desalinization-is-this-as-good-as-it-gets/
INFO:__main__:Getting metadata for https://arstechnica.com/science/2011/08/desalinization-is-this-as-good-as-it-gets/
 35%|███▌      | 80/226 [02:50<04:51,  1.99s/it]INFO:__main__:Requesting http://science.sciencemag.org/content/333/6043/712
INFO:__main__:Getting metadata for http://science.sciencemag.org/content/333/6043/712
 36%|███▌      | 81/226 [02:53<05:18,  2.19s/it]INFO:__main__:Requesting https://www.mercurynews.com/2014/05/29/nations-largest-ocean-desalination-plant-goes-up-near-san-diego-future-of-the-california-coast/
INFO:__main__:Getting metadata for https://www.mercurynews.com/2014/05/29/nations-largest-ocean-desalination-plant-goes-up-near-san-diego-future-of-the-california-coast/
 36%|███▋      | 82/226 [02:54<04:16,  1.78s/it]INFO:__main__:Requesting https://www.npr.org/sections/money/2011/10/27/141766341/the-price-of-electricity-in-your-state
INFO:__main__:Getting metadata for https://www.npr.org/sections/money/2011/10/27/141766341/the-price-of-electricity-in-your-state
 37%|███▋      | 83/226 [02:55<03:28,  1.46s/it]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2019-01-08/saudi-thirst-for-water-is-seen-creating-a-toxic-brine-problem
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=2ed35110-4021-11e9-86ff-e78679eba0dd&url=L25ld3MvYXJ0aWNsZXMvMjAxOS0wMS0wOC9zYXVkaS10aGlyc3QtZm9yLXdhdGVyLWlzLXNlZW4tY3JlYXRpbmctYS10b3hpYy1icmluZS1wcm9ibGVt
 37%|███▋      | 84/226 [02:55<02:46,  1.18s/it]INFO:__main__:Requesting https://www.aljazeera.com/news/2016/06/israel-water-tool-dominate-palestinians-160619062531348.html
INFO:__main__:Getting metadata for https://www.aljazeera.com/news/2016/06/israel-water-tool-dominate-palestinians-160619062531348.html
 38%|███▊      | 85/226 [02:56<02:18,  1.01it/s]INFO:__main__:Requesting https://water.usgs.gov/edu/qa-home-percapita.html
INFO:__main__:Getting metadata for https://water.usgs.gov/edu/qa-home-percapita.html
 38%|███▊      | 86/226 [02:58<03:05,  1.32s/it]INFO:__main__:Requesting https://www.pine64.org/?product=rockpro64-slim-profile-graphene-heatsink
INFO:__main__:Getting metadata for https://www.pine64.org/?product=rockpro64-slim-profile-graphene-heatsink
 38%|███▊      | 87/226 [03:01<04:40,  2.02s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=qZ5ut_4zKug
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=qZ5ut_4zKug
 39%|███▉      | 88/226 [03:02<03:50,  1.67s/it]INFO:__main__:Requesting https://letoverlambda.com/
INFO:__main__:Getting metadata for https://letoverlambda.com
 39%|███▉      | 89/226 [03:03<03:14,  1.42s/it]INFO:__main__:Requesting https://github.com/nornagon/jonesforth/blob/master/jonesforth.S
INFO:__main__:Getting metadata for https://github.com/nornagon/jonesforth/blob/master/jonesforth.S
 40%|███▉      | 90/226 [03:05<03:48,  1.68s/it]INFO:__main__:Requesting https://old.reddit.com/r/lisp/comments/axu858/here_is_what_we_are_doing_with_common_lisp/
INFO:__main__:Getting metadata for https://old.reddit.com/r/lisp/comments/axu858/here_is_what_we_are_doing_with_common_lisp/
 40%|████      | 91/226 [03:06<03:01,  1.34s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=hZRuGt4TcD8&list=PLbl4KVdl9U3I3MhFWgauT0cz-x7SymZmn&index=4&t=0s
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=hZRuGt4TcD8&list=PLbl4KVdl9U3I3MhFWgauT0cz-x7SymZmn&index=4&t=0s
 41%|████      | 92/226 [03:07<02:39,  1.19s/it]INFO:__main__:Requesting http://www.greghendershott.com/fear-of-macros/fear-of-macros.jpg
INFO:__main__:Getting metadata for http://www.greghendershott.com/fear-of-macros/fear-of-macros.jpg
 41%|████      | 93/226 [03:08<02:20,  1.06s/it]INFO:__main__:Requesting https://letoverlambda.com/index.cl/guest/chap6.html
INFO:__main__:Getting metadata for https://letoverlambda.com/index.cl/guest/chap6.html
 42%|████▏     | 94/226 [03:09<02:30,  1.14s/it]INFO:__main__:Requesting https://github.com/thephoeron/let-over-lambda
INFO:__main__:Getting metadata for https://github.com/thephoeron/let-over-lambda
 42%|████▏     | 95/226 [03:10<02:20,  1.07s/it]INFO:__main__:Requesting http://www.paulgraham.com/onlisptext.html
INFO:__main__:Getting metadata for http://www.paulgraham.com/onlisptext.html
 42%|████▏     | 96/226 [03:10<01:57,  1.11it/s]INFO:__main__:Requesting http://stevelosh.com/blog/2018/08/a-road-to-common-lisp/
INFO:__main__:Getting metadata for http://stevelosh.com/blog/2018/08/a-road-to-common-lisp/
 43%|████▎     | 97/226 [03:11<01:52,  1.15it/s]INFO:__main__:Requesting https://shipilev.net/jvm/anatomy-quarks/23-compressed-references/
INFO:__main__:Getting metadata for https://shipilev.net/jvm/anatomy-quarks/23-compressed-references/
 43%|████▎     | 98/226 [03:14<03:13,  1.51s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Succinct_data_structure
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Succinct_data_structure
 44%|████▍     | 99/226 [03:15<03:05,  1.46s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Compressed_data_structure
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Compressed_data_structure
 44%|████▍     | 100/226 [03:16<02:35,  1.24s/it]INFO:__main__:Requesting https://github.com/rust-lang/rust/pull/45225
INFO:__main__:Getting metadata for https://github.com/rust-lang/rust/pull/45225
 45%|████▍     | 101/226 [03:22<05:29,  2.63s/it]INFO:__main__:Requesting https://github.com/eclipse/openj9
INFO:__main__:Getting metadata for https://github.com/eclipse/openj9
 45%|████▌     | 102/226 [03:23<04:38,  2.25s/it]INFO:__main__:Requesting https://blog.openj9.org/category/jit/aot/
ERROR:__main__:Could not reach https://blog.openj9.org/category/jit/aot/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 46%|████▌     | 103/226 [03:24<03:20,  1.63s/it]INFO:__main__:Requesting http://openjdk.java.net/projects/panama/
INFO:__main__:Getting metadata for http://openjdk.java.net/projects/panama/
 46%|████▌     | 104/226 [03:24<02:38,  1.30s/it]INFO:__main__:Requesting https://www.azul.com/presentation/objectlayout/
INFO:__main__:Getting metadata for https://www.azul.com/presentation/objectlayout/
 46%|████▋     | 105/226 [03:24<01:59,  1.01it/s]INFO:__main__:Requesting https://numenta.com/blog/2019/01/16/the-thousand-brains-theory-of-intelligence/
INFO:__main__:Getting metadata for https://numenta.com/blog/2019/01/16/the-thousand-brains-theory-of-intelligence/
 47%|████▋     | 106/226 [03:25<01:33,  1.28it/s]INFO:__main__:Requesting https://discourse.numenta.org/
INFO:__main__:Getting metadata for https://discourse.numenta.org
 47%|████▋     | 107/226 [03:25<01:26,  1.37it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/BrownBoost
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/BrownBoost
 48%|████▊     | 108/226 [03:26<01:37,  1.22it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Random_forest
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Random_forest
 48%|████▊     | 109/226 [03:28<02:22,  1.22s/it]INFO:__main__:Requesting https://www.theringer.com/tech/2019/3/5/18249733/happiest-day-internet-history-ranking
INFO:__main__:Getting metadata for https://www.theringer.com/tech/2019/3/5/18249733/happiest-day-internet-history-ranking
 49%|████▊     | 110/226 [03:29<01:47,  1.08it/s]INFO:__main__:Requesting https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0026752
INFO:__main__:Getting metadata for https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0026752
 49%|████▉     | 111/226 [03:32<03:04,  1.60s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/2016_United_States_presidential_election
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/2016_United_States_presidential_election
 50%|████▉     | 112/226 [03:39<05:56,  3.13s/it]INFO:__main__:Requesting https://boren.blog/2017/01/26/autistic-burnout-the-cost-of-coping-and-passing/
ERROR:__main__:Could not reach https://boren.blog/2017/01/26/autistic-burnout-the-cost-of-coping-and-passing/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 50%|█████     | 113/226 [03:39<04:11,  2.23s/it]INFO:__main__:Requesting https://boingboing.net/2013/01/05/pedagogyofthedepressed.html
INFO:__main__:Getting metadata for https://boingboing.net/2013/01/05/pedagogyofthedepressed.html
 50%|█████     | 114/226 [03:39<03:01,  1.62s/it]INFO:__main__:Requesting https://psychology-tools.com/test/autism-spectrum-quotient
INFO:__main__:Getting metadata for https://psychology-tools.com/test/autism-spectrum-quotient
 51%|█████     | 115/226 [03:39<02:18,  1.25s/it]INFO:__main__:Requesting https://www.davidsongifted.org/Search-Database/entry/A10900
INFO:__main__:Getting metadata for https://www.davidsongifted.org/Search-Database/entry/A10900
 51%|█████▏    | 116/226 [03:44<04:17,  2.34s/it]INFO:__main__:Requesting https://www.amazon.com/Masks-Mirrors-Generation-Chameleon-Personality/dp/0275973255/
INFO:__main__:Getting metadata for https://www.amazon.com/Masks-Mirrors-Generation-Chameleon-Personality/dp/0275973255/
 52%|█████▏    | 117/226 [03:47<04:18,  2.37s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Factitious_disorder_imposed_on_self
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Factitious_disorder_imposed_on_self
 52%|█████▏    | 118/226 [03:48<03:39,  2.03s/it]INFO:__main__:Requesting https://www.dw.com/en/european-parliament-set-to-end-eu-wide-daylight-savings/a-47775317
INFO:__main__:Getting metadata for https://www.dw.com/en/european-parliament-set-to-end-eu-wide-daylight-saving/a-47775317
 53%|█████▎    | 119/226 [03:49<03:23,  1.91s/it]INFO:__main__:Requesting https://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time
INFO:__main__:Getting metadata for https://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time
 53%|█████▎    | 120/226 [03:50<02:43,  1.54s/it]INFO:__main__:Requesting http://creativedeletion.com/2015/01/28/falsehoods-programmers-date-time-zones.html
INFO:__main__:Getting metadata for http://www.creativedeletion.com/2015/01/28/falsehoods-programmers-date-time-zones.html
 54%|█████▎    | 121/226 [03:50<02:04,  1.18s/it]INFO:__main__:Requesting http://www.legislation.gov.uk/uksi/2002/262/article/2/made
INFO:__main__:Getting metadata for http://www.legislation.gov.uk/uksi/2002/262/article/2/made
 54%|█████▍    | 122/226 [03:51<01:55,  1.11s/it]INFO:__main__:Requesting http://www.webexhibits.org/daylightsaving/usc.html
INFO:__main__:Getting metadata for http://www.webexhibits.org/daylightsaving/usc.html
 54%|█████▍    | 123/226 [03:52<01:44,  1.01s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Daylight_saving_time_in_the_United_States#1966%E2%80%931972:_Federal_standard_established
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Daylight_saving_time_in_the_United_States#1966%E2%80%931972:_Federal_standard_established
 55%|█████▍    | 124/226 [03:53<01:48,  1.07s/it]INFO:__main__:Requesting https://www.livescience.com/56725-does-daylight-saving-time-save-energy.html
INFO:__main__:Getting metadata for https://www.livescience.com/56725-does-daylight-saving-time-save-energy.html
 55%|█████▌    | 125/226 [03:54<01:46,  1.05s/it]INFO:__main__:Requesting https://www.dw.com/en/eu-citizens-feel-times-up-for-changing-clocks/a-45263664
INFO:__main__:Getting metadata for https://www.dw.com/en/eu-citizens-feel-times-up-for-changing-clocks/a-45263664
 56%|█████▌    | 126/226 [03:56<01:52,  1.13s/it]INFO:__main__:Requesting https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52018SC0406
INFO:__main__:Getting metadata for https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52018SC0406
 56%|█████▌    | 127/226 [04:01<03:43,  2.26s/it]INFO:__main__:Requesting https://qz.com/1375622/eu-citizens-voted-to-abolish-daylight-saving-time-in-a-landslide/
INFO:__main__:Getting metadata for https://qz.com/1375622/eu-citizens-voted-to-abolish-daylight-saving-time-in-a-landslide/
 57%|█████▋    | 128/226 [04:01<02:40,  1.64s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Apportionment_in_the_European_Parliament
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Apportionment_in_the_European_Parliament
 57%|█████▋    | 129/226 [04:03<02:58,  1.84s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Degressive_proportionality
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Degressive_proportionality
 58%|█████▊    | 130/226 [04:04<02:24,  1.51s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Daylight_saving_time#History
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Daylight_saving_time#History
 58%|█████▊    | 131/226 [04:06<02:46,  1.75s/it]INFO:__main__:Requesting https://www.timeanddate.com/sun/usa/san-francisco
INFO:__main__:Getting metadata for https://www.timeanddate.com/sun/usa/san-francisco
 58%|█████▊    | 132/226 [04:07<02:27,  1.56s/it]INFO:__main__:Requesting https://www.timeanddate.com/sun/sweden/stockholm
INFO:__main__:Getting metadata for https://www.timeanddate.com/sun/sweden/stockholm
 59%|█████▉    | 133/226 [04:08<02:08,  1.38s/it]INFO:__main__:Requesting https://www.timeanddate.com/sun/usa/honolulu
INFO:__main__:Getting metadata for https://www.timeanddate.com/sun/usa/honolulu
 59%|█████▉    | 134/226 [04:09<01:56,  1.26s/it]INFO:__main__:Requesting https://www.timeanddate.com/sun/norway/narvik
INFO:__main__:Getting metadata for https://www.timeanddate.com/sun/norway/narvik
 60%|█████▉    | 135/226 [04:30<10:58,  7.24s/it]INFO:__main__:Requesting https://qntm.org/abolish
INFO:__main__:Getting metadata for https://qntm.org/abolish
 60%|██████    | 136/226 [04:32<08:28,  5.65s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Swatch_Internet_Time
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Swatch_Internet_Time
 61%|██████    | 137/226 [04:33<06:13,  4.19s/it]INFO:__main__:Requesting https://youtu.be/84aWtseb2-4?t=230
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=84aWtseb2-4&feature=youtu.be&t=230
 61%|██████    | 138/226 [04:34<04:42,  3.21s/it]INFO:__main__:Requesting https://www.nrc.nl/nieuws/2018/12/19/meeste-nederlanders-willen-hele-jaar-wintertijd-a3126390
INFO:__main__:Getting metadata for https://www.nrc.nl/nieuws/2018/12/19/meeste-nederlanders-willen-hele-jaar-wintertijd-a3126390
 62%|██████▏   | 139/226 [04:36<03:55,  2.71s/it]INFO:__main__:Requesting https://europa.eu/european-union/about-eu/institutions-bodies/european-parliament_en
INFO:__main__:Getting metadata for https://europa.eu/european-union/about-eu/institutions-bodies/european-parliament_en
 62%|██████▏   | 140/226 [04:37<03:23,  2.37s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Northern_Cyprus
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Northern_Cyprus
 62%|██████▏   | 141/226 [04:40<03:37,  2.55s/it]INFO:__main__:Requesting https://briefingsforbrexit.com/
INFO:__main__:Getting metadata for https://briefingsforbrexit.com
 63%|██████▎   | 142/226 [04:43<03:51,  2.76s/it]INFO:__main__:Requesting https://www.ibtimes.co.uk/tony-benn-dead-five-questions-power-other-memorable-quotes-1440277
INFO:__main__:Getting metadata for https://www.ibtimes.co.uk/tony-benn-dead-five-questions-power-other-memorable-quotes-1440277
 63%|██████▎   | 143/226 [04:44<02:50,  2.06s/it]INFO:__main__:Requesting https://medium.com/waymo/bringing-3d-perimeter-lidar-to-partners-6beaa7d3dcc2
INFO:__main__:Getting metadata for https://medium.com/waymo/bringing-3d-perimeter-lidar-to-partners-6beaa7d3dcc2
 64%|██████▎   | 144/226 [04:44<02:08,  1.57s/it]INFO:__main__:Requesting https://www.theverge.com/2019/3/6/18252561/waymo-sell-lidar-laser-sensor-av-customer-robot-taxi-competition
INFO:__main__:Getting metadata for https://www.theverge.com/2019/3/6/18252561/waymo-sell-lidar-laser-sensor-av-customer-robot-taxi-competition
 64%|██████▍   | 145/226 [04:45<01:34,  1.17s/it]INFO:__main__:Requesting https://www.python.org/dev/peps/pep-0584/
INFO:__main__:Getting metadata for https://www.python.org/dev/peps/pep-0584/
 65%|██████▍   | 146/226 [04:45<01:11,  1.12it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Liskov_substitution_principle
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Liskov_substitution_principle
 65%|██████▌   | 147/226 [04:46<01:10,  1.13it/s]INFO:__main__:Requesting https://doc.rust-lang.org/stable/src/std/collections/hash/set.rs.html#111-113
INFO:__main__:Getting metadata for https://doc.rust-lang.org/stable/src/std/collections/hash/set.rs.html#111-113
 65%|██████▌   | 148/226 [04:49<02:02,  1.57s/it]INFO:__main__:Requesting https://docs.scala-lang.org/overviews/collections/maps.html
INFO:__main__:Getting metadata for https://docs.scala-lang.org/overviews/collections/maps.html
 66%|██████▌   | 149/226 [04:53<02:54,  2.27s/it]INFO:__main__:Requesting https://bugs.python.org/issue36144#msg336848
INFO:__main__:Getting metadata for https://bugs.python.org/issue36144#msg336848
 66%|██████▋   | 150/226 [04:56<03:24,  2.69s/it]INFO:__main__:Requesting https://www.quantamagazine.org/the-universes-ultimate-complexity-revealed-by-simple-quantum-games-20190305/
INFO:__main__:Getting metadata for https://www.quantamagazine.org/the-universes-ultimate-complexity-revealed-by-simple-quantum-games-20190305/
 67%|██████▋   | 151/226 [04:57<02:26,  1.95s/it]INFO:__main__:Requesting https://www.nytimes.com/2019/03/05/health/depression-treatment-ketamine-fda.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/03/05/health/depression-treatment-ketamine-fda.html
 67%|██████▋   | 152/226 [04:57<01:46,  1.44s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Drug_harmfulness#/media/File:Development_of_a_rational_scale_to_assess_the_harm_of_drugs_of_potential_misuse_(physical_harm_and_dependence,_NA_free_means).svg
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Drug_harmfulness#/media/File:Development_of_a_rational_scale_to_assess_the_harm_of_drugs_of_potential_misuse_(physical_harm_and_dependence,_NA_free_means).svg
 68%|██████▊   | 153/226 [04:58<01:37,  1.33s/it]INFO:__main__:Requesting https://www.amazon.com/dp/B07D1NNGM6/
INFO:__main__:Getting metadata for https://www.amazon.com/dp/B07D1NNGM6/
 68%|██████▊   | 154/226 [05:00<01:54,  1.60s/it]INFO:__main__:Requesting https://erowid.org/chemicals/ketamine/ketamine_dose.shtml#oral
INFO:__main__:Getting metadata for https://erowid.org/chemicals/ketamine/ketamine_dose.shtml#oral
 69%|██████▊   | 155/226 [05:02<01:54,  1.61s/it]INFO:__main__:Requesting https://www.drugs.com/price-guide/ketamine
INFO:__main__:Getting metadata for https://www.drugs.com/price-guide/ketamine
 69%|██████▉   | 156/226 [05:03<01:37,  1.39s/it]INFO:__main__:Requesting https://www.nuffieldtrust.org.uk/resource/rationing-in-the-nhs
INFO:__main__:Getting metadata for https://www.nuffieldtrust.org.uk/resource/rationing-in-the-nhs
 69%|██████▉   | 157/226 [05:06<02:21,  2.05s/it]INFO:__main__:Requesting https://www.nhs.uk/using-the-nhs/nhs-services/visiting-or-moving-to-england/visitors-from-outside-the-european-economic-area-eea/
ERROR:__main__:Could not reach https://www.nhs.uk/using-the-nhs/nhs-services/visiting-or-moving-to-england/visitors-from-outside-the-european-economic-area-eea/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nhs.uk', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nhs.uk', port=443): Read timed out. (read timeout=6)
 70%|██████▉   | 158/226 [05:12<03:41,  3.25s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/List_of_largest_selling_pharmaceutical_products
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/List_of_largest_selling_pharmaceutical_products
 70%|███████   | 159/226 [05:14<02:59,  2.68s/it]INFO:__main__:Requesting https://www.gao.gov/mobile/products/GAO-18-40
INFO:__main__:Getting metadata for https://www.gao.gov/mobile/products/GAO-18-40
 71%|███████   | 160/226 [05:14<02:12,  2.00s/it]INFO:__main__:Requesting https://www.nytimes.com/2014/11/19/upshot/calculating-the-real-costs-of-developing-a-new-drug.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2014/11/19/upshot/calculating-the-real-costs-of-developing-a-new-drug.html
 71%|███████   | 161/226 [05:15<01:47,  1.66s/it]INFO:__main__:Requesting https://www.whitecase.com/publications/alert/supreme-court-says-america-invents-act-did-not-alter-sale-bar
INFO:__main__:Getting metadata for https://www.whitecase.com/publications/alert/supreme-court-says-america-invents-act-did-not-alter-sale-bar
 72%|███████▏  | 162/226 [05:16<01:25,  1.34s/it]INFO:__main__:Requesting https://www.uspto.gov/web/offices/pac/mpep/index.html
INFO:__main__:Getting metadata for https://www.uspto.gov/web/offices/pac/mpep/index.html
 72%|███████▏  | 163/226 [05:17<01:20,  1.28s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4910398/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4910398/
 73%|███████▎  | 164/226 [05:18<01:15,  1.22s/it]INFO:__main__:Requesting https://clinicaltrials.gov/ct2/results?cond=&term=Esketamine+Janssen+&cntry=&state=&city=&dist=&Search=Search
INFO:__main__:Getting metadata for https://clinicaltrials.gov/ct2/results?cond=&term=Esketamine+Janssen+&cntry=&state=&city=&dist=&Search=Search
 73%|███████▎  | 165/226 [05:19<01:07,  1.11s/it]INFO:__main__:Requesting https://www.drugs.com/history/spravato.html
INFO:__main__:Getting metadata for https://www.drugs.com/history/spravato.html
 73%|███████▎  | 166/226 [05:19<00:53,  1.12it/s]INFO:__main__:Requesting https://www.drugs.com/alpha/sp.html
INFO:__main__:Getting metadata for https://www.drugs.com/alpha/sp.html
 74%|███████▍  | 167/226 [05:19<00:41,  1.44it/s]INFO:__main__:Requesting https://twitter.com/melaynalokosky/status/1103114497084940289
INFO:__main__:Getting metadata for https://twitter.com/melaynalokosky/status/1103114497084940289
 74%|███████▍  | 168/226 [05:20<00:40,  1.45it/s]INFO:__main__:Requesting https://www.telegraph.co.uk/culture/art/10561090/Akhenaten-mad-bad-or-brilliant.html
INFO:__main__:Getting metadata for https://www.telegraph.co.uk/culture/art/10561090/Akhenaten-mad-bad-or-brilliant.html
 75%|███████▍  | 169/226 [05:20<00:33,  1.68it/s]INFO:__main__:Requesting https://www.amazon.com/1177-B-C-Civilization-Collapsed-Turning/dp/0691168385
INFO:__main__:Getting metadata for https://www.amazon.com/1177-B-C-Civilization-Collapsed-Turning/dp/0691168385
 75%|███████▌  | 170/226 [05:23<01:13,  1.30s/it]INFO:__main__:Requesting https://www.eno.org/whats-on/akhnaten/
INFO:__main__:Getting metadata for https://www.eno.org/whats-on/akhnaten/
 76%|███████▌  | 171/226 [05:25<01:21,  1.49s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=jEYPaZeLhLg
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=jEYPaZeLhLg
 76%|███████▌  | 172/226 [05:26<01:10,  1.31s/it]INFO:__main__:Requesting https://philosophynow.org/issues/128/Does_Western_Philosophy_Have_Egyptian_Roots
INFO:__main__:Getting metadata for https://philosophynow.org/issues/128/Does_Western_Philosophy_Have_Egyptian_Roots
 77%|███████▋  | 173/226 [05:31<02:04,  2.36s/it]INFO:__main__:Requesting https://www.tesorio.com/careers/
INFO:__main__:Getting metadata for https://www.tesorio.com/careers/
 77%|███████▋  | 174/226 [05:31<01:33,  1.79s/it]INFO:__main__:Requesting https://twitter.com/antoniogm/status/1103190266930913281
INFO:__main__:Getting metadata for https://twitter.com/antoniogm/status/1103190266930913281
 77%|███████▋  | 175/226 [05:32<01:18,  1.54s/it]INFO:__main__:Requesting https://physics.aps.org/articles/v12/23
INFO:__main__:Getting metadata for https://physics.aps.org/articles/v12/23
 78%|███████▊  | 176/226 [05:34<01:14,  1.48s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Stokes_drift
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Stokes_drift
 78%|███████▊  | 177/226 [05:35<01:13,  1.50s/it]INFO:__main__:Requesting https://www.pnas.org/content/110/31/12549
INFO:__main__:Getting metadata for https://www.pnas.org/content/110/31/12549
 79%|███████▉  | 178/226 [05:39<01:51,  2.33s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Sound
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Sound
 79%|███████▉  | 179/226 [05:41<01:37,  2.07s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Longitudinal_wave
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Longitudinal_wave
 80%|███████▉  | 180/226 [05:42<01:20,  1.75s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Photoelectric_effect
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Photoelectric_effect
 80%|████████  | 181/226 [05:44<01:21,  1.82s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Baryon_acoustic_oscillations
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Baryon_acoustic_oscillations
 81%|████████  | 182/226 [05:45<01:15,  1.72s/it]INFO:__main__:Requesting https://www.ligo.org/science/GW-Inspiral.php
INFO:__main__:Getting metadata for https://www.ligo.org/science/GW-Inspiral.php
 81%|████████  | 183/226 [05:47<01:08,  1.60s/it]INFO:__main__:Requesting https://theconversation.com/explainer-why-you-can-hear-gravitational-waves-when-things-collide-in-the-universe-92356
INFO:__main__:Getting metadata for https://theconversation.com/explainer-why-you-can-hear-gravitational-waves-when-things-collide-in-the-universe-92356
 81%|████████▏ | 184/226 [05:47<00:55,  1.32s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Photoacoustic_spectroscopy
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Photoacoustic_spectroscopy
 82%|████████▏ | 185/226 [05:48<00:47,  1.16s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=eUzB0L0mSCI
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=eUzB0L0mSCI
 82%|████████▏ | 186/226 [05:49<00:44,  1.10s/it]INFO:__main__:Requesting http://abedavis.com
INFO:__main__:Getting metadata for http://abedavis.com
 83%|████████▎ | 187/226 [05:50<00:40,  1.03s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/List_of_quasiparticles
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/List_of_quasiparticles
 83%|████████▎ | 188/226 [05:51<00:39,  1.03s/it]INFO:__main__:Requesting https://www.reuters.com/article/us-usa-internet/democrats-to-push-to-reinstate-repealed-net-neutrality-rules-idUSKCN1QL1W0/
INFO:__main__:Getting metadata for https://www.reuters.com/article/us-usa-internet/democrats-to-push-to-reinstate-repealed-net-neutrality-rules-idUSKCN1QL1W0/
 84%|████████▎ | 189/226 [05:51<00:30,  1.23it/s]INFO:__main__:Requesting https://www.huffingtonpost.com/entry/net-neutrality-in-2017-what-you-should-know_us_599debf0e4b06d67e334fa94
INFO:__main__:Getting metadata for https://www.huffingtonpost.com/entry/net-neutrality-in-2017-what-you-should-know_us_599debf0e4b06d67e334fa94
 84%|████████▍ | 190/226 [05:52<00:24,  1.48it/s]INFO:__main__:Requesting https://www.recode.net/2018/12/12/18134899/internet-broafband-faster-ookla
INFO:__main__:Getting metadata for https://www.recode.net/2018/12/12/18134899/internet-broafband-faster-ookla
 85%|████████▍ | 191/226 [05:52<00:21,  1.64it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Monopoly
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Monopoly
 85%|████████▍ | 192/226 [05:55<00:43,  1.27s/it]INFO:__main__:Requesting https://www.snopes.com/fact-check/pelosi-healthcare-pass-the-bill-to-see-what-is-in-it/
INFO:__main__:Getting metadata for https://www.snopes.com/fact-check/pelosi-healthcare-pass-the-bill-to-see-what-is-in-it/
 85%|████████▌ | 193/226 [05:55<00:34,  1.04s/it]INFO:__main__:Requesting https://www.realclearpolitics.com/fact_check_review/
INFO:__main__:Getting metadata for https://www.realclearpolitics.com/fact_check_review/
 86%|████████▌ | 194/226 [05:56<00:29,  1.08it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Read_the_Bills_Act
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Read_the_Bills_Act
 86%|████████▋ | 195/226 [05:57<00:26,  1.16it/s]INFO:__main__:Requesting https://www.congress.gov/bill/111th-congress/house-bill/3590/all-actions
INFO:__main__:Getting metadata for https://www.congress.gov/bill/111th-congress/house-bill/3590/all-actions
 87%|████████▋ | 196/226 [05:58<00:26,  1.12it/s]INFO:__main__:Requesting https://www.congress.gov/bill/111th-congress/house-bill/4872/actions
INFO:__main__:Getting metadata for https://www.congress.gov/bill/111th-congress/house-bill/4872/actions
 87%|████████▋ | 197/226 [05:59<00:28,  1.01it/s]INFO:__main__:Requesting https://reddit.com/r/KeepOurNetFree/comments/7ej1nd/fcc_unveils_its_plan_to_repeal_net_neutrality/dq5hlwd/
INFO:__main__:Getting metadata for https://www.reddit.com/r/KeepOurNetFree/comments/7ej1nd/fcc_unveils_its_plan_to_repeal_net_neutrality/dq5hlwd/
 88%|████████▊ | 198/226 [06:01<00:35,  1.28s/it]INFO:__main__:Requesting https://nocable.org/news/whats-happened-in-the-three-months-since-net-neutrality-was-repealed
INFO:__main__:Getting metadata for https://nocable.org/news/whats-happened-in-the-three-months-since-net-neutrality-was-repealed
 88%|████████▊ | 199/226 [06:02<00:32,  1.20s/it]INFO:__main__:Requesting https://stratechery.com/2017/pro-neutrality-anti-title-ii/
INFO:__main__:Getting metadata for https://stratechery.com/2017/pro-neutrality-anti-title-ii/
 88%|████████▊ | 200/226 [06:02<00:24,  1.08it/s]INFO:__main__:Requesting https://patents.google.com/patent/US20180376299A1
INFO:__main__:Getting metadata for https://patents.google.com/patent/US20180376299A1
 89%|████████▉ | 201/226 [06:04<00:26,  1.06s/it]INFO:__main__:Requesting http://bytecollector.com/hp_01.htm
INFO:__main__:Getting metadata for http://bytecollector.com/hp_01.htm
 89%|████████▉ | 202/226 [06:04<00:20,  1.15it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=gGQrsSEaZkI
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=gGQrsSEaZkI
 90%|████████▉ | 203/226 [06:05<00:20,  1.15it/s]INFO:__main__:Requesting https://www.americanradiohistory.com/Byte_Magazine.htm
INFO:__main__:Getting metadata for https://www.americanradiohistory.com/Byte_Magazine.htm
 90%|█████████ | 204/226 [06:07<00:26,  1.20s/it]INFO:__main__:Requesting https://archive.org/details/byte-magazine
INFO:__main__:Getting metadata for https://archive.org/details/byte-magazine
 91%|█████████ | 205/226 [06:10<00:37,  1.80s/it]INFO:__main__:Requesting https://www.americanradiohistory.com/Popular-Electronics-Guide.htm
INFO:__main__:Getting metadata for https://www.americanradiohistory.com/Popular-Electronics-Guide.htm
 91%|█████████ | 206/226 [06:13<00:44,  2.22s/it]INFO:__main__:Requesting https://archive.org/details/creativecomputing
ERROR:__main__:Could not reach https://archive.org/details/creativecomputing
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='archive.org', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='archive.org', port=443): Read timed out. (read timeout=6)
 92%|█████████▏| 207/226 [06:19<01:04,  3.41s/it]INFO:__main__:Requesting https://www.bbc.co.uk/news/business-46895770
INFO:__main__:Getting metadata for https://www.bbc.co.uk/news/business-46895770
 92%|█████████▏| 208/226 [06:22<00:54,  3.05s/it]INFO:__main__:Requesting https://fred.stlouisfed.org/series/DRSFRMACBS
INFO:__main__:Getting metadata for https://fred.stlouisfed.org/series/DRSFRMACBS
 92%|█████████▏| 209/226 [06:22<00:38,  2.27s/it]INFO:__main__:Requesting https://www.theguardian.com/cities/gallery/2017/jun/07/boxed-life-inside-hong-kong-coffin-cubicles-cage-homes-in-pictures
INFO:__main__:Getting metadata for https://www.theguardian.com/cities/gallery/2017/jun/07/boxed-life-inside-hong-kong-coffin-cubicles-cage-homes-in-pictures
 93%|█████████▎| 210/226 [06:22<00:26,  1.68s/it]INFO:__main__:Requesting https://www.syndikat.org/en/
INFO:__main__:Getting metadata for https://www.syndikat.org/en/
 93%|█████████▎| 211/226 [06:26<00:34,  2.31s/it]INFO:__main__:Requesting https://lwn.net/SubscriberLink/780556/9033277f8328f060/
INFO:__main__:Getting metadata for https://lwn.net/SubscriberLink/780556/9033277f8328f060/
 94%|█████████▍| 212/226 [06:27<00:25,  1.80s/it]INFO:__main__:Requesting https://web.archive.org/web/20190305032007/https://lwn.net/SubscriberLink/780556/9033277f8328f060/
ERROR:__main__:Could not reach https://web.archive.org/web/20190305032007/https://lwn.net/SubscriberLink/780556/9033277f8328f060/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b113335c0>, 'Connection to web.archive.org timed out. (connect timeout=6)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190305032007/https://lwn.net/SubscriberLink/780556/9033277f8328f060/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b113335c0>, 'Connection to web.archive.org timed out. (connect timeout=6)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190305032007/https://lwn.net/SubscriberLink/780556/9033277f8328f060/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b113335c0>, 'Connection to web.archive.org timed out. (connect timeout=6)'))
 94%|█████████▍| 213/226 [06:33<00:39,  3.07s/it]INFO:__main__:Requesting https://lwn.net/op/FAQ.lwn#slinks
INFO:__main__:Getting metadata for https://lwn.net/op/FAQ.lwn#slinks
 95%|█████████▍| 214/226 [06:34<00:28,  2.40s/it]INFO:__main__:Requesting https://paddle.com/
INFO:__main__:Getting metadata for https://paddle.com
 95%|█████████▌| 215/226 [06:34<00:19,  1.80s/it]INFO:__main__:Requesting https://streamlabs.com/
INFO:__main__:Getting metadata for https://streamlabs.com
 96%|█████████▌| 216/226 [06:34<00:13,  1.32s/it]INFO:__main__:Requesting https://venturebeat.com/2018/10/07/how-streamlabs-is-helping-livestreamers-monetize-their-audience-via-tips/
INFO:__main__:Getting metadata for https://venturebeat.com/2018/10/07/how-streamlabs-is-helping-livestreamers-monetize-their-audience-via-tips/
 96%|█████████▌| 217/226 [06:36<00:11,  1.31s/it]INFO:__main__:Requesting https://github.com/liberapay/liberapay.com
INFO:__main__:Getting metadata for https://github.com/liberapay/liberapay.com
 96%|█████████▋| 218/226 [06:37<00:09,  1.24s/it]INFO:__main__:Requesting https://hatreon.net/
INFO:__main__:Getting metadata for https://hatreon.net
 97%|█████████▋| 219/226 [06:37<00:07,  1.01s/it]INFO:__main__:Requesting https://newproject2.com/
INFO:__main__:Getting metadata for https://newproject2.com
 97%|█████████▋| 220/226 [06:38<00:06,  1.01s/it]INFO:__main__:Requesting https://www.sharetribe.com/academy/how-to-design-your-marketplaces-transaction-flow/
INFO:__main__:Getting metadata for https://www.sharetribe.com/academy/how-to-design-your-marketplaces-transaction-flow/
 98%|█████████▊| 221/226 [06:38<00:03,  1.31it/s]INFO:__main__:Requesting https://geoffkratz.wordpress.com/2017/12/10/is-patreon-about-regulations/
ERROR:__main__:Could not reach https://geoffkratz.wordpress.com/2017/12/10/is-patreon-about-regulations/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 98%|█████████▊| 222/226 [06:39<00:02,  1.72it/s]INFO:__main__:Requesting https://stripe.com/connect
INFO:__main__:Getting metadata for https://stripe.com/connect
 99%|█████████▊| 223/226 [06:40<00:02,  1.37it/s]INFO:__main__:Requesting https://paymentscompliance.com/us-money-transmitters
INFO:__main__:Getting metadata for https://paymentscompliance.com/us-money-transmitters
 99%|█████████▉| 224/226 [06:45<00:04,  2.11s/it]INFO:__main__:Requesting https://liberapay.com/
INFO:__main__:Getting metadata for https://liberapay.com
100%|█████████▉| 225/226 [06:46<00:01,  1.88s/it]INFO:__main__:Requesting https://techcrunch.com/video/patreon-the-idea/
ERROR:__main__:Could not reach https://techcrunch.com/video/patreon-the-idea/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
100%|██████████| 226/226 [06:46<00:00,  1.35s/it]
