INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:26,  1.11it/s] 10%|█         | 3/30 [00:01<00:18,  1.48it/s] 13%|█▎        | 4/30 [00:02<00:20,  1.26it/s] 20%|██        | 6/30 [00:07<00:31,  1.31s/it] 23%|██▎       | 7/30 [00:07<00:23,  1.01s/it] 27%|██▋       | 8/30 [00:08<00:20,  1.07it/s] 33%|███▎      | 10/30 [00:08<00:13,  1.49it/s] 40%|████      | 12/30 [00:08<00:09,  1.85it/s] 43%|████▎     | 13/30 [00:09<00:08,  1.90it/s] 47%|████▋     | 14/30 [00:10<00:09,  1.70it/s] 53%|█████▎    | 16/30 [00:10<00:06,  2.06it/s] 60%|██████    | 18/30 [00:10<00:04,  2.71it/s] 63%|██████▎   | 19/30 [00:11<00:03,  3.00it/s] 73%|███████▎  | 22/30 [00:11<00:02,  3.64it/s] 77%|███████▋  | 23/30 [00:11<00:01,  4.21it/s] 80%|████████  | 24/30 [00:11<00:01,  4.07it/s] 87%|████████▋ | 26/30 [00:12<00:00,  5.31it/s] 90%|█████████ | 27/30 [00:12<00:00,  3.84it/s] 93%|█████████▎| 28/30 [00:13<00:00,  2.52it/s] 97%|█████████▋| 29/30 [00:16<00:01,  1.33s/it]100%|██████████| 30/30 [00:17<00:00,  1.06s/it]
  0%|          | 0/235 [00:00<?, ?it/s]INFO:__main__:Requesting http://immersivemath.com/ila/index.html
INFO:__main__:Getting metadata for http://immersivemath.com/ila/index.html
  0%|          | 1/235 [00:03<14:41,  3.77s/it]INFO:__main__:Requesting http://joshua.smcvt.edu/linearalgebra/
INFO:__main__:Getting metadata for http://joshua.smcvt.edu/linearalgebra/
ERROR:__main__:Could not get metadata for http://joshua.smcvt.edu/linearalgebra/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  1%|          | 2/235 [00:04<10:51,  2.80s/it]INFO:__main__:Requesting http://webwork.maa.org/
INFO:__main__:Getting metadata for http://webwork.maa.org
  1%|▏         | 3/235 [00:04<08:03,  2.08s/it]INFO:__main__:Requesting https://crastina.se/theres-no-projects-like-side-projects/
INFO:__main__:Getting metadata for https://crastina.se/theres-no-projects-like-side-projects/
  2%|▏         | 4/235 [00:11<13:08,  3.41s/it]INFO:__main__:Requesting http://quantumgame.io/
INFO:__main__:Getting metadata for http://quantumgame.io
  2%|▏         | 5/235 [00:13<11:18,  2.95s/it]INFO:__main__:Requesting https://ximera.osu.edu/mooculus
INFO:__main__:Getting metadata for https://ximera.osu.edu/mooculus
  3%|▎         | 6/235 [00:13<08:48,  2.31s/it]INFO:__main__:Requesting http://pat.perso.ens-lyon.org/M1P1/
INFO:__main__:Getting metadata for http://pat.perso.ens-lyon.org/M1P1/
  3%|▎         | 7/235 [00:15<08:15,  2.17s/it]INFO:__main__:Requesting https://openstax.org/
INFO:__main__:Getting metadata for https://openstax.org
  3%|▎         | 8/235 [00:16<07:08,  1.89s/it]INFO:__main__:Requesting https://open.umn.edu/opentextbooks/
INFO:__main__:Getting metadata for https://open.umn.edu/opentextbooks/
  4%|▍         | 9/235 [00:18<06:52,  1.83s/it]INFO:__main__:Requesting http://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AlgebraTrigIntro.aspx
INFO:__main__:Getting metadata for http://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AlgebraTrigIntro.aspx
  4%|▍         | 10/235 [00:20<07:00,  1.87s/it]INFO:__main__:Requesting https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
INFO:__main__:Getting metadata for https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
  5%|▍         | 11/235 [00:24<09:22,  2.51s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
  5%|▌         | 12/235 [00:25<07:44,  2.08s/it]INFO:__main__:Requesting http://abstract.ups.edu/aata/
INFO:__main__:Getting metadata for http://abstract.ups.edu/aata/
  6%|▌         | 13/235 [00:28<08:15,  2.23s/it]INFO:__main__:Requesting http://linear.pugetsound.edu/html/fcla.html
INFO:__main__:Getting metadata for http://linear.pugetsound.edu/html/fcla.html
  6%|▌         | 14/235 [00:30<07:56,  2.16s/it]INFO:__main__:Requesting https://physicstoday.scitation.org/doi/full/10.1063/1.1768652
INFO:__main__:Getting metadata for https://physicstoday.scitation.org/action/captchaChallenge?redirectUrl=https%3A%2F%2Fphysicstoday.scitation.org%2Fdoi%2Ffull%2F10.1063%2F1.1768652
  6%|▋         | 15/235 [00:33<08:31,  2.32s/it]INFO:__main__:Requesting http://www.math.harvard.edu/~elkies/M55a.17/index.html
INFO:__main__:Getting metadata for http://www.math.harvard.edu/~elkies/M55a.17/index.html
ERROR:__main__:Could not get metadata for http://www.math.harvard.edu/~elkies/M55a.17/index.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  7%|▋         | 16/235 [00:34<07:11,  1.97s/it]INFO:__main__:Requesting http://setosa.io/ev/eigenvectors-and-eigenvalues/
INFO:__main__:Getting metadata for http://setosa.io/ev/eigenvectors-and-eigenvalues/
ERROR:__main__:Could not get metadata for http://setosa.io/ev/eigenvectors-and-eigenvalues/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  7%|▋         | 17/235 [00:34<05:15,  1.45s/it]INFO:__main__:Requesting https://www.amazon.com/Visual-Group-Theory-Problem-Book/dp/088385757X
INFO:__main__:Getting metadata for https://www.amazon.com/Visual-Group-Theory-Problem-Book/dp/088385757X
  8%|▊         | 18/235 [00:36<05:58,  1.65s/it]INFO:__main__:Requesting http://lion137.blogspot.com/2019/02/fundamental-algorithms-iii.html
INFO:__main__:Getting metadata for http://lion137.blogspot.com/2019/02/fundamental-algorithms-iii.html
  8%|▊         | 19/235 [00:36<04:20,  1.20s/it]INFO:__main__:Requesting https://docs.google.com/document/d/1xVrPoNutyqTdQ04DXBEZW4ZW4A5RAQW2he7qIpTmG-M/edit
INFO:__main__:Getting metadata for https://docs.google.com/document/d/1xVrPoNutyqTdQ04DXBEZW4ZW4A5RAQW2he7qIpTmG-M/preview?sle=true
  9%|▊         | 20/235 [00:37<04:23,  1.23s/it]INFO:__main__:Requesting https://gist.github.com/shobotch/5160017
INFO:__main__:Getting metadata for https://gist.github.com/shobotch/5160017
  9%|▉         | 21/235 [00:38<03:52,  1.09s/it]INFO:__main__:Requesting https://twitter.com/kevinriggle/status/23932444186
INFO:__main__:Getting metadata for https://twitter.com/kevinriggle/status/23932444186
  9%|▉         | 22/235 [00:39<03:24,  1.04it/s]INFO:__main__:Requesting https://twitter.com/mauritscorneIis
INFO:__main__:Getting metadata for https://twitter.com/mauritscorneIis
 10%|▉         | 23/235 [00:42<05:30,  1.56s/it]INFO:__main__:Requesting https://github.com/pomber/escher-bot
INFO:__main__:Getting metadata for https://github.com/pomber/escher-bot
 10%|█         | 24/235 [00:43<04:35,  1.31s/it]INFO:__main__:Requesting https://www.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
INFO:__main__:Getting metadata for https://www.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
 11%|█         | 25/235 [00:43<03:54,  1.12s/it]INFO:__main__:Requesting https://dothemath.ucsd.edu/2012/06/heat-pumps-work-miracles/
INFO:__main__:Getting metadata for https://dothemath.ucsd.edu/2012/06/heat-pumps-work-miracles/
 11%|█         | 26/235 [00:46<05:56,  1.70s/it]INFO:__main__:Requesting https://www.energy.gov/eere/solar/articles/solar-radiation-basics
 11%|█▏        | 27/235 [00:47<04:21,  1.26s/it]INFO:__main__:Requesting https://www.nrel.gov/gis/images/map_pv_us_january_dec2008.jpg
INFO:__main__:Getting metadata for https://www.nrel.gov/gis/images/map_pv_us_january_dec2008.jpg
ERROR:__main__:Could not get metadata for https://www.nrel.gov/gis/images/map_pv_us_january_dec2008.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 12%|█▏        | 28/235 [00:52<08:40,  2.51s/it]INFO:__main__:Requesting https://www.nrel.gov/gis/images/map_pv_us_july_dec2008.jpg
INFO:__main__:Getting metadata for https://www.nrel.gov/gis/images/map_pv_us_july_dec2008.jpg
ERROR:__main__:Could not get metadata for https://www.nrel.gov/gis/images/map_pv_us_july_dec2008.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 12%|█▏        | 29/235 [00:57<11:30,  3.35s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Mechanical_equivalent_of_heat
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Mechanical_equivalent_of_heat
 13%|█▎        | 30/235 [00:58<08:51,  2.59s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=GjcOobt9Ef8
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=GjcOobt9Ef8
 13%|█▎        | 31/235 [00:59<07:08,  2.10s/it]INFO:__main__:Requesting https://commons.wikimedia.org/wiki/File:Joule_Apparatus.jpg
INFO:__main__:Getting metadata for https://commons.wikimedia.org/wiki/File:Joule_Apparatus.jpg
 14%|█▎        | 32/235 [01:00<05:43,  1.69s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Great_Molasses_Flood
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Great_Molasses_Flood
 14%|█▍        | 33/235 [01:01<05:18,  1.58s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Electromigration
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Electromigration
 14%|█▍        | 34/235 [01:02<05:00,  1.50s/it]INFO:__main__:Requesting https://www.lowtechmagazine.com/2013/03/the-mechanical-transmission-of-power-3-wire-ropes.html
INFO:__main__:Getting metadata for https://www.lowtechmagazine.com/2013/03/the-mechanical-transmission-of-power-3-wire-ropes.html
 15%|█▍        | 35/235 [01:04<04:56,  1.48s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/District_heating
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/District_heating
 15%|█▌        | 36/235 [01:06<05:25,  1.63s/it]INFO:__main__:Requesting https://solar.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
INFO:__main__:Getting metadata for https://solar.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
 16%|█▌        | 37/235 [01:07<05:19,  1.61s/it]INFO:__main__:Requesting https://solar.lowtechmagazine.com/about/
INFO:__main__:Getting metadata for https://solar.lowtechmagazine.com/about/
 16%|█▌        | 38/235 [01:09<05:37,  1.72s/it]INFO:__main__:Requesting https://jacquesmattheij.com/how-to-build-a-windmill/
INFO:__main__:Getting metadata for https://jacquesmattheij.com/how-to-build-a-windmill/
 17%|█▋        | 39/235 [01:12<06:43,  2.06s/it]INFO:__main__:Requesting https://web.archive.org/web/20160813143636/http://www.jacquesmattheij.com/how-to-build-a-windmill
INFO:__main__:Getting metadata for https://web.archive.org/web/20160813143636/http://www.jacquesmattheij.com/how-to-build-a-windmill
 17%|█▋        | 40/235 [01:15<07:29,  2.31s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Vortex_tube
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Vortex_tube
 17%|█▋        | 41/235 [01:16<06:12,  1.92s/it]INFO:__main__:Requesting https://aleksandarmilicevic.github.io/hola/
INFO:__main__:Getting metadata for https://aleksandarmilicevic.github.io/hola/
 18%|█▊        | 42/235 [01:17<05:08,  1.60s/it]INFO:__main__:Requesting http://alloy.lcs.mit.edu/alloy/index.html
INFO:__main__:Getting metadata for http://alloy.lcs.mit.edu/alloy/index.html
ERROR:__main__:Could not get metadata for http://alloy.lcs.mit.edu/alloy/index.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 18%|█▊        | 43/235 [01:18<04:37,  1.45s/it]INFO:__main__:Requesting https://www.hillelwayne.com/tags/alloy/
INFO:__main__:Getting metadata for https://www.hillelwayne.com/tags/alloy/
ERROR:__main__:Could not get metadata for https://www.hillelwayne.com/tags/alloy/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 19%|█▊        | 44/235 [01:18<03:23,  1.06s/it]INFO:__main__:Requesting https://redalemeden.com/blog/2019/we-need-chrome-no-more
INFO:__main__:Getting metadata for https://redalemeden.com/blog/2019/we-need-chrome-no-more/
 19%|█▉        | 45/235 [01:19<03:13,  1.02s/it]INFO:__main__:Requesting https://news.softpedia.com/news/Lead-Firebug-Developer-Joins-Google-Chrome-Team-212278.shtml
ERROR:__main__:Could not reach https://news.softpedia.com/news/Lead-Firebug-Developer-Joins-Google-Chrome-Team-212278.shtml
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f075d712550>, 'Connection to news.softpedia.com timed out. (connect timeout=6)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='news.softpedia.com', port=443): Max retries exceeded with url: /news/Lead-Firebug-Developer-Joins-Google-Chrome-Team-212278.shtml (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f075d712550>, 'Connection to news.softpedia.com timed out. (connect timeout=6)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='news.softpedia.com', port=443): Max retries exceeded with url: /news/Lead-Firebug-Developer-Joins-Google-Chrome-Team-212278.shtml (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f075d712550>, 'Connection to news.softpedia.com timed out. (connect timeout=6)'))
 20%|█▉        | 46/235 [01:43<25:07,  7.98s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=885508#c49
 20%|██        | 47/235 [01:44<17:47,  5.68s/it]INFO:__main__:Requesting https://9to5google.com/2018/12/03/microsoft-chrome-based-browser/
INFO:__main__:Getting metadata for https://9to5google.com/2018/12/03/microsoft-chrome-based-browser/
 20%|██        | 48/235 [01:44<12:57,  4.16s/it]INFO:__main__:Requesting https://www.cnet.com/news/why-i-switched-from-firefox-to-chrome/
INFO:__main__:Getting metadata for https://www.cnet.com/news/why-i-switched-from-firefox-to-chrome/
 21%|██        | 49/235 [01:45<10:08,  3.27s/it]INFO:__main__:Requesting https://imgur.com/gallery/WWZxj
INFO:__main__:Getting metadata for https://imgur.com/gallery/WWZxj
 21%|██▏       | 50/235 [01:46<07:39,  2.49s/it]INFO:__main__:Requesting https://www.google.com/googlebooks/chrome/
INFO:__main__:Getting metadata for https://www.google.com/googlebooks/chrome/
 22%|██▏       | 51/235 [01:46<05:27,  1.78s/it]INFO:__main__:Requesting https://getpolarized.io/
INFO:__main__:Getting metadata for https://getpolarized.io
 22%|██▏       | 52/235 [01:47<04:08,  1.36s/it]INFO:__main__:Requesting https://googleblog.blogspot.com/2008/09/fresh-take-on-browser.html
INFO:__main__:Getting metadata for https://googleblog.blogspot.com/2008/09/fresh-take-on-browser.html
 23%|██▎       | 53/235 [01:47<03:06,  1.03s/it]INFO:__main__:Requesting https://developers.google.com/web/updates/2019/01/devtools
INFO:__main__:Getting metadata for https://developers.google.com/web/updates/2019/01/devtools
 23%|██▎       | 54/235 [01:48<02:53,  1.04it/s]INFO:__main__:Requesting https://developers.google.com/web/updates/2018/05/devtools
INFO:__main__:Getting metadata for https://developers.google.com/web/updates/2018/05/devtools
 23%|██▎       | 55/235 [01:49<02:46,  1.08it/s]INFO:__main__:Requesting https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts
INFO:__main__:Getting metadata for https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts
 24%|██▍       | 56/235 [01:49<02:21,  1.27it/s]INFO:__main__:Requesting https://websocket.org/echo.html
INFO:__main__:Getting metadata for https://websocket.org/echo.html
 24%|██▍       | 57/235 [01:50<02:29,  1.19it/s]INFO:__main__:Requesting https://www.xkcd.com/1053/
INFO:__main__:Getting metadata for https://www.xkcd.com/1053/
 25%|██▍       | 58/235 [01:50<02:09,  1.37it/s]INFO:__main__:Requesting https://screenshots.firefox.com/
INFO:__main__:Getting metadata for https://screenshots.firefox.com
 25%|██▌       | 59/235 [01:51<02:00,  1.46it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Internet_Explorer#/media/File:Internet-explorer-usage-data.svg
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Internet_Explorer#/media/File:Internet-explorer-usage-data.svg
 26%|██▌       | 60/235 [01:53<03:26,  1.18s/it]INFO:__main__:Requesting https://support.mozilla.org/en-US/questions/1206101
INFO:__main__:Getting metadata for https://support.mozilla.org/en-US/questions/1206101
 26%|██▌       | 61/235 [01:56<04:34,  1.58s/it]INFO:__main__:Requesting http://gs.statcounter.com/browser-market-share#monthly-200901-201902
INFO:__main__:Getting metadata for http://gs.statcounter.com/browser-market-share#monthly-200901-201902
 26%|██▋       | 62/235 [01:57<04:02,  1.40s/it]INFO:__main__:Requesting https://pianop.ly/
INFO:__main__:Getting metadata for https://pianop.ly
ERROR:__main__:Could not get metadata for https://pianop.ly
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 27%|██▋       | 63/235 [01:58<03:57,  1.38s/it]INFO:__main__:Requesting https://github.com/chromium/chromium
INFO:__main__:Getting metadata for https://github.com/chromium/chromium
 27%|██▋       | 64/235 [01:59<03:32,  1.24s/it]INFO:__main__:Requesting https://github.com/mozilla/gecko-dev
INFO:__main__:Getting metadata for https://github.com/mozilla/gecko-dev
 28%|██▊       | 65/235 [02:00<03:29,  1.23s/it]INFO:__main__:Requesting https://developer.microsoft.com/en-us/windows/pwa
INFO:__main__:Getting metadata for https://developer.microsoft.com/en-us/windows/pwa
 28%|██▊       | 66/235 [02:03<04:23,  1.56s/it]INFO:__main__:Requesting https://github.com/nodejs/node-chakracore
INFO:__main__:Getting metadata for https://github.com/nodejs/node-chakracore
 29%|██▊       | 67/235 [02:04<03:57,  1.41s/it]INFO:__main__:Requesting https://github.com/Microsoft/ChakraCore/issues/5865
INFO:__main__:Getting metadata for https://github.com/Microsoft/ChakraCore/issues/5865
 29%|██▉       | 68/235 [02:07<05:41,  2.05s/it]INFO:__main__:Requesting https://www.cnet.com/news/google-firefox-search-deal-gives-mozilla-more-money-to-push-privacy/
INFO:__main__:Getting metadata for https://www.cnet.com/news/google-firefox-search-deal-gives-mozilla-more-money-to-push-privacy/
 29%|██▉       | 69/235 [02:09<05:41,  2.06s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=85601
 30%|██▉       | 70/235 [02:10<04:09,  1.51s/it]INFO:__main__:Requesting https://imgur.com/a/eAOCL3J
INFO:__main__:Getting metadata for https://imgur.com/a/eAOCL3J
ERROR:__main__:Could not get metadata for https://imgur.com/a/eAOCL3J
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 30%|███       | 71/235 [02:10<03:05,  1.13s/it]INFO:__main__:Requesting https://www.adsoftheworld.com/media/film/google_chrome_speed_tests
INFO:__main__:Getting metadata for https://www.adsoftheworld.com/media/film/google_chrome_speed_tests
ERROR:__main__:Could not get metadata for https://www.adsoftheworld.com/media/film/google_chrome_speed_tests
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 31%|███       | 72/235 [02:11<03:22,  1.24s/it]INFO:__main__:Requesting https://support.mozilla.org/en-US/kb/containers
INFO:__main__:Getting metadata for https://support.mozilla.org/en-US/kb/containers
 31%|███       | 73/235 [02:13<04:02,  1.50s/it]INFO:__main__:Requesting https://arstechnica.com/information-technology/2013/04/google-going-its-own-way-forking-webkit-rendering-engine/
INFO:__main__:Getting metadata for https://arstechnica.com/information-technology/2013/04/google-going-its-own-way-forking-webkit-rendering-engine/
 31%|███▏      | 74/235 [02:14<03:04,  1.14s/it]INFO:__main__:Requesting https://blog.chromium.org/2013/04/blink-rendering-engine-for-chromium.html
INFO:__main__:Getting metadata for https://blog.chromium.org/2013/04/blink-rendering-engine-for-chromium.html
 32%|███▏      | 75/235 [02:14<02:26,  1.09it/s]INFO:__main__:Requesting https://www.qutebrowser.org
INFO:__main__:Getting metadata for https://www.qutebrowser.org
 32%|███▏      | 76/235 [02:17<04:02,  1.53s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Chromium_(web_browser)#2008
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Chromium_(web_browser)#2008
 33%|███▎      | 77/235 [02:19<04:31,  1.72s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
 33%|███▎      | 78/235 [02:20<04:04,  1.56s/it]INFO:__main__:Requesting https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave-
INFO:__main__:Getting metadata for https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave-
 34%|███▎      | 79/235 [02:21<03:23,  1.30s/it]INFO:__main__:Requesting https://colab.research.google.com/github/JuliaTPU/XLA.jl/blob/master/examples/3_LSTM_DistributedTraining.ipynb
INFO:__main__:Getting metadata for https://colab.research.google.com/github/JuliaTPU/XLA.jl/blob/master/examples/3_LSTM_DistributedTraining.ipynb
ERROR:__main__:Could not get metadata for https://colab.research.google.com/github/JuliaTPU/XLA.jl/blob/master/examples/3_LSTM_DistributedTraining.ipynb
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 34%|███▍      | 80/235 [02:21<02:30,  1.03it/s]INFO:__main__:Requesting https://github.com/staticfloat
INFO:__main__:Getting metadata for https://github.com/staticfloat
 34%|███▍      | 81/235 [02:24<03:29,  1.36s/it]INFO:__main__:Requesting http://karpathy.github.io/2015/05/21/rnn-effectiveness/
INFO:__main__:Getting metadata for http://karpathy.github.io/2015/05/21/rnn-effectiveness/
 35%|███▍      | 82/235 [02:24<02:55,  1.15s/it]INFO:__main__:Requesting https://arxiv.org/abs/1810.09868
INFO:__main__:Getting metadata for https://arxiv.org/abs/1810.09868
 35%|███▌      | 83/235 [02:26<03:08,  1.24s/it]INFO:__main__:Requesting https://github.com/JuliaGPU/CUDAnative.jl
INFO:__main__:Getting metadata for https://github.com/JuliaGPU/CUDAnative.jl
 36%|███▌      | 84/235 [02:27<02:55,  1.16s/it]INFO:__main__:Requesting https://medium.com/@mapmeld/esperanto-nlp-part-3-correcting-grammar-6d34f93bded1
INFO:__main__:Getting metadata for https://medium.com/@mapmeld/esperanto-nlp-part-3-correcting-grammar-6d34f93bded1
 36%|███▌      | 85/235 [02:27<02:25,  1.03it/s]INFO:__main__:Requesting http://gpu.rocks
INFO:__main__:Getting metadata for http://gpu.rocks
ERROR:__main__:Could not get metadata for http://gpu.rocks
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 37%|███▋      | 86/235 [02:27<01:52,  1.32it/s]INFO:__main__:Requesting https://github.com/gpujs/gpu.js/blob/develop/src/backend/web-gl2/fragment-shader.js#L40
INFO:__main__:Getting metadata for https://github.com/gpujs/gpu.js/blob/develop/src/backend/web-gl2/fragment-shader.js#L40
 37%|███▋      | 87/235 [02:28<02:00,  1.23it/s]INFO:__main__:Requesting http://raytracer.crypt.sg/
INFO:__main__:Getting metadata for http://raytracer.crypt.sg
ERROR:__main__:Could not get metadata for http://raytracer.crypt.sg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 37%|███▋      | 88/235 [02:29<01:54,  1.29it/s]INFO:__main__:Requesting https://turdnagel.com/cells/
INFO:__main__:Getting metadata for https://turdnagel.com/cells/
ERROR:__main__:Could not get metadata for https://turdnagel.com/cells/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 38%|███▊      | 89/235 [02:30<01:51,  1.31it/s]INFO:__main__:Requesting https://www.zdnet.com/article/new-browser-attack-lets-hackers-run-bad-code-even-after-users-leave-a-web-page/
INFO:__main__:Getting metadata for https://www.zdnet.com/article/new-browser-attack-lets-hackers-run-bad-code-even-after-users-leave-a-web-page/
 38%|███▊      | 90/235 [02:30<01:38,  1.47it/s]INFO:__main__:Requesting https://github.com/numtel/nano-webgl-pow
INFO:__main__:Getting metadata for https://github.com/numtel/nano-webgl-pow
 39%|███▊      | 91/235 [02:31<01:44,  1.38it/s]INFO:__main__:Requesting https://js.tensorflow.org/
INFO:__main__:Getting metadata for https://js.tensorflow.org
 39%|███▉      | 92/235 [02:31<01:19,  1.81it/s]INFO:__main__:Requesting https://sysdig.com/blog/the-art-of-writing-ebpf-programs-a-primer/
INFO:__main__:Getting metadata for https://sysdig.com/blog/the-art-of-writing-ebpf-programs-a-primer/
 40%|███▉      | 93/235 [02:31<01:00,  2.34it/s]INFO:__main__:Requesting https://lwn.net/Articles/740157/
INFO:__main__:Getting metadata for https://lwn.net/Articles/740157/
 40%|████      | 94/235 [02:32<01:15,  1.86it/s]INFO:__main__:Requesting https://www.citylab.com/transportation/2019/02/france-high-speed-rail-new-trains-tgv-2020-sncf-cost-ticket/583624/
INFO:__main__:Getting metadata for https://www.citylab.com/transportation/2019/02/france-high-speed-rail-new-trains-tgv-2020-sncf-cost-ticket/583624/
 40%|████      | 95/235 [02:32<01:02,  2.23it/s]INFO:__main__:Requesting https://en.wiktionary.org/wiki/inou%C3%AF
INFO:__main__:Getting metadata for https://en.wiktionary.org/wiki/inou%C3%AF
 41%|████      | 96/235 [02:33<01:15,  1.84it/s]INFO:__main__:Requesting https://www.thelocal.fr/20180727/fire-blocks-montparnasse-train-station-in-paris-at-height-of-holiday-exodus
INFO:__main__:Getting metadata for https://www.thelocal.fr/20180727/fire-blocks-montparnasse-train-station-in-paris-at-height-of-holiday-exodus
 41%|████▏     | 97/235 [02:35<01:54,  1.21it/s]INFO:__main__:Requesting https://www.cnbc.com/2019/02/26/hyperloop-firm-unveils-first-images-of-its-new-test-track-in-toulouse.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2019/02/26/hyperloop-firm-unveils-first-images-of-its-new-test-track-in-toulouse.html
 42%|████▏     | 98/235 [02:35<01:37,  1.41it/s]INFO:__main__:Requesting http://ai.stanford.edu/blog/beyond_local_pattern_matching/
INFO:__main__:Getting metadata for http://ai.stanford.edu/blog/beyond_local_pattern_matching/
 42%|████▏     | 99/235 [02:36<01:27,  1.55it/s]INFO:__main__:Requesting https://www.gremlin.com/blog/introducing-gremlin-free/
INFO:__main__:Getting metadata for https://www.gremlin.com/blog/introducing-gremlin-free/
 43%|████▎     | 100/235 [02:37<01:45,  1.28it/s]INFO:__main__:Requesting https://www.gremlin.com/docs/infrastructure-layer/installation/
INFO:__main__:Getting metadata for https://www.gremlin.com/docs/infrastructure-layer/installation/
 43%|████▎     | 101/235 [02:38<02:00,  1.11it/s]INFO:__main__:Requesting https://www.gremlin.com/docs/security/overview/#linux-capabilities
INFO:__main__:Getting metadata for https://www.gremlin.com/docs/security/overview/#linux-capabilities
 43%|████▎     | 102/235 [02:39<02:07,  1.04it/s]INFO:__main__:Requesting https://www.rust-lang.org/production/users
INFO:__main__:Getting metadata for https://www.rust-lang.org/production/users
 44%|████▍     | 103/235 [02:39<01:43,  1.27it/s]INFO:__main__:Requesting https://www.gremlin.com/docs/application-layer/overview/
INFO:__main__:Getting metadata for https://www.gremlin.com/docs/application-layer/overview/
 44%|████▍     | 104/235 [02:41<01:56,  1.13it/s]INFO:__main__:Requesting https://www.gremlin.com/slack
INFO:__main__:Getting metadata for https://slofile.com/slack/chaosengineering
 45%|████▍     | 105/235 [02:41<01:44,  1.25it/s]INFO:__main__:Requesting https://gremlin.com/security
INFO:__main__:Getting metadata for https://www.gremlin.com/security/
 45%|████▌     | 106/235 [02:43<02:26,  1.13s/it]INFO:__main__:Requesting https://www.gremlin.com/chaos-monkey/chaos-monkey-alternatives/
INFO:__main__:Getting metadata for https://www.gremlin.com/chaos-monkey/chaos-monkey-alternatives/
 46%|████▌     | 107/235 [02:44<02:32,  1.19s/it]INFO:__main__:Requesting https://github.com/Netflix/SimianArmy
INFO:__main__:Getting metadata for https://github.com/Netflix/SimianArmy
 46%|████▌     | 108/235 [02:45<02:21,  1.11s/it]INFO:__main__:Requesting http://www.apache.org/foundation/marks/faq/
INFO:__main__:Getting metadata for http://www.apache.org/foundation/marks/faq/
 46%|████▋     | 109/235 [02:47<02:35,  1.23s/it]INFO:__main__:Requesting https://www.cbsnews.com/pictures/worlds-15-ugliest-cars/7/
INFO:__main__:Getting metadata for https://www.cbsnews.com/pictures/worlds-15-ugliest-cars/7/
 47%|████▋     | 110/235 [02:48<02:37,  1.26s/it]INFO:__main__:Requesting https://trademarks.justia.com/871/94/gremlin-87194877.html
INFO:__main__:Getting metadata for https://trademarks.justia.com/871/94/gremlin-87194877.html
 47%|████▋     | 111/235 [02:48<02:00,  1.03it/s]INFO:__main__:Requesting https://cacm.acm.org/magazines/2019/3/234913-lost-in-math/fulltext
INFO:__main__:Getting metadata for https://cacm.acm.org/magazines/2019/3/234913-lost-in-math/fulltext
 48%|████▊     | 112/235 [02:53<04:30,  2.20s/it]INFO:__main__:Requesting http://www.cs.utexas.edu/users/EWD/transcriptions/EWD12xx/EWD1243a.html
INFO:__main__:Getting metadata for http://www.cs.utexas.edu/users/EWD/transcriptions/EWD12xx/EWD1243a.html
 48%|████▊     | 113/235 [02:54<03:20,  1.64s/it]INFO:__main__:Requesting http://learnyouahaskell.com/
INFO:__main__:Getting metadata for http://learnyouahaskell.com
ERROR:__main__:Could not get metadata for http://learnyouahaskell.com
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 49%|████▊     | 114/235 [02:55<02:46,  1.37s/it]INFO:__main__:Requesting https://github.com/data61/fp-course
INFO:__main__:Getting metadata for https://github.com/data61/fp-course
 49%|████▉     | 115/235 [02:56<02:38,  1.32s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=O3EjNRgypXg
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=O3EjNRgypXg
 49%|████▉     | 116/235 [02:57<02:24,  1.21s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=FGtsqEwANWY&feature=youtu.be&list=PLgKuh-lKre12S9FgcsgxlaoEkgNZuqeNc
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=FGtsqEwANWY&feature=youtu.be&list=PLgKuh-lKre12S9FgcsgxlaoEkgNZuqeNc
 50%|████▉     | 117/235 [02:58<02:09,  1.10s/it]INFO:__main__:Requesting https://deepai.org/machine-learning-glossary-and-terms/manifold-hypothesis
INFO:__main__:Getting metadata for https://deepai.org/machine-learning-glossary-and-terms/manifold-hypothesis
 50%|█████     | 118/235 [02:58<01:48,  1.08it/s]INFO:__main__:Requesting http://backreaction.blogspot.com/2019/02/a-philosopher-of-science-reviews-lost.html
INFO:__main__:Getting metadata for http://backreaction.blogspot.com/2019/02/a-philosopher-of-science-reviews-lost.html
 51%|█████     | 119/235 [02:58<01:25,  1.36it/s]INFO:__main__:Requesting https://github.com/oilshell/oil/blob/master/bin/osh_parse.py
INFO:__main__:Getting metadata for https://github.com/oilshell/oil/blob/master/bin/osh_parse.py
 51%|█████     | 120/235 [02:59<01:30,  1.27it/s]INFO:__main__:Requesting https://github.com/oilshell/oil/issues/171
INFO:__main__:Getting metadata for https://github.com/oilshell/oil/issues/171
 51%|█████▏    | 121/235 [03:01<01:50,  1.03it/s]INFO:__main__:Requesting http://www.oilshell.org/blog/2017/11/10.html
INFO:__main__:Getting metadata for http://www.oilshell.org/blog/2017/11/10.html
ERROR:__main__:Could not get metadata for http://www.oilshell.org/blog/2017/11/10.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 52%|█████▏    | 122/235 [03:01<01:33,  1.20it/s]INFO:__main__:Requesting https://labelbox.com/buy-vs-build
INFO:__main__:Getting metadata for https://labelbox.com/buy-vs-build
 52%|█████▏    | 123/235 [03:02<01:39,  1.12it/s]INFO:__main__:Requesting https://www.rafflecopter.com/
INFO:__main__:Getting metadata for https://www.rafflecopter.com
 53%|█████▎    | 124/235 [03:02<01:17,  1.43it/s]INFO:__main__:Requesting https://docs.fuzzbuzz.io/
INFO:__main__:Getting metadata for https://docs.fuzzbuzz.io
 53%|█████▎    | 125/235 [03:04<01:29,  1.23it/s]INFO:__main__:Requesting https://github.com/sslab-gatech/perf-fuzz/
INFO:__main__:Getting metadata for https://github.com/sslab-gatech/perf-fuzz/
 54%|█████▎    | 126/235 [03:05<01:35,  1.14it/s]INFO:__main__:Requesting https://www.microsoft.com/security/blog/2013/06/13/exploitable-crash-analyzer-version-1-6/
INFO:__main__:Getting metadata for https://www.microsoft.com/security/blog/2013/06/13/exploitable-crash-analyzer-version-1-6/
 54%|█████▍    | 127/235 [03:06<01:50,  1.02s/it]INFO:__main__:Requesting https://github.com/jfoote/exploitable
INFO:__main__:Getting metadata for https://github.com/jfoote/exploitable
 54%|█████▍    | 128/235 [03:07<01:44,  1.02it/s]INFO:__main__:Requesting https://gitlab.com/akihe/radamsa
INFO:__main__:Getting metadata for https://gitlab.com/akihe/radamsa
 55%|█████▍    | 129/235 [03:08<01:45,  1.00it/s]INFO:__main__:Requesting https://github.com/cretz/javan-warty-pig
INFO:__main__:Getting metadata for https://github.com/cretz/javan-warty-pig
 55%|█████▌    | 130/235 [03:09<01:39,  1.06it/s]INFO:__main__:Requesting https://github.com/rust-fuzz/afl.rs
INFO:__main__:Getting metadata for https://github.com/rust-fuzz/afl.rs
 56%|█████▌    | 131/235 [03:09<01:33,  1.11it/s]INFO:__main__:Requesting https://docs.ruby-lang.org/en/2.5.0/CSV.html
INFO:__main__:Getting metadata for https://docs.ruby-lang.org/en/2.5.0/CSV.html
 56%|█████▌    | 132/235 [03:11<02:04,  1.21s/it]INFO:__main__:Requesting https://github.com/gettalong/hexapdf
INFO:__main__:Getting metadata for https://github.com/gettalong/hexapdf
 57%|█████▋    | 133/235 [03:12<01:50,  1.08s/it]INFO:__main__:Requesting https://github.com/trailofbits/deepstate
INFO:__main__:Getting metadata for https://github.com/trailofbits/deepstate
 57%|█████▋    | 134/235 [03:13<01:45,  1.05s/it]INFO:__main__:Requesting https://hypothesis.readthedocs.io/en/latest/
INFO:__main__:Getting metadata for https://hypothesis.readthedocs.io/en/latest/
 57%|█████▋    | 135/235 [03:14<01:40,  1.01s/it]INFO:__main__:Requesting https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition
INFO:__main__:Getting metadata for https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition
 58%|█████▊    | 136/235 [03:15<01:37,  1.01it/s]INFO:__main__:Requesting http://www.tovala.com/careers
INFO:__main__:Getting metadata for https://www.tovala.com/careers
 58%|█████▊    | 137/235 [03:16<01:23,  1.18it/s]INFO:__main__:Requesting https://github.com/antontarasenko/hacker-news-groups
INFO:__main__:Getting metadata for https://github.com/antontarasenko/hacker-news-groups
 59%|█████▊    | 138/235 [03:16<01:25,  1.14it/s]INFO:__main__:Requesting https://gettogether.community/
INFO:__main__:Getting metadata for https://gettogether.community
 59%|█████▉    | 139/235 [03:19<01:59,  1.25s/it]INFO:__main__:Requesting https://github.com/GetTogetherComm/GetTogether
INFO:__main__:Getting metadata for https://github.com/GetTogetherComm/GetTogether
 60%|█████▉    | 140/235 [03:19<01:45,  1.11s/it]INFO:__main__:Requesting https://hackernoon.com/stop-using-io-domain-names-for-production-traffic-b6aa17eeac20
INFO:__main__:Getting metadata for https://hackernoon.com/stop-using-io-domain-names-for-production-traffic-b6aa17eeac20?gi=21d0ecd1e67c
 60%|██████    | 141/235 [03:22<02:17,  1.46s/it]INFO:__main__:Requesting https://spectrum.chat/canada
INFO:__main__:Getting metadata for https://spectrum.chat/canada
 60%|██████    | 142/235 [03:24<02:30,  1.62s/it]INFO:__main__:Requesting https://www.2600.com/meetings/mtg.html
INFO:__main__:Getting metadata for https://www.2600.com/meetings/mtg.html
ERROR:__main__:Could not get metadata for https://www.2600.com/meetings/mtg.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 61%|██████    | 143/235 [03:25<02:17,  1.49s/it]INFO:__main__:Requesting https://lwn.net/SubscriberLink/780710/ece0f8b930151422/
INFO:__main__:Getting metadata for https://lwn.net/SubscriberLink/780710/ece0f8b930151422/
 61%|██████▏   | 144/235 [03:25<01:50,  1.22s/it]INFO:__main__:Requesting https://www.newyorker.com/magazine/2019/03/04/how-much-a-dementia-patient-needs-to-know
INFO:__main__:Getting metadata for https://www.newyorker.com/magazine/2019/03/04/how-much-a-dementia-patient-needs-to-know
 62%|██████▏   | 145/235 [03:26<01:26,  1.04it/s]INFO:__main__:Requesting https://psmag.com/economics/protestant-worth-ethic-real-65544
INFO:__main__:Getting metadata for https://psmag.com/economics/protestant-worth-ethic-real-65544
 62%|██████▏   | 146/235 [03:26<01:12,  1.22it/s]INFO:__main__:Requesting https://hbr.org/daily-stat/2013/08/there-really-is-such-a-thing-a.html
INFO:__main__:Getting metadata for https://hbr.org/daily-stat/2013/08/there-really-is-such-a-thing-a.html
 63%|██████▎   | 147/235 [03:27<01:04,  1.37it/s]INFO:__main__:Requesting https://gizmodo.com/inside-an-amazing-village-designed-just-for-people-with-1526062373
INFO:__main__:Getting metadata for https://gizmodo.com/inside-an-amazing-village-designed-just-for-people-with-1526062373
 63%|██████▎   | 148/235 [03:27<00:52,  1.66it/s]INFO:__main__:Requesting https://www.newyorker.com/magazine/2018/10/08/the-comforting-fictions-of-dementia-care
INFO:__main__:Getting metadata for https://www.newyorker.com/magazine/2018/10/08/the-comforting-fictions-of-dementia-care
 63%|██████▎   | 149/235 [03:27<00:43,  1.97it/s]INFO:__main__:Requesting https://www.secbsd.org/
INFO:__main__:Getting metadata for https://www.secbsd.org
ERROR:__main__:Could not get metadata for https://www.secbsd.org
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 64%|██████▍   | 150/235 [03:31<01:52,  1.33s/it]INFO:__main__:Requesting https://webcache.googleusercontent.com/search?q=cache:E2OiV-7ZhGIJ:https://secbsd.org/dark-intelligence-team.html
INFO:__main__:Getting metadata for https://webcache.googleusercontent.com/search?q=cache:E2OiV-7ZhGIJ:https://secbsd.org/dark-intelligence-team.html
 64%|██████▍   | 151/235 [03:33<02:20,  1.67s/it]INFO:__main__:Requesting https://www.secbsd.org/dark-intelligence-team.html
INFO:__main__:Getting metadata for https://www.secbsd.org/dark-intelligence-team.html
ERROR:__main__:Could not get metadata for https://www.secbsd.org/dark-intelligence-team.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 65%|██████▍   | 152/235 [03:36<02:49,  2.04s/it]INFO:__main__:Requesting https://www.allacronyms.com/TCB
INFO:__main__:Getting metadata for https://www.allacronyms.com/TCB
 65%|██████▌   | 153/235 [03:36<02:06,  1.54s/it]INFO:__main__:Requesting https://www.nature.com/articles/s42254-018-0005-3
INFO:__main__:Getting metadata for https://www.nature.com/articles/s42254-018-0005-3
 66%|██████▌   | 154/235 [03:39<02:31,  1.87s/it]INFO:__main__:Requesting https://longform.org/posts/the-mastermind
INFO:__main__:Getting metadata for https://longform.org/posts/the-mastermind
 66%|██████▌   | 155/235 [03:39<01:55,  1.44s/it]INFO:__main__:Requesting https://www.gimletmedia.com/reply-all/the-founder#episode-player
INFO:__main__:Getting metadata for https://www.gimletmedia.com/reply-all/the-founder#episode-player
ERROR:__main__:Could not get metadata for https://www.gimletmedia.com/reply-all/the-founder#episode-player
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 66%|██████▋   | 156/235 [03:40<01:39,  1.26s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=MTeonvkHKDk
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=MTeonvkHKDk
 67%|██████▋   | 157/235 [03:41<01:29,  1.15s/it]INFO:__main__:Requesting https://www.vulture.com/amp/2019/02/michael-mann-and-elaine-shannon-talk-on-hunting-leroux.html
INFO:__main__:Getting metadata for https://www.vulture.com/amp/2019/02/michael-mann-and-elaine-shannon-talk-on-hunting-leroux.html
 67%|██████▋   | 158/235 [03:41<01:07,  1.14it/s]INFO:__main__:Requesting https://www.vox.com/future-perfect/2019/2/26/18241904/lake-erie-legal-rights-personhood-nature-environment-toledo-ohio
INFO:__main__:Getting metadata for https://www.vox.com/future-perfect/2019/2/26/18241904/lake-erie-legal-rights-personhood-nature-environment-toledo-ohio
 68%|██████▊   | 159/235 [03:42<00:51,  1.46it/s]INFO:__main__:Requesting https://www.wilderness.org/articles/blog/what-intact-forest-worth-1-trillion-case-greater-seattles-mt-baker-snoqualmie
INFO:__main__:Getting metadata for https://www.wilderness.org/articles/blog/what-intact-forest-worth-1-trillion-case-greater-seattles-mt-baker-snoqualmie
ERROR:__main__:Could not get metadata for https://www.wilderness.org/articles/blog/what-intact-forest-worth-1-trillion-case-greater-seattles-mt-baker-snoqualmie
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 68%|██████▊   | 160/235 [03:42<00:46,  1.61it/s]INFO:__main__:Requesting https://www.williamcronon.net/writing/Trouble_with_Wilderness_Main.html
 69%|██████▊   | 161/235 [03:42<00:38,  1.92it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Great_Lakes_Compact
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Great_Lakes_Compact
 69%|██████▉   | 162/235 [03:43<00:42,  1.71it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Great_Lakes%E2%80%93Saint_Lawrence_River_Basin_Sustainable_Water_Resources_Agreement
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Great_Lakes%E2%80%93Saint_Lawrence_River_Basin_Sustainable_Water_Resources_Agreement
 69%|██████▉   | 163/235 [03:44<00:42,  1.70it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Great_Lakes_Charter
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Great_Lakes_Charter
 70%|██████▉   | 164/235 [03:44<00:41,  1.71it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/International_Joint_Commission
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/International_Joint_Commission
 70%|███████   | 165/235 [03:45<00:44,  1.59it/s]INFO:__main__:Requesting http://www.glfc.org/index.php
INFO:__main__:Getting metadata for http://www.glfc.org/index.php
 71%|███████   | 166/235 [03:46<00:44,  1.54it/s]INFO:__main__:Requesting https://www.nationofchange.org/2019/02/04/the-white-earth-band-of-ojibwe-legally-recognized-the-rights-of-wild-rice-heres-why/
INFO:__main__:Getting metadata for https://www.nationofchange.org/2019/02/04/the-white-earth-band-of-ojibwe-legally-recognized-the-rights-of-wild-rice-heres-why/
 71%|███████   | 167/235 [03:47<01:03,  1.07it/s]INFO:__main__:Requesting https://bicycledutch.wordpress.com/2019/02/27/the-1979-delft-cycle-plan/
ERROR:__main__:Could not reach https://bicycledutch.wordpress.com/2019/02/27/the-1979-delft-cycle-plan/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 71%|███████▏  | 168/235 [03:47<00:46,  1.44it/s]INFO:__main__:Requesting http://www.calgary.ca/Transportation/TP/Pages/Cycling/Cycling-Route-Improvements/Downtown-cycle-track-pilot-project.aspx?redirect=/cycletracks
INFO:__main__:Getting metadata for http://www.calgary.ca/Transportation/TP/Pages/Cycling/Cycling-Route-Improvements/Downtown-cycle-track-pilot-project.aspx?redirect=/cycletracks
 72%|███████▏  | 169/235 [03:50<01:27,  1.33s/it]INFO:__main__:Requesting https://www.theguardian.com/cities/2015/jan/28/seville-cycling-capital-southern-europe-bike-lanes
INFO:__main__:Getting metadata for https://www.theguardian.com/cities/2015/jan/28/seville-cycling-capital-southern-europe-bike-lanes
 72%|███████▏  | 170/235 [03:51<01:13,  1.14s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Desire_path
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Desire_path
 73%|███████▎  | 171/235 [03:52<01:06,  1.04s/it]INFO:__main__:Requesting https://www.youtube.com/user/markenlei
INFO:__main__:Getting metadata for https://www.youtube.com/user/markenlei
 73%|███████▎  | 172/235 [03:55<01:39,  1.57s/it]INFO:__main__:Requesting https://bicycledutch.wordpress.com
ERROR:__main__:Could not reach https://bicycledutch.wordpress.com
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 74%|███████▎  | 173/235 [03:55<01:10,  1.14s/it]INFO:__main__:Requesting https://bicycledutch.wordpress.com/index-by-theme/
ERROR:__main__:Could not reach https://bicycledutch.wordpress.com/index-by-theme/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 74%|███████▍  | 174/235 [03:55<00:50,  1.20it/s]INFO:__main__:Requesting https://techcrunch.com/2019/02/27/dow-jones-watchlist-leak/
ERROR:__main__:Could not reach https://techcrunch.com/2019/02/27/dow-jones-watchlist-leak/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 74%|███████▍  | 175/235 [03:55<00:37,  1.61it/s]INFO:__main__:Requesting https://outline.com/DEfmHq
INFO:__main__:Getting metadata for https://outline.com/DEfmHq
 75%|███████▍  | 176/235 [03:56<00:47,  1.24it/s]INFO:__main__:Requesting http://lexindicium.com/2018/03/19/data-mining-and-gdpr-compliance/
INFO:__main__:Getting metadata for http://lexindicium.com/2018/03/19/data-mining-and-gdpr-compliance/
 75%|███████▌  | 177/235 [03:57<00:53,  1.07it/s]INFO:__main__:Requesting https://ec.europa.eu/info/law/law-topic/data-protection/reform/rights-citizens/my-rights/what-are-my-rights_en
INFO:__main__:Getting metadata for https://ec.europa.eu/info/law/law-topic/data-protection/reform/rights-citizens/my-rights/what-are-my-rights_en
ERROR:__main__:Could not get metadata for https://ec.europa.eu/info/law/law-topic/data-protection/reform/rights-citizens/my-rights/what-are-my-rights_en
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 76%|███████▌  | 178/235 [04:00<01:19,  1.40s/it]INFO:__main__:Requesting https://0day.work/performance-of-iodine-over-dns-over-https/
INFO:__main__:Getting metadata for https://0day.work/performance-of-iodine-over-dns-over-https/
 76%|███████▌  | 179/235 [04:01<01:20,  1.43s/it]INFO:__main__:Requesting https://paleotronic.com/2019/02/27/arcade-rats-on-the-moon/
INFO:__main__:Getting metadata for https://paleotronic.com/2019/02/27/arcade-rats-on-the-moon/
 77%|███████▋  | 180/235 [04:02<01:10,  1.29s/it]INFO:__main__:Requesting https://www.eetimes.com/document.asp?doc_id=1334373
ERROR:__main__:Could not reach https://www.eetimes.com/document.asp?doc_id=1334373
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.eetimes.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.eetimes.com', port=443): Read timed out. (read timeout=6)
 77%|███████▋  | 181/235 [04:08<02:27,  2.73s/it]INFO:__main__:Requesting http://www.ti.com/product/LMK05318
ERROR:__main__:Could not reach http://www.ti.com/product/LMK05318
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.ti.com', port=80): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.ti.com', port=80): Read timed out. (read timeout=6)
 77%|███████▋  | 182/235 [04:15<03:20,  3.78s/it]INFO:__main__:Requesting https://training.ti.com/tis-bulk-acoustic-wave-clocking-technology-0
INFO:__main__:Getting metadata for https://training.ti.com/tis-bulk-acoustic-wave-clocking-technology-0
ERROR:__main__:Could not get metadata for https://training.ti.com/tis-bulk-acoustic-wave-clocking-technology-0
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 78%|███████▊  | 183/235 [04:16<02:41,  3.11s/it]INFO:__main__:Requesting https://www.nytimes.com/2019/02/26/dining/homemade-yogurt-starter-south-asia.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/02/26/dining/homemade-yogurt-starter-south-asia.html
 78%|███████▊  | 184/235 [04:17<01:55,  2.26s/it]INFO:__main__:Requesting https://qz.com/1176962/map-how-the-word-tea-spread-over-land-and-sea-to-conquer-the-world/
INFO:__main__:Getting metadata for https://qz.com/1176962/map-how-the-word-tea-spread-over-land-and-sea-to-conquer-the-world/
 79%|███████▊  | 185/235 [04:17<01:21,  1.64s/it]INFO:__main__:Requesting https://www.languagesoftheworld.info/etymology/say-cheese.html
INFO:__main__:Getting metadata for https://www.languagesoftheworld.info/etymology/say-cheese.html
 79%|███████▉  | 186/235 [04:18<01:21,  1.66s/it]INFO:__main__:Requesting https://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/servepdf.php?page=502
INFO:__main__:Getting metadata for https://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/servepdf.php?page=502
ERROR:__main__:Could not get metadata for https://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/servepdf.php?page=502
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 80%|███████▉  | 187/235 [04:21<01:33,  1.94s/it]INFO:__main__:Requesting https://www.bobsredmill.com/sourdough-starter.html
INFO:__main__:Getting metadata for https://www.bobsredmill.com/sourdough-starter.html
 80%|████████  | 188/235 [04:23<01:36,  2.05s/it]INFO:__main__:Requesting https://cooking.nytimes.com/recipes/11376-no-knead-bread
INFO:__main__:Getting metadata for https://cooking.nytimes.com/recipes/11376-no-knead-bread
 80%|████████  | 189/235 [04:24<01:08,  1.50s/it]INFO:__main__:Requesting https://www.womenshealthmag.com/nl/voeding/feiten-fabels/a23733982/yoghurt-verschillende-soorten-gezondst/
INFO:__main__:Getting metadata for https://www.womenshealthmag.com/nl/voeding/feiten-fabels/a23733982/yoghurt-verschillende-soorten-gezondst/
 81%|████████  | 190/235 [04:25<01:00,  1.34s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4166373/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4166373/
 81%|████████▏ | 191/235 [04:26<01:05,  1.49s/it]INFO:__main__:Requesting https://www.zdnet.com/article/windows-10-new-study-shows-home-edition-users-are-baffled-by-updates/
INFO:__main__:Getting metadata for https://www.zdnet.com/article/windows-10-new-study-shows-home-edition-users-are-baffled-by-updates/
 82%|████████▏ | 192/235 [04:27<00:53,  1.25s/it]INFO:__main__:Requesting https://news.ycombinator.com/reply?id=19265107&goto=item%3Fid%3D19264154%2319265107
INFO:__main__:Getting metadata for https://news.ycombinator.com/reply?id=19265107&goto=item%3Fid%3D19264154%2319265107
ERROR:__main__:Could not get metadata for https://news.ycombinator.com/reply?id=19265107&goto=item%3Fid%3D19264154%2319265107
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 82%|████████▏ | 193/235 [04:28<00:52,  1.25s/it]INFO:__main__:Requesting https://www.ubuntu.com/livepatch
INFO:__main__:Getting metadata for https://www.ubuntu.com/livepatch
 83%|████████▎ | 194/235 [04:32<01:16,  1.86s/it]INFO:__main__:Requesting https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/LTSC-What-is-it-and-when-should-it-be-used/ba-p/293181
INFO:__main__:Getting metadata for https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/LTSC-What-is-it-and-when-should-it-be-used/ba-p/293181
 83%|████████▎ | 195/235 [04:34<01:17,  1.93s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Kexec#See%20Also
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Kexec#See%20Also
 83%|████████▎ | 196/235 [04:35<01:03,  1.62s/it]INFO:__main__:Requesting https://www.windowslatest.com/2017/07/23/calculator-windows-10-updated-currency-converter/
INFO:__main__:Getting metadata for https://www.windowslatest.com/2017/07/23/calculator-windows-10-updated-currency-converter/
 84%|████████▍ | 197/235 [04:35<00:47,  1.24s/it]INFO:__main__:Requesting https://www.dell.com/learn/us/en/555/campaigns/xps-linux-laptop_us
INFO:__main__:Getting metadata for https://www.dell.com/learn/us/en/555/campaigns/xps-linux-laptop_us
 84%|████████▍ | 198/235 [04:36<00:43,  1.17s/it]INFO:__main__:Requesting https://linux-audit.com/livepatch-linux-kernel-updates-without-rebooting/
INFO:__main__:Getting metadata for https://linux-audit.com/livepatch-linux-kernel-updates-without-rebooting/
 85%|████████▍ | 199/235 [04:37<00:41,  1.16s/it]INFO:__main__:Requesting https://www.fool.com/investing/2017/06/29/how-microsoft-corporation-makes-most-of-its-money.aspx
INFO:__main__:Getting metadata for https://www.fool.com/investing/2017/06/29/how-microsoft-corporation-makes-most-of-its-money.aspx
 85%|████████▌ | 200/235 [04:38<00:39,  1.14s/it]INFO:__main__:Requesting https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant
INFO:__main__:Getting metadata for https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant
 86%|████████▌ | 201/235 [04:40<00:41,  1.21s/it]INFO:__main__:Requesting https://www.voidtools.com/
INFO:__main__:Getting metadata for https://www.voidtools.com
 86%|████████▌ | 202/235 [04:40<00:35,  1.08s/it]INFO:__main__:Requesting https://www.launchy.net/
INFO:__main__:Getting metadata for https://www.launchy.net
 86%|████████▋ | 203/235 [04:41<00:31,  1.00it/s]INFO:__main__:Requesting http://keypirinha.com/
INFO:__main__:Getting metadata for http://keypirinha.com
 87%|████████▋ | 204/235 [04:42<00:27,  1.14it/s]INFO:__main__:Requesting https://mouse-jiggler.en.uptodown.com/windows
INFO:__main__:Getting metadata for https://mouse-jiggler.en.uptodown.com/windows
 87%|████████▋ | 205/235 [04:42<00:23,  1.28it/s]INFO:__main__:Requesting https://www.udse.de/en/windows-10-reboot-blocker
INFO:__main__:Getting metadata for https://www.udse.de/en/windows-10-reboot-blocker
 88%|████████▊ | 206/235 [04:47<01:00,  2.08s/it]INFO:__main__:Requesting https://www.windowscentral.com/how-prevent-windows-10-rebooting-after-installing-updates
INFO:__main__:Getting metadata for https://www.windowscentral.com/how-prevent-windows-10-rebooting-after-installing-updates
 88%|████████▊ | 207/235 [04:48<00:42,  1.52s/it]INFO:__main__:Requesting https://github.com/ValveSoftware/Proton/
INFO:__main__:Getting metadata for https://github.com/ValveSoftware/Proton/
 89%|████████▊ | 208/235 [04:49<00:37,  1.39s/it]INFO:__main__:Requesting https://forums.docker.com/t/running-docker-and-virtualbox-on-the-same-machine/23578/7
INFO:__main__:Getting metadata for https://forums.docker.com/t/running-docker-and-virtualbox-on-the-same-machine/23578/7
 89%|████████▉ | 209/235 [04:49<00:30,  1.17s/it]INFO:__main__:Requesting https://forums.docker.com/t/running-docker-and-virtualbox-on..
 89%|████████▉ | 210/235 [04:50<00:22,  1.11it/s]INFO:__main__:Requesting https://getaether.net
INFO:__main__:Getting metadata for https://getaether.net
ERROR:__main__:Could not get metadata for https://getaether.net
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 90%|████████▉ | 211/235 [04:51<00:22,  1.06it/s]INFO:__main__:Requesting https://answers.microsoft.com/en-us/windows/forum/windows_10-update/windows-10-1809-update-deleted-all-files-from/ff608374-2686-4a08-a4c2-caa4caa6d4e1?auth=1
INFO:__main__:Getting metadata for https://answers.microsoft.com/en-us/windows/forum/windows_10-update/windows-10-1809-update-deleted-all-files-from/ff608374-2686-4a08-a4c2-caa4caa6d4e1?auth=1
 90%|█████████ | 212/235 [04:52<00:24,  1.08s/it]INFO:__main__:Requesting https://arstechnica.com/information-technology/2013/12/exponential-algorithm-making-windows-xp-miserable-could-be-fixed/
INFO:__main__:Getting metadata for https://arstechnica.com/information-technology/2013/12/exponential-algorithm-making-windows-xp-miserable-could-be-fixed/
 91%|█████████ | 213/235 [04:52<00:18,  1.20it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Focus_stealing
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Focus_stealing
 91%|█████████ | 214/235 [04:53<00:16,  1.31it/s]INFO:__main__:Requesting https://support.microsoft.com/en-us/help/4464619
INFO:__main__:Getting metadata for https://support.microsoft.com/en-us/help/4464619/windows-10-update-history
 91%|█████████▏| 215/235 [04:54<00:18,  1.05it/s]INFO:__main__:Requesting https://www.computerworld.com/article/3250464/faq-windows-10-ltsb-explained.html
INFO:__main__:Getting metadata for https://www.computerworld.com/article/3250464/faq-windows-10-ltsb-explained.html
 92%|█████████▏| 216/235 [04:55<00:14,  1.34it/s]INFO:__main__:Requesting https://support.microsoft.com/en-us/help/4028458/windows-metered-connections-in-windows-10
INFO:__main__:Getting metadata for https://support.microsoft.com/en-us/help/4028458/windows-metered-connections-in-windows-10
 92%|█████████▏| 217/235 [04:56<00:17,  1.02it/s]INFO:__main__:Requesting https://www.nature.com/articles/d41586-019-00577-0
INFO:__main__:Getting metadata for https://www.nature.com/articles/d41586-019-00577-0
 93%|█████████▎| 218/235 [04:58<00:22,  1.31s/it]INFO:__main__:Requesting https://physicsfm-frontiers.blogspot.com
INFO:__main__:Getting metadata for https://physicsfm-frontiers.blogspot.com
ERROR:__main__:Could not get metadata for https://physicsfm-frontiers.blogspot.com
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 93%|█████████▎| 219/235 [04:58<00:16,  1.00s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=mtPgW1ebxmE&list=PLOpjORaUU74zmq6Pmo3O6dzhxFBtaGsdt
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=mtPgW1ebxmE&list=PLOpjORaUU74zmq6Pmo3O6dzhxFBtaGsdt
 94%|█████████▎| 220/235 [05:00<00:16,  1.08s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=uXyLaER23aU
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=uXyLaER23aU
 94%|█████████▍| 221/235 [05:01<00:14,  1.06s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=MToNKd6RQhk
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=MToNKd6RQhk
 94%|█████████▍| 222/235 [05:02<00:13,  1.03s/it]INFO:__main__:Requesting https://www.preposterousuniverse.com/podcast/
 95%|█████████▍| 223/235 [05:02<00:09,  1.23it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Semi-empirical_mass_formula
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Semi-empirical_mass_formula
 95%|█████████▌| 224/235 [05:04<00:11,  1.08s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Neutron
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Neutron
 96%|█████████▌| 225/235 [05:06<00:14,  1.41s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Neutron#Description
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Neutron#Description
 96%|█████████▌| 226/235 [05:08<00:14,  1.65s/it]INFO:__main__:Requesting https://commons.wikimedia.org/wiki/File:Beta_Negative_Decay.svg
INFO:__main__:Getting metadata for https://commons.wikimedia.org/wiki/File:Beta_Negative_Decay.svg
 97%|█████████▋| 227/235 [05:09<00:10,  1.37s/it]INFO:__main__:Requesting http://hyperphysics.phy-astr.gsu.edu/hbase/Nuclear/scatele.html#c1
INFO:__main__:Getting metadata for http://hyperphysics.phy-astr.gsu.edu/hbase/Nuclear/scatele.html#c1
 97%|█████████▋| 228/235 [05:09<00:07,  1.07s/it]INFO:__main__:Requesting http://www.clarifyscience.info/assets/2017-Atoms/assets0/wk/1406.2473-Ne.png
INFO:__main__:Getting metadata for http://www.clarifyscience.info/assets/2017-Atoms/assets0/wk/1406.2473-Ne.png
ERROR:__main__:Could not get metadata for http://www.clarifyscience.info/assets/2017-Atoms/assets0/wk/1406.2473-Ne.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 97%|█████████▋| 229/235 [05:11<00:06,  1.15s/it]INFO:__main__:Requesting https://arxiv.org/abs/1406.2473
INFO:__main__:Getting metadata for https://arxiv.org/abs/1406.2473
 98%|█████████▊| 230/235 [05:12<00:05,  1.15s/it]INFO:__main__:Requesting https://arxiv.org/abs/1802.02873
INFO:__main__:Getting metadata for https://arxiv.org/abs/1802.02873
 98%|█████████▊| 231/235 [05:13<00:04,  1.10s/it]INFO:__main__:Requesting http://www.clarifyscience.info/part/Atoms
INFO:__main__:Getting metadata for http://www.clarifyscience.info/part/Atoms
 99%|█████████▊| 232/235 [05:15<00:04,  1.52s/it]INFO:__main__:Requesting https://pubs.rsc.org/en/content/articlehtml/2013/cp/c3cp51500a
INFO:__main__:Getting metadata for https://pubs.rsc.org/en/content/articlehtml/2013/cp/c3cp51500a
ERROR:__main__:Could not get metadata for https://pubs.rsc.org/en/content/articlehtml/2013/cp/c3cp51500a
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 99%|█████████▉| 233/235 [05:17<00:03,  1.67s/it]INFO:__main__:Requesting https://www.quantamagazine.org/famous-experiment-dooms-pilot-wave-alternative-to-quantum-weirdness-20181011/
INFO:__main__:Getting metadata for https://www.quantamagazine.org/famous-experiment-dooms-pilot-wave-alternative-to-quantum-weirdness-20181011/
ERROR:__main__:Could not get metadata for https://www.quantamagazine.org/famous-experiment-dooms-pilot-wave-alternative-to-quantum-weirdness-20181011/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
100%|█████████▉| 234/235 [05:19<00:01,  1.65s/it]INFO:__main__:Requesting https://qr.ae/TUfBFN
INFO:__main__:Getting metadata for https://www.quora.com/Why-are-protons-and-neutrons-made-up-of-3-quarks-Why-is-3-the-magic-number/answer/Stephen-Selipsky?ch=10&share=feae6ace&srid=uy4X
100%|██████████| 235/235 [05:21<00:00,  1.72s/it]
