INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:01<00:47,  1.62s/it]  7%|▋         | 2/30 [00:01<00:33,  1.21s/it] 10%|█         | 3/30 [00:06<00:57,  2.12s/it] 13%|█▎        | 4/30 [00:06<00:41,  1.61s/it] 17%|█▋        | 5/30 [00:07<00:33,  1.35s/it] 20%|██        | 6/30 [00:07<00:23,  1.03it/s] 23%|██▎       | 7/30 [00:08<00:20,  1.12it/s] 27%|██▋       | 8/30 [00:09<00:21,  1.04it/s] 30%|███       | 9/30 [00:09<00:14,  1.41it/s] 33%|███▎      | 10/30 [00:10<00:18,  1.10it/s] 37%|███▋      | 11/30 [00:10<00:12,  1.49it/s] 40%|████      | 12/30 [00:11<00:10,  1.79it/s] 47%|████▋     | 14/30 [00:12<00:10,  1.51it/s] 50%|█████     | 15/30 [00:13<00:09,  1.56it/s] 53%|█████▎    | 16/30 [00:13<00:06,  2.01it/s] 60%|██████    | 18/30 [00:13<00:04,  2.71it/s] 63%|██████▎   | 19/30 [00:14<00:04,  2.64it/s] 67%|██████▋   | 20/30 [00:14<00:04,  2.08it/s] 73%|███████▎  | 22/30 [00:20<00:09,  1.18s/it] 77%|███████▋  | 23/30 [00:21<00:07,  1.11s/it] 80%|████████  | 24/30 [00:21<00:05,  1.19it/s] 83%|████████▎ | 25/30 [00:21<00:03,  1.58it/s] 87%|████████▋ | 26/30 [00:21<00:01,  2.10it/s] 90%|█████████ | 27/30 [00:22<00:01,  1.82it/s] 93%|█████████▎| 28/30 [00:22<00:00,  2.34it/s] 97%|█████████▋| 29/30 [00:23<00:00,  2.80it/s]100%|██████████| 30/30 [00:23<00:00,  1.30it/s]
  0%|          | 0/328 [00:00<?, ?it/s]INFO:__main__:Requesting https://www.universityofcalifornia.edu/press-room/uc-terminates-subscriptions-worlds-largest-scientific-publisher-push-open-access-publicly
INFO:__main__:Getting metadata for https://www.universityofcalifornia.edu/press-room/uc-terminates-subscriptions-worlds-largest-scientific-publisher-push-open-access-publicly
  0%|          | 1/328 [00:00<01:28,  3.68it/s]INFO:__main__:Requesting https://www.theguardian.com/science/2012/apr/24/harvard-university-journal-publishers-prices
INFO:__main__:Getting metadata for https://www.theguardian.com/science/2012/apr/24/harvard-university-journal-publishers-prices
  1%|          | 2/328 [00:01<02:17,  2.38it/s]INFO:__main__:Requesting https://www.projekt-deal.de/vertragskundigungen-elsevier-2018/
INFO:__main__:Getting metadata for https://www.projekt-deal.de/vertragskundigungen-elsevier-2018/
  1%|          | 3/328 [00:06<10:12,  1.88s/it]INFO:__main__:Requesting https://www.projekt-deal.de/
INFO:__main__:Getting metadata for https://www.projekt-deal.de
  1%|          | 4/328 [00:11<15:30,  2.87s/it]INFO:__main__:Requesting https://controller.berkeley.edu/home/uc-berkeley-financial-reports
INFO:__main__:Getting metadata for https://controller.berkeley.edu/home/uc-berkeley-financial-reports
  2%|▏         | 5/328 [00:12<12:48,  2.38s/it]INFO:__main__:Requesting https://www.quora.com/What-is-the-cost-for-a-university-subscription-to-the-entire-Elsevier-database-with-unlimited-views-and-downloads-for-an-academic-year
INFO:__main__:Getting metadata for https://www.quora.com/What-is-the-cost-for-a-university-subscription-to-the-entire-Elsevier-database-with-unlimited-views-and-downloads-for-an-academic-year
  2%|▏         | 6/328 [00:15<13:17,  2.48s/it]INFO:__main__:Requesting https://pages.github.berkeley.edu/OPA/our-berkeley/enroll-history.html
INFO:__main__:Getting metadata for https://pages.github.berkeley.edu/OPA/our-berkeley/enroll-history.html
ERROR:__main__:Could not get metadata for https://pages.github.berkeley.edu/OPA/our-berkeley/enroll-history.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  2%|▏         | 7/328 [00:16<10:58,  2.05s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=pgUA1tluVmE
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=pgUA1tluVmE
  2%|▏         | 8/328 [00:17<09:08,  1.71s/it]INFO:__main__:Requesting https://chorasimilarity.wordpress.com/2019/02/28/google-translate-helps-the-scholarly-poor/
ERROR:__main__:Could not reach https://chorasimilarity.wordpress.com/2019/02/28/google-translate-helps-the-scholarly-poor/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  3%|▎         | 9/328 [00:17<06:35,  1.24s/it]INFO:__main__:Requesting https://sci-hub.tw/donate
INFO:__main__:Getting metadata for https://sci-hub.tw/donate
  3%|▎         | 10/328 [00:24<15:58,  3.01s/it]INFO:__main__:Requesting https://www.topuniversities.com/student-info/student-finance/how-much-does-it-cost-study-us
INFO:__main__:Getting metadata for https://www.topuniversities.com/student-info/student-finance/how-much-does-it-cost-study-us
  3%|▎         | 11/328 [00:25<11:57,  2.26s/it]INFO:__main__:Requesting https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-private-nonprofit-four-year-institutions
INFO:__main__:Getting metadata for https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-private-nonprofit-four-year-institutions
  4%|▎         | 12/328 [00:25<09:33,  1.81s/it]INFO:__main__:Requesting https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-public-four-year-institution
INFO:__main__:Getting metadata for https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-public-four-year-institution
  4%|▍         | 13/328 [00:26<07:36,  1.45s/it]INFO:__main__:Requesting https://www.reddit.com/r/AskAnAmerican/comments/7qesj9/why_is_college_in_the_us_so_expensive/
INFO:__main__:Getting metadata for https://www.reddit.com/r/AskAnAmerican/comments/7qesj9/why_is_college_in_the_us_so_expensive/
  4%|▍         | 14/328 [00:27<06:31,  1.25s/it]INFO:__main__:Requesting https://trends.collegeboard.org/college-pricing
INFO:__main__:Getting metadata for https://trends.collegeboard.org/college-pricing
  5%|▍         | 15/328 [00:27<05:31,  1.06s/it]INFO:__main__:Requesting https://nces.ed.gov/programs/digest/d17/tables/dt17_334.30.asp
INFO:__main__:Getting metadata for https://nces.ed.gov/programs/digest/d17/tables/dt17_334.30.asp
  5%|▍         | 16/328 [00:31<09:17,  1.79s/it]INFO:__main__:Requesting https://nces.ed.gov/programs/digest/d17/tables/dt17_334.10.asp
INFO:__main__:Getting metadata for https://nces.ed.gov/programs/digest/d17/tables/dt17_334.10.asp
  5%|▌         | 17/328 [00:34<10:40,  2.06s/it]INFO:__main__:Requesting https://ucla.app.box.com/v/acct-pdf-AFR-16-17
INFO:__main__:Getting metadata for https://ucla.app.box.com/v/acct-pdf-AFR-16-17
ERROR:__main__:Could not get metadata for https://ucla.app.box.com/v/acct-pdf-AFR-16-17
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  5%|▌         | 18/328 [00:41<18:39,  3.61s/it]INFO:__main__:Requesting https://www.latimes.com/local/education/la-me-uc-spending-20151011-story.html
INFO:__main__:Getting metadata for https://www.latimes.com/local/education/la-me-uc-spending-20151011-story.html
ERROR:__main__:Could not get metadata for https://www.latimes.com/local/education/la-me-uc-spending-20151011-story.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  6%|▌         | 19/328 [00:42<14:35,  2.83s/it]INFO:__main__:Requesting https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db
INFO:__main__:Getting metadata for https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db
ERROR:__main__:Could not get metadata for https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  6%|▌         | 20/328 [00:43<12:04,  2.35s/it]INFO:__main__:Requesting https://twitter.com/dgmacarthur/status/1028489457803161600?s=09
INFO:__main__:Getting metadata for https://twitter.com/dgmacarthur/status/1028489457803161600?s=09
  6%|▋         | 21/328 [00:44<10:02,  1.96s/it]INFO:__main__:Requesting https://getpolarized.io/2019/01/23/mendeleys-encrypted-repository-is-fundamentally-anti-science.html
INFO:__main__:Getting metadata for https://getpolarized.io/2019/01/23/mendeleys-encrypted-repository-is-fundamentally-anti-science.html
  7%|▋         | 22/328 [00:44<07:20,  1.44s/it]INFO:__main__:Requesting https://www.zotero.org/support/kb/mendeley_import
INFO:__main__:Getting metadata for https://www.zotero.org/support/kb/mendeley_import
  7%|▋         | 23/328 [00:45<06:43,  1.32s/it]INFO:__main__:Requesting https://github.com/retorquere/zotero-better-bibtex
INFO:__main__:Getting metadata for https://github.com/retorquere/zotero-better-bibtex
  7%|▋         | 24/328 [00:46<06:11,  1.22s/it]INFO:__main__:Requesting https://blog.mendeley.com/2019/01/31/the-importance-of-interoperability/
ERROR:__main__:Could not reach https://blog.mendeley.com/2019/01/31/the-importance-of-interoperability/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  8%|▊         | 25/328 [00:47<04:34,  1.11it/s]INFO:__main__:Requesting https://www.josemoura.com
INFO:__main__:Getting metadata for https://www.josemoura.com
  8%|▊         | 26/328 [00:48<04:55,  1.02it/s]INFO:__main__:Requesting https://youtu.be/Sdm698P2AkA?t=88
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=Sdm698P2AkA&feature=youtu.be&t=88
  8%|▊         | 27/328 [00:49<04:39,  1.08it/s]INFO:__main__:Requesting https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
INFO:__main__:Getting metadata for https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
  9%|▊         | 28/328 [00:49<03:40,  1.36it/s]INFO:__main__:Requesting https://web.archive.org/web/20190209202821/https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
INFO:__main__:Getting metadata for https://web.archive.org/web/20190209202821/https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
ERROR:__main__:Could not get metadata for https://web.archive.org/web/20190209202821/https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f612d2dceb8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190209202821/https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f612d2dceb8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190209202821/https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f612d2dceb8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
  9%|▉         | 29/328 [02:57<3:13:37, 38.85s/it]INFO:__main__:Requesting https://www.crui.it/archivio-notizie/i-ricercatori-italiani-potranno-beneficiare-dell%E2%80%99accesso-continuo-al-database-sciencedirect-di-elsevie.html
INFO:__main__:Getting metadata for https://www.crui.it/archivio-notizie/i-ricercatori-italiani-potranno-beneficiare-dell%E2%80%99accesso-continuo-al-database-sciencedirect-di-elsevie.html
  9%|▉         | 30/328 [03:01<2:20:54, 28.37s/it]INFO:__main__:Requesting https://escholarship.org
INFO:__main__:Getting metadata for https://escholarship.org
ERROR:__main__:Could not get metadata for https://escholarship.org
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  9%|▉         | 31/328 [03:01<1:39:07, 20.02s/it]INFO:__main__:Requesting http://rivervalleytechnologies.com/#clients
INFO:__main__:Getting metadata for http://rivervalleytechnologies.com/#clients
 10%|▉         | 32/328 [03:03<1:12:30, 14.70s/it]INFO:__main__:Requesting https://openscience.com/green-oa-vs-gold-oa-which-one-to-choose/
INFO:__main__:Getting metadata for https://openscience.com/green-oa-vs-gold-oa-which-one-to-choose/
 10%|█         | 33/328 [03:05<52:31, 10.68s/it]  INFO:__main__:Requesting https://openaccessmanifesto.wordpress.com/guerilla-open-access-manifesto/
ERROR:__main__:Could not reach https://openaccessmanifesto.wordpress.com/guerilla-open-access-manifesto/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 10%|█         | 34/328 [03:05<36:49,  7.52s/it]INFO:__main__:Requesting https://www.nature.com/articles/d41586-019-00492-4
INFO:__main__:Getting metadata for https://www.nature.com/articles/d41586-019-00492-4
 11%|█         | 35/328 [03:07<29:02,  5.95s/it]INFO:__main__:Requesting https://www.library.ucdavis.edu/uc-elsevier/
INFO:__main__:Getting metadata for https://www.library.ucdavis.edu/uc-elsevier/
 11%|█         | 36/328 [03:08<22:12,  4.56s/it]INFO:__main__:Requesting http://libgen.io/scimag/index.php?s=archaeology
INFO:__main__:Getting metadata for http://libgen.io/scimag/index.php?s=archaeology
 11%|█▏        | 37/328 [03:11<19:45,  4.08s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5832410/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5832410/
 12%|█▏        | 38/328 [03:14<17:27,  3.61s/it]INFO:__main__:Requesting https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/alternative-access-to-articles/
INFO:__main__:Getting metadata for https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/alternative-access-to-articles/
 12%|█▏        | 39/328 [03:14<12:25,  2.58s/it]INFO:__main__:Requesting https://unpaywall.org/products/extension
INFO:__main__:Getting metadata for https://unpaywall.org/products/extension
ERROR:__main__:Could not get metadata for https://unpaywall.org/products/extension
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 12%|█▏        | 40/328 [03:15<09:56,  2.07s/it]INFO:__main__:Requesting https://github.com/nfahlgren/scihub_bookmark
INFO:__main__:Getting metadata for https://github.com/nfahlgren/scihub_bookmark
 12%|█▎        | 41/328 [03:16<08:10,  1.71s/it]INFO:__main__:Requesting https://medium.com/@gagarine/use-sci-hub-with-zotero-as-a-fall-back-pdf-resolver-cf139eb2cea7
INFO:__main__:Getting metadata for https://medium.com/@gagarine/use-sci-hub-with-zotero-as-a-fall-back-pdf-resolver-cf139eb2cea7
 13%|█▎        | 42/328 [03:17<07:58,  1.67s/it]INFO:__main__:Requesting https://twitter.com/sci_hub/status/731467465973174273
INFO:__main__:Getting metadata for https://twitter.com/sci_hub/status/731467465973174273
 13%|█▎        | 43/328 [03:18<06:46,  1.43s/it]INFO:__main__:Requesting https://greasyfork.org/en/scripts/36188-sci-hub-automatic-link/code
INFO:__main__:Getting metadata for https://greasyfork.org/en/scripts/36188-sci-hub-automatic-link/code
ERROR:__main__:Could not get metadata for https://greasyfork.org/en/scripts/36188-sci-hub-automatic-link/code
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 203, in web_preview
    gp = GenericPreview(url, timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 73, in __init__
    self.description = self._get_description()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 97, in _get_description
    if(meta_description and meta_description['content'] !=""):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bs4/element.py", line 1016, in __getitem__
    return self.attrs[key]
KeyError: 'content'
 13%|█▎        | 44/328 [03:19<06:22,  1.35s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=vSPUc70z_Cc
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=vSPUc70z_Cc
 14%|█▎        | 45/328 [03:20<05:48,  1.23s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=bzNowvBmR3g
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=bzNowvBmR3g
 14%|█▍        | 46/328 [03:21<05:13,  1.11s/it]INFO:__main__:Requesting http://thecostofknowledge.com
INFO:__main__:Getting metadata for http://thecostofknowledge.com
 14%|█▍        | 47/328 [03:22<04:32,  1.03it/s]INFO:__main__:Requesting https://www.chronicle.com/article/In-Talks-With-Elsevier-UCLA/245311
 15%|█▍        | 48/328 [03:22<03:25,  1.37it/s]INFO:__main__:Requesting https://www.ucpress.edu/openaccess
INFO:__main__:Getting metadata for https://www.ucpress.edu/openaccess
 15%|█▍        | 49/328 [03:26<07:20,  1.58s/it]INFO:__main__:Requesting https://www.arl.org/focus-areas/scholarly-communication/toward-an-open-monograph-ecosystem
INFO:__main__:Getting metadata for https://www.arl.org/focus-areas/scholarly-communication/toward-an-open-monograph-ecosystem
 15%|█▌        | 50/328 [03:28<07:55,  1.71s/it]INFO:__main__:Requesting http://uc-oa.info
INFO:__main__:Getting metadata for https://osc.universityofcalifornia.edu/open-access-at-uc/open-access-policy/
 16%|█▌        | 51/328 [03:28<06:03,  1.31s/it]INFO:__main__:Requesting http://www.lib.berkeley.edu/using-the-libraries/interlibrary-loan
INFO:__main__:Getting metadata for http://www.lib.berkeley.edu/using-the-libraries/interlibrary-loan
 16%|█▌        | 52/328 [03:29<05:27,  1.19s/it]INFO:__main__:Requesting https://twitter.com/DannyBate4/status/1092132558937169922
INFO:__main__:Getting metadata for https://twitter.com/DannyBate4/status/1092132558937169922
 16%|█▌        | 53/328 [03:30<05:06,  1.11s/it]INFO:__main__:Requesting https://www.sqlite.org/json1.html
INFO:__main__:Getting metadata for https://www.sqlite.org/json1.html
 16%|█▋        | 54/328 [03:31<04:41,  1.03s/it]INFO:__main__:Requesting https://modern-sql.com/blog/2017-06/whats-new-in-sql-2016
INFO:__main__:Getting metadata for https://modern-sql.com/blog/2017-06/whats-new-in-sql-2016
 17%|█▋        | 55/328 [03:32<05:06,  1.12s/it]INFO:__main__:Requesting https://commitfest.postgresql.org/17/1471/
INFO:__main__:Getting metadata for https://commitfest.postgresql.org/17/1471/
ERROR:__main__:Could not get metadata for https://commitfest.postgresql.org/17/1471/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 17%|█▋        | 56/328 [03:34<05:57,  1.31s/it]INFO:__main__:Requesting https://commitfest.postgresql.org/17/1472/
INFO:__main__:Getting metadata for https://commitfest.postgresql.org/17/1472/
ERROR:__main__:Could not get metadata for https://commitfest.postgresql.org/17/1472/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 17%|█▋        | 57/328 [03:35<06:04,  1.35s/it]INFO:__main__:Requesting https://commitfest.postgresql.org/17/1473/
INFO:__main__:Getting metadata for https://commitfest.postgresql.org/17/1473/
ERROR:__main__:Could not get metadata for https://commitfest.postgresql.org/17/1473/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 18%|█▊        | 58/328 [03:37<06:23,  1.42s/it]INFO:__main__:Requesting https://obartunov.livejournal.com/200076.html
INFO:__main__:Getting metadata for https://obartunov.livejournal.com/200076.html
 18%|█▊        | 59/328 [03:41<10:27,  2.33s/it]INFO:__main__:Requesting https://www.postgresql.org/message-id/CAF4Au4w2x-5LTnN_bxky-mq4=WOqsGsxSpENCzHRAzSnEd8+WQ@mail.gmail.com
INFO:__main__:Getting metadata for https://www.postgresql.org/message-id/CAF4Au4w2x-5LTnN_bxky-mq4=WOqsGsxSpENCzHRAzSnEd8+WQ@mail.gmail.com
 18%|█▊        | 60/328 [03:45<11:43,  2.62s/it]INFO:__main__:Requesting https://www.postgresql.org/message-id/00531c7e-f501-b852-9b67-1d1278d035a0%40pgmasters.net
INFO:__main__:Getting metadata for https://www.postgresql.org/message-id/00531c7e-f501-b852-9b67-1d1278d035a0%40pgmasters.net
 19%|█▊        | 61/328 [03:47<12:03,  2.71s/it]INFO:__main__:Requesting https://standards.iso.org/ittf/PubliclyAvailableStandards/
INFO:__main__:Getting metadata for https://standards.iso.org/ittf/PubliclyAvailableStandards/
 19%|█▉        | 62/328 [03:57<21:29,  4.85s/it]INFO:__main__:Requesting https://www.sqlite.org/expridx.html
INFO:__main__:Getting metadata for https://www.sqlite.org/expridx.html
 19%|█▉        | 63/328 [03:58<15:47,  3.57s/it]INFO:__main__:Requesting https://redisql.com/
INFO:__main__:Getting metadata for https://redisql.com
 20%|█▉        | 64/328 [03:58<11:37,  2.64s/it]INFO:__main__:Requesting http://redbeardlab.tech/rediSQL/blog/JaaS/
INFO:__main__:Getting metadata for http://redbeardlab.tech/rediSQL/blog/JaaS/
 20%|█▉        | 65/328 [03:59<08:38,  1.97s/it]INFO:__main__:Requesting http://redbeardlab.tech/rediSQL/blog/golang/using-redisql-with-golang/
INFO:__main__:Getting metadata for http://redbeardlab.tech/rediSQL/blog/golang/using-redisql-with-golang/
 20%|██        | 66/328 [03:59<06:30,  1.49s/it]INFO:__main__:Requesting https://github.com/coast-framework/lighthouse/blob/master/README.md#pull-queries
INFO:__main__:Getting metadata for https://github.com/coast-framework/lighthouse/blob/master/README.md#pull-queries
 20%|██        | 67/328 [04:00<05:32,  1.27s/it]INFO:__main__:Requesting https://www.bbc.co.uk/news/technology-47408969
INFO:__main__:Getting metadata for https://www.bbc.co.uk/news/technology-47408969
 21%|██        | 68/328 [04:01<05:23,  1.24s/it]INFO:__main__:Requesting https://twitter.com/chrisulmer/status/1099366622329036801
INFO:__main__:Getting metadata for https://twitter.com/chrisulmer/status/1099366622329036801
 21%|██        | 69/328 [04:02<04:54,  1.14s/it]INFO:__main__:Requesting https://kotaku.com/blizzards-real-name-forum-policy-has-fans-in-an-uproar-5581209
INFO:__main__:Getting metadata for https://kotaku.com/blizzards-real-name-forum-policy-has-fans-in-an-uproar-5581209
 21%|██▏       | 70/328 [04:02<04:04,  1.05it/s]INFO:__main__:Requesting https://kotaku.com/blizzard-scraps-plans-to-display-real-names-in-forums-5583405
INFO:__main__:Getting metadata for https://kotaku.com/blizzard-scraps-plans-to-display-real-names-in-forums-5583405
 22%|██▏       | 71/328 [04:03<03:23,  1.26it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Eugenics_in_the_United_States
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Eugenics_in_the_United_States
 22%|██▏       | 72/328 [04:05<04:36,  1.08s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Joseph_C._Wilson
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Joseph_C._Wilson
 22%|██▏       | 73/328 [04:06<04:58,  1.17s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=O13G5A5w5P0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=O13G5A5w5P0
 23%|██▎       | 74/328 [04:07<04:36,  1.09s/it]INFO:__main__:Requesting https://news.ycombinator.com/newsguidelines.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/newsguidelines.html
ERROR:__main__:Could not get metadata for https://news.ycombinator.com/newsguidelines.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 23%|██▎       | 75/328 [04:08<04:48,  1.14s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=FMNJuSl91qY
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=FMNJuSl91qY
 23%|██▎       | 76/328 [04:09<04:20,  1.03s/it]INFO:__main__:Requesting https://support.google.com/youtube/answer/7284070?hl=en
INFO:__main__:Getting metadata for https://support.google.com/youtube/answer/7284070?hl=en
 23%|██▎       | 77/328 [04:10<04:03,  1.03it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/I_know_it_when_I_see_it
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/I_know_it_when_I_see_it
 24%|██▍       | 78/328 [04:11<03:47,  1.10it/s]INFO:__main__:Requesting https://slatestarcodex.com/2019/02/22/rip-culture-war-thread/
INFO:__main__:Getting metadata for https://slatestarcodex.com/2019/02/22/rip-culture-war-thread/
 24%|██▍       | 79/328 [04:12<04:53,  1.18s/it]INFO:__main__:Requesting https://www.eff.org/cyberspace-independence
INFO:__main__:Getting metadata for https://www.eff.org/cyberspace-independence
 24%|██▍       | 80/328 [04:13<03:48,  1.09it/s]INFO:__main__:Requesting https://en.wikiquote.org/wiki/John_Gilmore
INFO:__main__:Getting metadata for https://en.wikiquote.org/wiki/John_Gilmore
 25%|██▍       | 81/328 [04:13<03:32,  1.16it/s]INFO:__main__:Requesting https://shift.newco.co/2017/12/26/My-Internet-Mea-Culpa/
INFO:__main__:Getting metadata for https://shift.newco.co/2017/12/26/My-Internet-Mea-Culpa/
 25%|██▌       | 82/328 [04:15<03:53,  1.05it/s]INFO:__main__:Requesting https://medium.com/@hondanhon/no-ones-coming-it-s-up-to-us-de8d9442d0d
INFO:__main__:Getting metadata for https://medium.com/@hondanhon/no-ones-coming-it-s-up-to-us-de8d9442d0d
 25%|██▌       | 83/328 [04:15<03:17,  1.24it/s]INFO:__main__:Requesting https://youtube-creators.googleblog.com/2019/02/more-updates-on-our-actions-related-to.html
INFO:__main__:Getting metadata for https://youtube-creators.googleblog.com/2019/02/more-updates-on-our-actions-related-to.html
 26%|██▌       | 84/328 [04:15<02:30,  1.62it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=hXfWU_ER3Mg
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=hXfWU_ER3Mg
 26%|██▌       | 85/328 [04:16<02:44,  1.48it/s]INFO:__main__:Requesting https://twitter.com/TeamYouTube/status/1100488813854351360
INFO:__main__:Getting metadata for https://twitter.com/TeamYouTube/status/1100488813854351360
 26%|██▌       | 86/328 [04:17<02:43,  1.48it/s]INFO:__main__:Requesting https://d.tube/
INFO:__main__:Getting metadata for https://d.tube
ERROR:__main__:Could not get metadata for https://d.tube
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 27%|██▋       | 87/328 [04:17<02:46,  1.45it/s]INFO:__main__:Requesting https://about.d.tube/
INFO:__main__:Getting metadata for https://about.d.tube
 27%|██▋       | 88/328 [04:18<02:36,  1.53it/s]INFO:__main__:Requesting https://youtu.be/oeI0-ijIotk?t=504
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=oeI0-ijIotk&feature=youtu.be&t=504
 27%|██▋       | 89/328 [04:19<02:58,  1.34it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/reddit-on-youtube/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/reddit-on-youtube/
 27%|██▋       | 90/328 [04:20<03:19,  1.19it/s]INFO:__main__:Requesting http://www.samadhantutors.com/
INFO:__main__:Getting metadata for http://www.samadhantutors.com
 28%|██▊       | 91/328 [04:26<09:13,  2.34s/it]INFO:__main__:Requesting https://medium.com/@jamesbridle/something-is-wrong-on-the-internet-c39c471271d2
INFO:__main__:Getting metadata for https://medium.com/@jamesbridle/something-is-wrong-on-the-internet-c39c471271d2
 28%|██▊       | 92/328 [04:26<06:56,  1.77s/it]INFO:__main__:Requesting https://www.bbc.co.uk/news/technology-47393510
INFO:__main__:Getting metadata for https://www.bbc.co.uk/news/technology-47393510
 28%|██▊       | 93/328 [04:29<07:41,  1.96s/it]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/herp-derp-for-youtube/ioomnmgjblnnolpdgdhebainmfbipjoh?hl=en-US
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/herp-derp-for-youtube/ioomnmgjblnnolpdgdhebainmfbipjoh?hl=en-US
 29%|██▊       | 94/328 [04:29<05:34,  1.43s/it]INFO:__main__:Requesting https://definitions.uslegal.com/c/child-enticement/
INFO:__main__:Getting metadata for https://definitions.uslegal.com/c/child-enticement/
 29%|██▉       | 95/328 [04:32<07:17,  1.88s/it]INFO:__main__:Requesting https://www.theatlantic.com/national/archive/2013/08/government-knocking-doors-because-google-searches/312599/
INFO:__main__:Getting metadata for https://www.theatlantic.com/national/archive/2013/08/government-knocking-doors-because-google-searches/312599/
 29%|██▉       | 96/328 [04:32<05:41,  1.47s/it]INFO:__main__:Requesting https://energy.stanford.edu/news/cheap-renewables-won-t-stop-global-warming-says-bill-gates
INFO:__main__:Getting metadata for https://energy.stanford.edu/news/cheap-renewables-won-t-stop-global-warming-says-bill-gates
 30%|██▉       | 97/328 [04:34<05:28,  1.42s/it]INFO:__main__:Requesting https://www.drawdown.org
INFO:__main__:Getting metadata for https://www.drawdown.org
 30%|██▉       | 98/328 [04:35<05:26,  1.42s/it]INFO:__main__:Requesting http://www.thedrawdownagenda.com/about/
INFO:__main__:Getting metadata for http://www.thedrawdownagenda.com/about/
 30%|███       | 99/328 [04:35<04:05,  1.07s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=d1EB1zsxW0k
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=d1EB1zsxW0k
 30%|███       | 100/328 [04:36<03:47,  1.00it/s]INFO:__main__:Requesting https://www.gatesnotes.com/Books/Energy-and-Civilization
INFO:__main__:Getting metadata for https://www.gatesnotes.com/Books/Energy-and-Civilization
 31%|███       | 101/328 [04:37<03:15,  1.16it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=wGt4XwBbCvA
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=wGt4XwBbCvA
 31%|███       | 102/328 [04:38<03:12,  1.17it/s]INFO:__main__:Requesting https://www.epa.gov/ghgemissions/sources-greenhouse-gas-emissions
INFO:__main__:Getting metadata for https://www.epa.gov/ghgemissions/sources-greenhouse-gas-emissions
 31%|███▏      | 103/328 [04:38<02:45,  1.36it/s]INFO:__main__:Requesting https://ourworldindata.org/grapher/carbon-dioxide-co2-emissions-by-sector-or-source
INFO:__main__:Getting metadata for https://ourworldindata.org/grapher/carbon-dioxide-co2-emissions-by-sector-or-source
 32%|███▏      | 104/328 [04:38<02:29,  1.50it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=lUuu6nRT29Y
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=lUuu6nRT29Y
 32%|███▏      | 105/328 [04:39<02:36,  1.43it/s]INFO:__main__:Requesting https://youtu.be/h45dzeugIZw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=h45dzeugIZw&feature=youtu.be
 32%|███▏      | 106/328 [04:40<02:53,  1.28it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/List_of_countries_by_carbon_dioxide_emissions_per_capita
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/List_of_countries_by_carbon_dioxide_emissions_per_capita
 33%|███▎      | 107/328 [04:44<05:55,  1.61s/it]INFO:__main__:Requesting https://github.com/remacs/remacs
INFO:__main__:Getting metadata for https://github.com/remacs/remacs
 33%|███▎      | 108/328 [04:45<05:36,  1.53s/it]INFO:__main__:Requesting https://www.emacswiki.org/emacs/GuileEmacs
INFO:__main__:Getting metadata for https://www.emacswiki.org/emacs/GuileEmacs
 33%|███▎      | 109/328 [04:49<08:30,  2.33s/it]INFO:__main__:Requesting https://common-lisp.net/project/phemlock/
INFO:__main__:Getting metadata for https://common-lisp.net/project/phemlock/
 34%|███▎      | 110/328 [04:52<08:37,  2.38s/it]INFO:__main__:Requesting https://m.facebook.com/notes/daniel-colascione/buttery-smooth-emacs/10155313440066102/
INFO:__main__:Getting metadata for https://m.facebook.com/notes/daniel-colascione/buttery-smooth-emacs/10155313440066102/
 34%|███▍      | 111/328 [04:53<07:18,  2.02s/it]INFO:__main__:Requesting https://github.com/remacs/remacs/blob/master/README.md#porting-elisp-primitive-functions
INFO:__main__:Getting metadata for https://github.com/remacs/remacs/blob/master/README.md#porting-elisp-primitive-functions
 34%|███▍      | 112/328 [04:54<06:13,  1.73s/it]INFO:__main__:Requesting https://www.emacswiki.org/emacs/EmacsClient
INFO:__main__:Getting metadata for https://www.emacswiki.org/emacs/EmacsClient
 34%|███▍      | 113/328 [04:58<08:44,  2.44s/it]INFO:__main__:Requesting https://github.com/komali2/Configs/tree/master/emacs
INFO:__main__:Getting metadata for https://github.com/komali2/Configs/tree/master/emacs
 35%|███▍      | 114/328 [04:59<06:45,  1.89s/it]INFO:__main__:Requesting http://wiki.c2.com/?EmacsAsOperatingSystem
INFO:__main__:Getting metadata for http://wiki.c2.com/?EmacsAsOperatingSystem
ERROR:__main__:Could not get metadata for http://wiki.c2.com/?EmacsAsOperatingSystem
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 35%|███▌      | 115/328 [04:59<04:57,  1.39s/it]INFO:__main__:Requesting http://emacshorrors.com/posts/unexecute.html
INFO:__main__:Getting metadata for http://emacshorrors.com/posts/unexecute.html
 35%|███▌      | 116/328 [05:00<04:36,  1.30s/it]INFO:__main__:Requesting https://github.com/remacs/remacs/issues/105
INFO:__main__:Getting metadata for https://github.com/remacs/remacs/issues/105
 36%|███▌      | 117/328 [05:02<05:04,  1.44s/it]INFO:__main__:Requesting https://github.com/pugwonk/gif2xlsx/blob/master/README.md
INFO:__main__:Getting metadata for https://github.com/pugwonk/gif2xlsx/blob/master/README.md
 36%|███▌      | 118/328 [05:03<04:17,  1.22s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=UBX2QQHlQ_I
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=UBX2QQHlQ_I
 36%|███▋      | 119/328 [05:04<04:01,  1.16s/it]INFO:__main__:Requesting https://github.com/robertaboukhalil/aioli/
INFO:__main__:Getting metadata for https://github.com/robertaboukhalil/aioli/
 37%|███▋      | 120/328 [05:05<03:59,  1.15s/it]INFO:__main__:Requesting https://github.com/robertaboukhalil/fastq.bio
INFO:__main__:Getting metadata for https://github.com/robertaboukhalil/fastq.bio
 37%|███▋      | 121/328 [05:06<03:46,  1.09s/it]INFO:__main__:Requesting https://chromatic.nci.nih.gov/
INFO:__main__:Getting metadata for https://chromatic.nci.nih.gov
ERROR:__main__:Could not get metadata for https://chromatic.nci.nih.gov
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 37%|███▋      | 122/328 [05:07<04:05,  1.19s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5987889/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5987889/
 38%|███▊      | 123/328 [05:09<04:26,  1.30s/it]INFO:__main__:Requesting https://pagedraw.io/
INFO:__main__:Getting metadata for https://pagedraw.io
 38%|███▊      | 124/328 [05:10<04:05,  1.20s/it]INFO:__main__:Requesting https://medium.com/@gabriel_20625/technical-lessons-from-building-a-compiler-startup-for-3-years-4473405161cd
INFO:__main__:Getting metadata for https://medium.com/@gabriel_20625/technical-lessons-from-building-a-compiler-startup-for-3-years-4473405161cd
 38%|███▊      | 125/328 [05:10<03:16,  1.03it/s]INFO:__main__:Requesting https://medium.com/@jaredpochtar/on-performance-and-software-engineering-44eefa90d46f
INFO:__main__:Getting metadata for https://medium.com/@jaredpochtar/on-performance-and-software-engineering-44eefa90d46f
 38%|███▊      | 126/328 [05:11<02:46,  1.21it/s]INFO:__main__:Requesting https://medium.com/@gabriel_20625/technical-lessons-from-building-a-compiler-startup-for-3-years-4473405161cd*
 39%|███▊      | 127/328 [05:11<02:13,  1.51it/s]INFO:__main__:Requesting https://norvig.com/spell-correct.html
INFO:__main__:Getting metadata for https://norvig.com/spell-correct.html
 39%|███▉      | 128/328 [05:12<03:07,  1.07it/s]INFO:__main__:Requesting https://ourincrediblejourney.tumblr.com/
INFO:__main__:Getting metadata for https://ourincrediblejourney.tumblr.com
 39%|███▉      | 129/328 [05:13<03:01,  1.10it/s]INFO:__main__:Requesting https://youtu.be/hgFkzrqxDcs
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=hgFkzrqxDcs&feature=youtu.be
 40%|███▉      | 130/328 [05:14<02:55,  1.13it/s]INFO:__main__:Requesting https://youtu.be/IpX47gAe150
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=IpX47gAe150&feature=youtu.be
 40%|███▉      | 131/328 [05:15<02:50,  1.15it/s]INFO:__main__:Requesting https://youtu.be/u6uV2X1MGeY
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=u6uV2X1MGeY&feature=youtu.be
 40%|████      | 132/328 [05:16<02:50,  1.15it/s]INFO:__main__:Requesting https://youtu.be/s2dYVret-Ck
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=s2dYVret-Ck&feature=youtu.be
 41%|████      | 133/328 [05:17<02:47,  1.16it/s]INFO:__main__:Requesting https://youtu.be/X6pL0St6NM4
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=X6pL0St6NM4&feature=youtu.be
 41%|████      | 134/328 [05:17<02:42,  1.20it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw/tree/master/src
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw/tree/master/src
 41%|████      | 135/328 [05:18<02:37,  1.23it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw/blob/master/package.json
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw/blob/master/package.json
 41%|████▏     | 136/328 [05:19<02:52,  1.11it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw/blob/master/src/editor/edit-page.cjsx
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw/blob/master/src/editor/edit-page.cjsx
 42%|████▏     | 137/328 [05:21<04:03,  1.28s/it]INFO:__main__:Requesting http://www.paulgraham.com/avg.html
INFO:__main__:Getting metadata for http://www.paulgraham.com/avg.html
ERROR:__main__:Could not get metadata for http://www.paulgraham.com/avg.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 42%|████▏     | 138/328 [05:22<03:24,  1.08s/it]INFO:__main__:Requesting https://shubhamjain.co/2018/12/01/why-paul-graham-wrong/
INFO:__main__:Getting metadata for https://shubhamjain.co/2018/12/01/why-paul-graham-wrong/
ERROR:__main__:Could not get metadata for https://shubhamjain.co/2018/12/01/why-paul-graham-wrong/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 42%|████▏     | 139/328 [05:22<02:42,  1.17it/s]INFO:__main__:Requesting https://reactstudio.com
INFO:__main__:Getting metadata for https://reactstudio.com
 43%|████▎     | 140/328 [05:23<02:47,  1.12it/s]INFO:__main__:Requesting https://www.modulz.app/
INFO:__main__:Getting metadata for https://www.modulz.app
 43%|████▎     | 141/328 [05:24<02:22,  1.31it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw
 43%|████▎     | 142/328 [05:25<02:30,  1.23it/s]INFO:__main__:Requesting https://www.nytimes.com/2019/02/24/business/china-pig-technology-facial-recognition.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/02/24/business/china-pig-technology-facial-recognition.html
 44%|████▎     | 143/328 [05:25<01:57,  1.57it/s]INFO:__main__:Requesting https://www.latimes.com/business/la-fi-san-bernardino-solar-renewable-energy-20190228-story.html
INFO:__main__:Getting metadata for https://www.latimes.com/business/la-fi-san-bernardino-solar-renewable-energy-20190228-story.html
 44%|████▍     | 144/328 [05:25<01:41,  1.81it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Ivanpah_Solar_Power_Facility
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Ivanpah_Solar_Power_Facility
 44%|████▍     | 145/328 [05:27<02:52,  1.06it/s]INFO:__main__:Requesting https://ieeexplore.ieee.org/document/7274289
INFO:__main__:Getting metadata for https://ieeexplore.ieee.org/document/7274289
 45%|████▍     | 146/328 [05:32<06:19,  2.09s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Solar_thermal_energy#Molten_salt_storage
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Solar_thermal_energy#Molten_salt_storage
 45%|████▍     | 147/328 [05:33<05:23,  1.79s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Ivanpah_Solar_Power_Facility
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Ivanpah_Solar_Power_Facility
 45%|████▌     | 148/328 [05:34<04:58,  1.66s/it]INFO:__main__:Requesting https://amp.economist.com/democracy-in-america/2012/08/08/the-balance-trap
INFO:__main__:Getting metadata for https://amp.economist.com/democracy-in-america/2012/08/08/the-balance-trap
 45%|████▌     | 149/328 [05:35<03:47,  1.27s/it]INFO:__main__:Requesting https://youtu.be/PKBENzzEluY
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=PKBENzzEluY&feature=youtu.be
 46%|████▌     | 150/328 [05:36<03:25,  1.15s/it]INFO:__main__:Requesting https://www.sbsun.com/2019/02/28/san-bernardino-county-board-to-prohibit-renewable-energy-development-in-key-desert-areas/
INFO:__main__:Getting metadata for https://www.sbsun.com/2019/02/28/san-bernardino-county-board-to-prohibit-renewable-energy-development-in-key-desert-areas/
 46%|████▌     | 151/328 [05:36<02:43,  1.08it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Path_27
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Path_27
 46%|████▋     | 152/328 [05:37<02:44,  1.07it/s]INFO:__main__:Requesting https://www.openstreetmap.org/relation/3392214
INFO:__main__:Getting metadata for https://www.openstreetmap.org/relation/3392214
 47%|████▋     | 153/328 [05:38<02:53,  1.01it/s]INFO:__main__:Requesting http://sfcitizen.com/blog/2008/10/15/a-san-francisco-general-hospital-helipad-promise-made-then-broken/
INFO:__main__:Getting metadata for http://sfcitizen.com/blog/2008/10/15/a-san-francisco-general-hospital-helipad-promise-made-then-broken/
 47%|████▋     | 154/328 [05:39<02:44,  1.06it/s]INFO:__main__:Requesting https://www.mercurynews.com/2018/10/06/turn-schools-into-teacher-housing-bay-area-community-up-in-arms-over-unique-idea/
INFO:__main__:Getting metadata for https://www.mercurynews.com/2018/10/06/turn-schools-into-teacher-housing-bay-area-community-up-in-arms-over-unique-idea/
 47%|████▋     | 155/328 [05:40<02:56,  1.02s/it]INFO:__main__:Requesting https://quillette.com/2019/02/27/why-renewables-cant-save-the-planet/
INFO:__main__:Getting metadata for https://quillette.com/2019/02/27/why-renewables-cant-save-the-planet/
 48%|████▊     | 156/328 [05:41<02:30,  1.14it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Diablo_Canyon_Power_Plant#Closure_in_2024%E2%80%932025
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Diablo_Canyon_Power_Plant#Closure_in_2024%E2%80%932025
 48%|████▊     | 157/328 [05:42<02:53,  1.01s/it]INFO:__main__:Requesting https://www.worldwildlife.org/habitats/deserts
INFO:__main__:Getting metadata for https://www.worldwildlife.org/habitats/deserts
 48%|████▊     | 158/328 [05:42<02:17,  1.23it/s]INFO:__main__:Requesting https://www.environmentalscience.org/deserts-ecosystems
INFO:__main__:Getting metadata for https://www.environmentalscience.org/deserts-ecosystems
 48%|████▊     | 159/328 [05:53<10:36,  3.77s/it]INFO:__main__:Requesting https://www.mercurynews.com/2019/02/21/its-almost-time-for-californias-super-bloom/
INFO:__main__:Getting metadata for https://www.mercurynews.com/2019/02/21/its-almost-time-for-californias-super-bloom/
 49%|████▉     | 160/328 [05:54<08:01,  2.87s/it]INFO:__main__:Requesting https://phys.org/news/2009-03-dark-side-solar-power.html
INFO:__main__:Getting metadata for https://phys.org/news/2009-03-dark-side-solar-power.html
 49%|████▉     | 161/328 [05:54<06:05,  2.19s/it]INFO:__main__:Requesting https://imgur.com/a/blZbs5e
INFO:__main__:Getting metadata for https://imgur.com/a/blZbs5e
ERROR:__main__:Could not get metadata for https://imgur.com/a/blZbs5e
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 49%|████▉     | 162/328 [05:55<04:29,  1.63s/it]INFO:__main__:Requesting https://www.audubon.org/conservation/audubons-position-wind-power
INFO:__main__:Getting metadata for https://www.audubon.org/conservation/audubons-position-wind-power
 50%|████▉     | 163/328 [05:55<03:30,  1.28s/it]INFO:__main__:Requesting https://github.com/CovenantSQL/CovenantForum
INFO:__main__:Getting metadata for https://github.com/CovenantSQL/CovenantForum
 50%|█████     | 164/328 [05:56<03:03,  1.12s/it]INFO:__main__:Requesting https://demo.covenantsql.io/forum/
INFO:__main__:Getting metadata for https://demo.covenantsql.io/forum/
ERROR:__main__:Could not get metadata for https://demo.covenantsql.io/forum/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 50%|█████     | 165/328 [06:01<06:15,  2.31s/it]INFO:__main__:Requesting https://github.com/CovenantSQL/CovenantForum#comments-on-blockchain
INFO:__main__:Getting metadata for https://github.com/CovenantSQL/CovenantForum#comments-on-blockchain
 51%|█████     | 166/328 [06:02<05:10,  1.92s/it]INFO:__main__:Requesting https://www.scuttlebutt.nz/
INFO:__main__:Getting metadata for https://www.scuttlebutt.nz
 51%|█████     | 167/328 [06:03<04:17,  1.60s/it]INFO:__main__:Requesting https://github.com/CovenantSQL/CovenantSQL/blob/develop/logo/rpc.png
INFO:__main__:Getting metadata for https://github.com/CovenantSQL/CovenantSQL/blob/develop/logo/rpc.png
 51%|█████     | 168/328 [06:04<03:43,  1.39s/it]INFO:__main__:Requesting https://github.com/CovenantSQL/CovenantSQL/tree/develop/rpc
INFO:__main__:Getting metadata for https://github.com/CovenantSQL/CovenantSQL/tree/develop/rpc
 52%|█████▏    | 169/328 [06:05<03:13,  1.22s/it]INFO:__main__:Requesting https://github.com/sunrise-choir
INFO:__main__:Getting metadata for https://github.com/sunrise-choir
 52%|█████▏    | 170/328 [06:05<02:55,  1.11s/it]INFO:__main__:Requesting https://github.com/antonmedv/fx-completion
INFO:__main__:Getting metadata for https://github.com/antonmedv/fx-completion
 52%|█████▏    | 171/328 [06:06<02:37,  1.00s/it]INFO:__main__:Requesting https://github.com/antonmedv/fx-completion/blob/master/complete.sh
INFO:__main__:Getting metadata for https://github.com/antonmedv/fx-completion/blob/master/complete.sh
 52%|█████▏    | 172/328 [06:07<02:26,  1.07it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Feature_detection_(web_development)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Feature_detection_(web_development)
 53%|█████▎    | 173/328 [06:08<02:16,  1.14it/s]INFO:__main__:Requesting http://www.oilshell.org/blog/2019/02/05.html
INFO:__main__:Getting metadata for http://www.oilshell.org/blog/2019/02/05.html
ERROR:__main__:Could not get metadata for http://www.oilshell.org/blog/2019/02/05.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 53%|█████▎    | 174/328 [06:08<01:56,  1.32it/s]INFO:__main__:Requesting https://github.com/triska/lisprolog
INFO:__main__:Getting metadata for https://github.com/triska/lisprolog
 53%|█████▎    | 175/328 [06:09<01:54,  1.33it/s]INFO:__main__:Requesting http://tonsky.me/blog/github-redesign/
INFO:__main__:Getting metadata for http://tonsky.me/blog/github-redesign/
 54%|█████▎    | 176/328 [06:09<01:24,  1.79it/s]INFO:__main__:Requesting https://github.com/ozoneplatform/owf-framework/wiki
INFO:__main__:Getting metadata for https://github.com/ozoneplatform/owf-framework/wiki
 54%|█████▍    | 177/328 [06:10<01:37,  1.55it/s]INFO:__main__:Requesting https://octobanana.com/software/fltrdr
INFO:__main__:Getting metadata for https://octobanana.com/software/fltrdr
 54%|█████▍    | 178/328 [06:11<01:55,  1.30it/s]INFO:__main__:Requesting https://pbs.twimg.com/media/De17PIKXUAE27W6.jpg:large
INFO:__main__:Getting metadata for https://pbs.twimg.com/media/De17PIKXUAE27W6.jpg:large
ERROR:__main__:Could not get metadata for https://pbs.twimg.com/media/De17PIKXUAE27W6.jpg:large
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 55%|█████▍    | 179/328 [06:19<07:05,  2.85s/it]INFO:__main__:Requesting https://twitter.com/nikitonsky/status/1003593821723267072?s=21
INFO:__main__:Getting metadata for https://twitter.com/nikitonsky/status/1003593821723267072?s=21
 55%|█████▍    | 180/328 [06:20<05:40,  2.30s/it]INFO:__main__:Requesting https://www.k2.com/platform/workflow
INFO:__main__:Getting metadata for https://www.k2.com/platform/workflow
 55%|█████▌    | 181/328 [06:22<05:37,  2.30s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Sparkline
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Sparkline
 55%|█████▌    | 182/328 [06:23<04:27,  1.83s/it]INFO:__main__:Requesting https://github.com/ruby/ruby#readme
INFO:__main__:Getting metadata for https://github.com/ruby/ruby#readme
 56%|█████▌    | 183/328 [06:24<04:19,  1.79s/it]INFO:__main__:Requesting https://github.com/tonsky
INFO:__main__:Getting metadata for https://github.com/tonsky
 56%|█████▌    | 184/328 [06:26<04:20,  1.81s/it]INFO:__main__:Requesting https://ianstormtaylor.com/refactoring-githubs-design/
INFO:__main__:Getting metadata for https://ianstormtaylor.com/refactoring-githubs-design/
 56%|█████▋    | 185/328 [06:27<03:34,  1.50s/it]INFO:__main__:Requesting https://github.com/mrchief/github-redesign
INFO:__main__:Getting metadata for https://github.com/mrchief/github-redesign
 57%|█████▋    | 186/328 [06:28<03:08,  1.33s/it]INFO:__main__:Requesting http://tonsky.me/blog/github-redesign/160_files_buttons.png
INFO:__main__:Getting metadata for http://tonsky.me/blog/github-redesign/160_files_buttons.png
ERROR:__main__:Could not get metadata for http://tonsky.me/blog/github-redesign/160_files_buttons.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 57%|█████▋    | 187/328 [06:36<07:38,  3.25s/it]INFO:__main__:Requesting https://www.sendthemtomir.com/blog/cli-2-factor-authentication
INFO:__main__:Getting metadata for https://www.sendthemtomir.com/blog/cli-2-factor-authentication
 57%|█████▋    | 188/328 [06:37<06:13,  2.67s/it]INFO:__main__:Requesting https://support.yubico.com/support/solutions/articles/15000012643-yubikey-manager-cli-ykman-user-manual#ykman_oathwicpwc
INFO:__main__:Getting metadata for https://support.yubico.com/support/solutions/articles/15000012643-yubikey-manager-cli-ykman-user-manual#ykman_oathwicpwc
 58%|█████▊    | 189/328 [06:40<06:37,  2.86s/it]INFO:__main__:Requesting https://github.com/romanz/trezor-agent
INFO:__main__:Getting metadata for https://github.com/romanz/trezor-agent
 58%|█████▊    | 190/328 [06:41<05:16,  2.29s/it]INFO:__main__:Requesting https://github.com/tadfisher/pass-otp
INFO:__main__:Getting metadata for https://github.com/tadfisher/pass-otp
 58%|█████▊    | 191/328 [06:42<04:14,  1.85s/it]INFO:__main__:Requesting https://github.com/browserpass/browserpass
INFO:__main__:Getting metadata for https://github.com/browserpass/browserpass
 59%|█████▊    | 192/328 [06:44<03:54,  1.73s/it]INFO:__main__:Requesting https://github.com/zeapo/Android-Password-Store
INFO:__main__:Getting metadata for https://github.com/zeapo/Android-Password-Store
 59%|█████▉    | 193/328 [06:44<03:23,  1.50s/it]INFO:__main__:Requesting https://bitbucket.org/devinmartin/keeotp/wiki/Home
INFO:__main__:Getting metadata for https://bitbucket.org/devinmartin/keeotp/wiki/Home
 59%|█████▉    | 194/328 [06:46<03:30,  1.57s/it]INFO:__main__:Requesting https://sourceforge.net/projects/traytotp-kp2/
INFO:__main__:Getting metadata for https://sourceforge.net/projects/traytotp-kp2/
 59%|█████▉    | 195/328 [06:47<03:17,  1.48s/it]INFO:__main__:Requesting https://qtpass.org/
INFO:__main__:Getting metadata for https://qtpass.org
 60%|█████▉    | 196/328 [06:49<03:04,  1.40s/it]INFO:__main__:Requesting https://github.com/w8rbt/oathgen
INFO:__main__:Getting metadata for https://github.com/w8rbt/oathgen
 60%|██████    | 197/328 [06:50<02:41,  1.23s/it]INFO:__main__:Requesting https://github.com/w8rbt/goathgen
INFO:__main__:Getting metadata for https://github.com/w8rbt/goathgen
 60%|██████    | 198/328 [06:50<02:23,  1.10s/it]INFO:__main__:Requesting https://gitlab.com/elagost/linux-2fa
INFO:__main__:Getting metadata for https://gitlab.com/elagost/linux-2fa
 61%|██████    | 199/328 [06:51<02:11,  1.02s/it]INFO:__main__:Requesting https://www.clockworkpi.com/
INFO:__main__:Getting metadata for https://www.clockworkpi.com
 61%|██████    | 200/328 [06:55<03:40,  1.72s/it]INFO:__main__:Requesting https://www.idontplaydarts.com/2011/07/google-totp-two-factor-authentication-for-php/
INFO:__main__:Getting metadata for https://www.idontplaydarts.com/2011/07/google-totp-two-factor-authentication-for-php/
 61%|██████▏   | 201/328 [06:56<03:17,  1.56s/it]INFO:__main__:Requesting https://github.com/rsc/2fa
INFO:__main__:Getting metadata for https://github.com/rsc/2fa
 62%|██████▏   | 202/328 [06:57<02:49,  1.34s/it]INFO:__main__:Requesting https://otp.codebro.org
INFO:__main__:Getting metadata for https://otp.codebro.org
 62%|██████▏   | 203/328 [06:57<02:13,  1.06s/it]INFO:__main__:Requesting https://pastebin.com/9CLhPiff
INFO:__main__:Getting metadata for https://pastebin.com/9CLhPiff
ERROR:__main__:Could not get metadata for https://pastebin.com/9CLhPiff
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 62%|██████▏   | 204/328 [06:57<01:41,  1.22it/s]INFO:__main__:Requesting https://sod.pixlab.io/articles/license-plate-detection.html
INFO:__main__:Getting metadata for https://sod.pixlab.io/articles/license-plate-detection.html
 62%|██████▎   | 205/328 [07:00<02:45,  1.34s/it]INFO:__main__:Requesting http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.455.2440&rep=rep1&type=pdf
INFO:__main__:Getting metadata for http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.455.2440&rep=rep1&type=pdf
ERROR:__main__:Could not get metadata for http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.455.2440&rep=rep1&type=pdf
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 63%|██████▎   | 206/328 [07:22<15:31,  7.64s/it]INFO:__main__:Requesting https://github.com/mathDR/reading-text-in-the-wild/blob/master/README.md
INFO:__main__:Getting metadata for https://github.com/mathDR/reading-text-in-the-wild/blob/master/README.md
 63%|██████▎   | 207/328 [07:23<11:16,  5.59s/it]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/random-wikipedia/kanbdekniajhfdofkbikiclgccplhfjg
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/random-wikipedia/kanbdekniajhfdofkbikiclgccplhfjg
 63%|██████▎   | 208/328 [07:23<07:55,  3.97s/it]INFO:__main__:Requesting https://phys.org/news/2019-02-million-year-old-worm-superhighway-canada.html
INFO:__main__:Getting metadata for https://phys.org/news/2019-02-million-year-old-worm-superhighway-canada.html
 64%|██████▎   | 209/328 [07:23<05:44,  2.89s/it]INFO:__main__:Requesting https://www.eurekalert.org/multimedia/pub/194320.php
INFO:__main__:Getting metadata for https://www.eurekalert.org/multimedia/pub/194320.php
 64%|██████▍   | 210/328 [07:24<04:17,  2.18s/it]INFO:__main__:Requesting https://pubs.geoscienceworld.org/gsa/geology/article-abstract/47/3/231/568392/extensive-bioturbation-in-a-middle-cambrian
INFO:__main__:Getting metadata for https://pubs.geoscienceworld.org/gsa/geology/article-abstract/47/3/231/568392/extensive-bioturbation-in-a-middle-cambrian
ERROR:__main__:Could not get metadata for https://pubs.geoscienceworld.org/gsa/geology/article-abstract/47/3/231/568392/extensive-bioturbation-in-a-middle-cambrian
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 64%|██████▍   | 211/328 [07:25<03:45,  1.92s/it]INFO:__main__:Requesting https://lineageos.org/Changelog-22/
INFO:__main__:Getting metadata for https://lineageos.org/Changelog-22/
 65%|██████▍   | 212/328 [07:26<02:50,  1.47s/it]INFO:__main__:Requesting https://www.gsmarena.com/google_pixel_xl-8345.php
INFO:__main__:Getting metadata for https://www.gsmarena.com/google_pixel_xl-8345.php
 65%|██████▍   | 213/328 [07:30<04:11,  2.19s/it]INFO:__main__:Requesting https://www.reddit.com/r/LineageOS/comments/at3bf5/_/egzcoxb/
INFO:__main__:Getting metadata for https://www.reddit.com/r/LineageOS/comments/at3bf5/_/egzcoxb/
 65%|██████▌   | 214/328 [07:30<03:18,  1.74s/it]INFO:__main__:Requesting https://www.androidbenchmark.net/device_list.php
INFO:__main__:Getting metadata for https://www.androidbenchmark.net/device_list.php
 66%|██████▌   | 215/328 [07:32<03:30,  1.86s/it]INFO:__main__:Requesting https://www.dxomark.com/google-pixel-camera-review-retested-new-dxomark-mobile-protocols/
INFO:__main__:Getting metadata for https://www.dxomark.com/google-pixel-camera-review-retested-new-dxomark-mobile-protocols/
 66%|██████▌   | 216/328 [07:34<03:09,  1.69s/it]INFO:__main__:Requesting https://www.gsmarena.com/motorola_moto_z2_force-8693.php
INFO:__main__:Getting metadata for https://www.gsmarena.com/motorola_moto_z2_force-8693.php
 66%|██████▌   | 217/328 [07:38<04:17,  2.32s/it]INFO:__main__:Requesting https://www.dxomark.com/motorola-moto-z2-force-review-motorolas-dual-cam-flagship/
INFO:__main__:Getting metadata for https://www.dxomark.com/motorola-moto-z2-force-review-motorolas-dual-cam-flagship/
 66%|██████▋   | 218/328 [07:39<03:36,  1.97s/it]INFO:__main__:Requesting https://www.motorola.com/us/moto-mods
INFO:__main__:Getting metadata for https://www.motorola.com/us/moto-mods
 67%|██████▋   | 219/328 [07:39<02:48,  1.55s/it]INFO:__main__:Requesting https://www.androidauthority.com/xiaomi-redmi-note-7-pro-960973/
INFO:__main__:Getting metadata for https://www.androidauthority.com/xiaomi-redmi-note-7-pro-960973/
 67%|██████▋   | 220/328 [07:40<02:16,  1.26s/it]INFO:__main__:Requesting https://www.gsmarena.com/nokia_6_1-8972.php
INFO:__main__:Getting metadata for https://www.gsmarena.com/nokia_6_1-8972.php
 67%|██████▋   | 221/328 [07:44<03:35,  2.02s/it]INFO:__main__:Requesting https://downloads.aospextended.com/PL2
INFO:__main__:Getting metadata for https://downloads.aospextended.com/PL2
 68%|██████▊   | 222/328 [07:44<02:38,  1.49s/it]INFO:__main__:Requesting https://builds.lineageos.org
INFO:__main__:Getting metadata for https://builds.lineageos.org
ERROR:__main__:Could not get metadata for https://builds.lineageos.org
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 68%|██████▊   | 223/328 [07:45<02:19,  1.33s/it]INFO:__main__:Requesting https://niftylettuce.com/posts/google-free-android-setup/
INFO:__main__:Getting metadata for https://niftylettuce.com/posts/google-free-android-setup/
 68%|██████▊   | 224/328 [07:45<01:42,  1.01it/s]INFO:__main__:Requesting https://lineageos.org/feed.xml
INFO:__main__:Getting metadata for https://lineageos.org/feed.xml
ERROR:__main__:Could not get metadata for https://lineageos.org/feed.xml
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 69%|██████▊   | 225/328 [07:46<01:38,  1.04it/s]INFO:__main__:Requesting https://www.lineageoslog.com/
INFO:__main__:Getting metadata for https://www.lineageoslog.com
 69%|██████▉   | 226/328 [07:47<01:47,  1.06s/it]INFO:__main__:Requesting https://forum.xda-developers.com/
INFO:__main__:Getting metadata for https://forum.xda-developers.com
 69%|██████▉   | 227/328 [07:48<01:34,  1.06it/s]INFO:__main__:Requesting https://review.lineageos.org
INFO:__main__:Getting metadata for https://review.lineageos.org
 70%|██████▉   | 228/328 [07:50<02:17,  1.38s/it]INFO:__main__:Requesting https://github.com/LineageOS
INFO:__main__:Getting metadata for https://github.com/LineageOS
 70%|██████▉   | 229/328 [07:51<02:06,  1.28s/it]INFO:__main__:Requesting https://www.reddit.com/r/LineageOS/comments/9ulb17/is_there_a_mailing_list_for_lineageos/
INFO:__main__:Getting metadata for https://www.reddit.com/r/LineageOS/comments/9ulb17/is_there_a_mailing_list_for_lineageos/
 70%|███████   | 230/328 [07:52<01:48,  1.10s/it]INFO:__main__:Requesting https://www.reddit.com/r/LineageOS/comments/an1fo9/whats_holding_back_the_los16_release/efr5rc4/
INFO:__main__:Getting metadata for https://www.reddit.com/r/LineageOS/comments/an1fo9/whats_holding_back_the_los16_release/efr5rc4/
 70%|███████   | 231/328 [07:53<01:31,  1.06it/s]INFO:__main__:Requesting https://wiki.lineageos.org/devices/zerofltexx/
INFO:__main__:Getting metadata for https://wiki.lineageos.org/devices/zerofltexx/
 71%|███████   | 232/328 [07:53<01:28,  1.08it/s]INFO:__main__:Requesting https://www.androidpolice.com/2018/04/05/dont-freak-lineageos-bad-late-april-fools-joke-latest-builds/
INFO:__main__:Getting metadata for https://www.androidpolice.com/2018/04/05/dont-freak-lineageos-bad-late-april-fools-joke-latest-builds/
 71%|███████   | 233/328 [07:54<01:22,  1.16it/s]INFO:__main__:Requesting https://lineageos.org/An-April-Apology/
INFO:__main__:Getting metadata for https://lineageos.org/An-April-Apology/
 71%|███████▏  | 234/328 [07:54<01:04,  1.46it/s]INFO:__main__:Requesting https://www.mathieustern.com/blog/2018/10/22/l437fjpq58g619vlkm6t1iwhk8s6dr
INFO:__main__:Getting metadata for https://www.mathieustern.com/blog/2018/10/22/l437fjpq58g619vlkm6t1iwhk8s6dr
 72%|███████▏  | 235/328 [07:55<01:06,  1.40it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=bUHcCHbgX_o
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=bUHcCHbgX_o
 72%|███████▏  | 236/328 [07:56<01:11,  1.30it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Water_memory
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Water_memory
 72%|███████▏  | 237/328 [07:57<01:18,  1.16it/s]INFO:__main__:Requesting https://www.urbandictionary.com/define.php?term=no%20homeo
INFO:__main__:Getting metadata for https://www.urbandictionary.com/define.php?term=no%20homeo
 73%|███████▎  | 238/328 [07:57<01:00,  1.49it/s]INFO:__main__:Requesting https://www.studioneat.com/products/neaticekit
INFO:__main__:Getting metadata for https://www.studioneat.com/products/neaticekit
 73%|███████▎  | 239/328 [07:58<01:02,  1.43it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=sNohIFrbkXM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=sNohIFrbkXM
 73%|███████▎  | 240/328 [07:59<01:05,  1.34it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Fresnel_lens
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Fresnel_lens
 73%|███████▎  | 241/328 [08:00<01:17,  1.13it/s]INFO:__main__:Requesting https://www.medicalnewstoday.com/articles/302550.php
INFO:__main__:Getting metadata for https://www.medicalnewstoday.com/articles/302550.php
 74%|███████▍  | 242/328 [08:01<01:22,  1.04it/s]INFO:__main__:Requesting https://www.ted.com/talks/josh_silver_demos_adjustable_liquid_filled_eyeglasses?language=en
INFO:__main__:Getting metadata for https://www.ted.com/talks/josh_silver_demos_adjustable_liquid_filled_eyeglasses?language=en
 74%|███████▍  | 243/328 [08:02<01:16,  1.12it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Liquid_mirror_telescope
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Liquid_mirror_telescope
 74%|███████▍  | 244/328 [08:03<01:18,  1.07it/s]INFO:__main__:Requesting https://www.imaging-resource.com/news/2015/10/05/this-smartphone-camera-uses-liquid-crystal-and-electrical-currents-to-focus
INFO:__main__:Getting metadata for https://www.imaging-resource.com/news/2015/10/05/this-smartphone-camera-uses-liquid-crystal-and-electrical-currents-to-focus
 75%|███████▍  | 245/328 [08:07<02:36,  1.89s/it]INFO:__main__:Requesting http://www.laurawaller.com/opticsfun/sugarGRINlens.htm
 75%|███████▌  | 246/328 [08:07<01:51,  1.36s/it]INFO:__main__:Requesting https://www.flickr.com/photos/130436300@N07/44672960900
INFO:__main__:Getting metadata for https://www.flickr.com/photos/130436300@N07/44672960900
 75%|███████▌  | 247/328 [08:08<01:39,  1.23s/it]INFO:__main__:Requesting https://kottke.org/19/02/a-camera-lens-made-from-an-iceberg
INFO:__main__:Getting metadata for https://kottke.org/19/02/a-camera-lens-made-from-an-iceberg
 76%|███████▌  | 248/328 [08:09<01:15,  1.06it/s]INFO:__main__:Requesting https://github.com/zelon88/xPress
INFO:__main__:Getting metadata for https://github.com/zelon88/xPress
 76%|███████▌  | 249/328 [08:09<01:12,  1.09it/s]INFO:__main__:Requesting https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-xca/a8b7cb0a-92a6-4187-a23b-5e14273b96f8
INFO:__main__:Getting metadata for https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-xca/a8b7cb0a-92a6-4187-a23b-5e14273b96f8
 76%|███████▌  | 250/328 [08:10<01:01,  1.26it/s]INFO:__main__:Requesting https://www.tesla.com/blog/35000-tesla-model-3-available-now
INFO:__main__:Getting metadata for https://www.tesla.com/blog/35000-tesla-model-3-available-now
 77%|███████▋  | 251/328 [08:10<00:49,  1.55it/s]INFO:__main__:Requesting https://www.businessinsider.com/tesla-is-eliminating-most-of-its-stores-and-going-to-an-online-only-sales-model-2019-2
INFO:__main__:Getting metadata for https://www.businessinsider.com/tesla-is-eliminating-most-of-its-stores-and-going-to-an-online-only-sales-model-2019-2
 77%|███████▋  | 252/328 [08:11<00:39,  1.90it/s]INFO:__main__:Requesting https://www.dmv.org/vehicle-history/odometer-fraud.php
INFO:__main__:Getting metadata for https://www.dmv.org/vehicle-history/odometer-fraud.php
 77%|███████▋  | 253/328 [08:11<00:33,  2.25it/s]INFO:__main__:Requesting https://www.theverge.com/2019/2/28/18245296/tesla-stores-closing-online-only-car-sales
INFO:__main__:Getting metadata for https://www.theverge.com/2019/2/28/18245296/tesla-stores-closing-online-only-car-sales
 77%|███████▋  | 254/328 [08:11<00:27,  2.65it/s]INFO:__main__:Requesting https://www.cnbc.com/amp/2019/02/21/tesla-refund-and-return-problems-detailed.html
INFO:__main__:Getting metadata for https://www.cnbc.com/amp/2019/02/21/tesla-refund-and-return-problems-detailed.html
 78%|███████▊  | 255/328 [08:12<00:33,  2.20it/s]INFO:__main__:Requesting https://www.tesla.com/drive
INFO:__main__:Getting metadata for https://www.tesla.com/drive
 78%|███████▊  | 256/328 [08:12<00:27,  2.62it/s]INFO:__main__:Requesting https://www.researchgate.net/profile/Till_Stowasser/publication/295859167/figure/fig4/AS:411667432263684@1475160572644/Distribution-of-car-prices.png
INFO:__main__:Getting metadata for https://www.researchgate.net/profile/Till_Stowasser/publication/295859167/figure/fig4/AS:411667432263684@1475160572644/Distribution-of-car-prices.png
ERROR:__main__:Could not get metadata for https://www.researchgate.net/profile/Till_Stowasser/publication/295859167/figure/fig4/AS:411667432263684@1475160572644/Distribution-of-car-prices.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 78%|███████▊  | 257/328 [08:14<01:08,  1.04it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Household_income_in_the_United_States
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Household_income_in_the_United_States
 79%|███████▊  | 258/328 [08:16<01:31,  1.31s/it]INFO:__main__:Requesting http://apps.urban.org/features/wealth-inequality-charts/img/Retirement.jpg
INFO:__main__:Getting metadata for http://apps.urban.org/features/wealth-inequality-charts/img/Retirement.jpg
ERROR:__main__:Could not get metadata for http://apps.urban.org/features/wealth-inequality-charts/img/Retirement.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 79%|███████▉  | 259/328 [08:31<05:59,  5.22s/it]INFO:__main__:Requesting https://whatever.scalzi.com/2005/09/03/being-poor/
ERROR:__main__:Could not reach https://whatever.scalzi.com/2005/09/03/being-poor/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 79%|███████▉  | 260/328 [08:31<04:11,  3.70s/it]INFO:__main__:Requesting https://fred.stlouisfed.org/series/MEHOINUSA672N/
INFO:__main__:Getting metadata for https://fred.stlouisfed.org/series/MEHOINUSA672N/
ERROR:__main__:Could not get metadata for https://fred.stlouisfed.org/series/MEHOINUSA672N/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 80%|███████▉  | 261/328 [08:33<03:31,  3.15s/it]INFO:__main__:Requesting https://smartasset.com/checking-account/savings-account-average-balance
INFO:__main__:Getting metadata for https://smartasset.com/checking-account/savings-account-average-balance
 80%|███████▉  | 262/328 [08:35<03:13,  2.93s/it]INFO:__main__:Requesting https://forums.tesla.com/forum/forums/why-does-it-take-months-repair-tesla
INFO:__main__:Getting metadata for https://forums.tesla.com/forum/forums/why-does-it-take-months-repair-tesla
 80%|████████  | 263/328 [08:36<02:33,  2.36s/it]INFO:__main__:Requesting https://teslamotorsclub.com/tmc/threads/repair-time-6-months.112515/
INFO:__main__:Getting metadata for https://teslamotorsclub.com/tmc/threads/repair-time-6-months.112515/
 80%|████████  | 264/328 [08:37<02:12,  2.08s/it]INFO:__main__:Requesting https://www.driving.co.uk/news/features/tesla-owners-facing-extended-wait-repairs/
INFO:__main__:Getting metadata for https://www.driving.co.uk/news/features/tesla-owners-facing-extended-wait-repairs/
 81%|████████  | 265/328 [08:41<02:31,  2.41s/it]INFO:__main__:Requesting https://www.sfchronicle.com/business/article/Tesla-owners-fume-about-delays-for-service-13112104.php
INFO:__main__:Getting metadata for https://www.sfchronicle.com/business/article/Tesla-owners-fume-about-delays-for-service-13112104.php
 81%|████████  | 266/328 [08:41<01:55,  1.86s/it]INFO:__main__:Requesting https://cleantechnica.com/2018/04/16/tesla-batteries-have-90-capacity-after-160000-miles-may-last-for-500000-miles/
INFO:__main__:Getting metadata for https://cleantechnica.com/2018/04/16/tesla-batteries-have-90-capacity-after-160000-miles-may-last-for-500000-miles/
 81%|████████▏ | 267/328 [08:41<01:23,  1.37s/it]INFO:__main__:Requesting https://www.libertytax.com/tax-lounge/electric-car-and-vehicle-tax-credit-what-to-know-and-how-to-claim-it/
INFO:__main__:Getting metadata for https://www.libertytax.com/tax-lounge/electric-car-and-vehicle-tax-credit-what-to-know-and-how-to-claim-it/
 82%|████████▏ | 268/328 [08:42<01:02,  1.03s/it]INFO:__main__:Requesting https://nextmove.de/autobahn-test-tesla-model-x-beats-audi-e-tron-jaguar-i-pace/
INFO:__main__:Getting metadata for https://nextmove.de/autobahn-test-tesla-model-x-beats-audi-e-tron-jaguar-i-pace/
 82%|████████▏ | 269/328 [08:44<01:15,  1.29s/it]INFO:__main__:Requesting https://www.theverge.com/2019/2/28/18245165/tesla-model-3-price-lower-cost-elon-musk-news
INFO:__main__:Getting metadata for https://www.theverge.com/2019/2/28/18245165/tesla-model-3-price-lower-cost-elon-musk-news
 82%|████████▏ | 270/328 [08:44<00:56,  1.04it/s]INFO:__main__:Requesting https://www.paulolyslager.com/decoy-effect-price-tables/
INFO:__main__:Getting metadata for https://www.paulolyslager.com/decoy-effect-price-tables/
 83%|████████▎ | 271/328 [08:44<00:42,  1.35it/s]INFO:__main__:Requesting https://3.tesla.com/model3/design#battery
INFO:__main__:Getting metadata for https://3.tesla.com/model3/design#battery
 83%|████████▎ | 272/328 [08:47<01:18,  1.40s/it]INFO:__main__:Requesting https://3.tesla.com/model3/design?redirect=no#battery
INFO:__main__:Getting metadata for https://3.tesla.com/model3/design?redirect=no#battery
 83%|████████▎ | 273/328 [08:50<01:45,  1.92s/it]INFO:__main__:Requesting https://electrek.co/2018/11/20/tesla-gigafactory-battery-cells-made-cost-advantage-panasonic-lg-report/
INFO:__main__:Getting metadata for https://electrek.co/2018/11/20/tesla-gigafactory-battery-cells-made-cost-advantage-panasonic-lg-report/
 84%|████████▎ | 274/328 [08:51<01:25,  1.58s/it]INFO:__main__:Requesting https://insideevs.com/tesla-cheapest-battery-pack-costs/
INFO:__main__:Getting metadata for https://insideevs.com/tesla-cheapest-battery-pack-costs/
 84%|████████▍ | 275/328 [08:52<01:14,  1.41s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Tesla_Model_3
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Tesla_Model_3
 84%|████████▍ | 276/328 [08:54<01:26,  1.66s/it]INFO:__main__:Requesting https://darkpatterns.org/
INFO:__main__:Getting metadata for https://darkpatterns.org
 84%|████████▍ | 277/328 [08:55<01:12,  1.41s/it]INFO:__main__:Requesting https://www.chevrolet.com/electric/bolt-ev-electric-car
INFO:__main__:Getting metadata for https://www.chevrolet.com/electric/bolt-ev-electric-car
 85%|████████▍ | 278/328 [08:57<01:22,  1.65s/it]INFO:__main__:Requesting https://electrek.co/2018/04/14/tesla-battery-degradation-data/
INFO:__main__:Getting metadata for https://electrek.co/2018/04/14/tesla-battery-degradation-data/
 85%|████████▌ | 279/328 [08:58<01:08,  1.39s/it]INFO:__main__:Requesting https://cleanvehiclerebate.org/eng/income-eligibility
INFO:__main__:Getting metadata for https://cleanvehiclerebate.org/eng/income-eligibility
 85%|████████▌ | 280/328 [08:58<00:52,  1.10s/it]INFO:__main__:Requesting https://www.businessinsider.com/tesla-to-pay-march-convertible-debt-cash-stock-report-2018-12?r=US&IR=T
INFO:__main__:Getting metadata for https://www.businessinsider.com/tesla-to-pay-march-convertible-debt-cash-stock-report-2018-12?r=US&IR=T
 86%|████████▌ | 281/328 [08:59<00:39,  1.20it/s]INFO:__main__:Requesting https://3.tesla.com/model3/design?redirect=no
INFO:__main__:Getting metadata for https://3.tesla.com/model3/design?redirect=no
 86%|████████▌ | 282/328 [09:02<01:19,  1.73s/it]INFO:__main__:Requesting https://mazdasla.com/wp-content/uploads/2018/10/Mazda-Protege-2019-Interior.png
INFO:__main__:Getting metadata for https://mazdasla.com/wp-content/uploads/2018/10/Mazda-Protege-2019-Interior.png
ERROR:__main__:Could not get metadata for https://mazdasla.com/wp-content/uploads/2018/10/Mazda-Protege-2019-Interior.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 86%|████████▋ | 283/328 [09:13<03:11,  4.27s/it]INFO:__main__:Requesting http://gtcarlot.com/data/Mazda/Protege/1999/12552040/Dashboard-70858347.html
INFO:__main__:Getting metadata for http://gtcarlot.com/data/Mazda/Protege/1999/12552040/Dashboard-70858347.html
ERROR:__main__:Could not get metadata for http://gtcarlot.com/data/Mazda/Protege/1999/12552040/Dashboard-70858347.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 87%|████████▋ | 284/328 [09:13<02:16,  3.10s/it]INFO:__main__:Requesting https://www.stoddard.com/media/catalog/category/IMG_1365.jpg
INFO:__main__:Getting metadata for https://www.stoddard.com/media/catalog/category/IMG_1365.jpg
ERROR:__main__:Could not get metadata for https://www.stoddard.com/media/catalog/category/IMG_1365.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 87%|████████▋ | 285/328 [09:16<02:07,  2.95s/it]INFO:__main__:Requesting https://www.google.com/search?q=honda+paint+defects+on+delivery
INFO:__main__:Getting metadata for https://www.google.com/search?q=honda+paint+defects+on+delivery
 87%|████████▋ | 286/328 [09:19<02:08,  3.06s/it]INFO:__main__:Requesting https://www.google.com/search?q=bmw+paint+defects+on+delivery+-tesla
INFO:__main__:Getting metadata for https://www.google.com/search?q=bmw+paint+defects+on+delivery+-tesla
 88%|████████▊ | 287/328 [09:22<02:09,  3.16s/it]INFO:__main__:Requesting https://www.google.com/search?q=chevy+paint+defects+on+delivery
INFO:__main__:Getting metadata for https://www.google.com/search?q=chevy+paint+defects+on+delivery
 88%|████████▊ | 288/328 [09:26<02:10,  3.25s/it]INFO:__main__:Requesting https://youtu.be/FSLTNjGI8hw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=FSLTNjGI8hw&feature=youtu.be
 88%|████████▊ | 289/328 [09:27<01:38,  2.54s/it]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2019-02-27/musk-s-tweets-all-but-assure-cash-payout-for-920-million-bond
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=f6e30de0-3c01-11e9-80c3-cf6e5f58d631&url=L25ld3MvYXJ0aWNsZXMvMjAxOS0wMi0yNy9tdXNrLXMtdHdlZXRzLWFsbC1idXQtYXNzdXJlLWNhc2gtcGF5b3V0LWZvci05MjAtbWlsbGlvbi1ib25k
 88%|████████▊ | 290/328 [09:27<01:13,  1.93s/it]INFO:__main__:Requesting http://www.quantwolf.com/calculators/bonddefaultcalc.html
INFO:__main__:Getting metadata for http://www.quantwolf.com/calculators/bonddefaultcalc.html
ERROR:__main__:Could not get metadata for http://www.quantwolf.com/calculators/bonddefaultcalc.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 89%|████████▊ | 291/328 [09:28<00:56,  1.52s/it]INFO:__main__:Requesting https://markets.businessinsider.com/bonds/tesla_incdl-notes_201717-25_regs-bond-2025-usu8810laa18
INFO:__main__:Getting metadata for https://markets.businessinsider.com/bonds/tesla_incdl-notes_201717-25_regs-bond-2025-usu8810laa18
ERROR:__main__:Could not get metadata for https://markets.businessinsider.com/bonds/tesla_incdl-notes_201717-25_regs-bond-2025-usu8810laa18
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 89%|████████▉ | 292/328 [09:28<00:46,  1.29s/it]INFO:__main__:Requesting https://unintendedconsequenc.es/uyghurs-xinjiang-onward-to-the-inevitable/
 89%|████████▉ | 293/328 [09:29<00:34,  1.02it/s]INFO:__main__:Requesting https://www.businessinsider.com/china-tiananmen-square-2014-5?IR=T
INFO:__main__:Getting metadata for https://www.businessinsider.com/china-tiananmen-square-2014-5?IR=T
 90%|████████▉ | 294/328 [09:29<00:25,  1.33it/s]INFO:__main__:Requesting https://www.forbes.com/sites/ralphjennings/2016/12/29/why-asia-has-a-fascination-for-hitler-and-the-nazis/
INFO:__main__:Getting metadata for https://www.forbes.com/sites/ralphjennings/2016/12/29/why-asia-has-a-fascination-for-hitler-and-the-nazis/
 90%|████████▉ | 295/328 [09:30<00:23,  1.42it/s]INFO:__main__:Requesting https://www.uyghurcongress.org/en/?p=37293
ERROR:__main__:Could not reach https://www.uyghurcongress.org/en/?p=37293
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.uyghurcongress.org', port=443): Max retries exceeded with url: /en/?p=37293 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.uyghurcongress.org', port=443): Max retries exceeded with url: /en/?p=37293 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
 90%|█████████ | 296/328 [09:30<00:19,  1.63it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Judeo-Christian#Inter-group_relations
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Judeo-Christian#Inter-group_relations
 91%|█████████ | 297/328 [09:31<00:22,  1.38it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Realistic_conflict_theory
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Realistic_conflict_theory
 91%|█████████ | 298/328 [09:32<00:22,  1.32it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Abrahamic_religions
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Abrahamic_religions
 91%|█████████ | 299/328 [09:34<00:33,  1.16s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Islamization_of_Xinjiang
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Islamization_of_Xinjiang
 91%|█████████▏| 300/328 [09:36<00:36,  1.31s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Dehomag
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Dehomag
 92%|█████████▏| 301/328 [09:36<00:29,  1.11s/it]INFO:__main__:Requesting https://www.nytimes.com/interactive/2018/09/20/us/politics/russia-interference-election-trump-clinton.html
INFO:__main__:Getting metadata for https://www.nytimes.com/interactive/2018/09/20/us/politics/russia-interference-election-trump-clinton.html
 92%|█████████▏| 302/328 [09:37<00:29,  1.15s/it]INFO:__main__:Requesting https://www.washingtonpost.com/politics/how-the-bad-boys-of-brexit-forged-ties-with-russia-and-the-trump-campaign--and-came-under-investigators-scrutiny/2018/06/28/6e3a5e9c-7656-11e8-b4b7-308400242c2e_story.html
ERROR:__main__:Could not reach https://www.washingtonpost.com/politics/how-the-bad-boys-of-brexit-forged-ties-with-russia-and-the-trump-campaign--and-came-under-investigators-scrutiny/2018/06/28/6e3a5e9c-7656-11e8-b4b7-308400242c2e_story.html
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 92%|█████████▏| 303/328 [09:43<01:05,  2.62s/it]INFO:__main__:Requesting https://www.bbc.com/news/technology-41182519
INFO:__main__:Getting metadata for https://www.bbc.com/news/technology-41182519
 93%|█████████▎| 304/328 [09:45<00:58,  2.42s/it]INFO:__main__:Requesting https://www.axios.com/senate-reports-russian-interference-2016-election-9d0daca6-1e2d-4617-9295-f8eec61c1719.html
INFO:__main__:Getting metadata for https://www.axios.com/senate-reports-russian-interference-2016-election-9d0daca6-1e2d-4617-9295-f8eec61c1719.html
 93%|█████████▎| 305/328 [09:46<00:41,  1.81s/it]INFO:__main__:Requesting https://www.vox.com/policy-and-politics/2018/2/20/17031772/mueller-indictments-grand-jury
INFO:__main__:Getting metadata for https://www.vox.com/policy-and-politics/2018/2/20/17031772/mueller-indictments-grand-jury
 93%|█████████▎| 306/328 [09:46<00:31,  1.41s/it]INFO:__main__:Requesting https://bitbucket.org/blog/meet-bitbucket-pipes-30-ways-to-automate-your-ci-cd-pipeline
INFO:__main__:Getting metadata for https://bitbucket.org/blog/meet-bitbucket-pipes-30-ways-to-automate-your-ci-cd-pipeline
 94%|█████████▎| 307/328 [09:47<00:23,  1.10s/it]INFO:__main__:Requesting https://concourse-ci.org/resources.html
INFO:__main__:Getting metadata for https://concourse-ci.org/resources.html
 94%|█████████▍| 308/328 [09:47<00:17,  1.11it/s]INFO:__main__:Requesting https://concourse-ci.org/implementing-resources.html
INFO:__main__:Getting metadata for https://concourse-ci.org/implementing-resources.html
 94%|█████████▍| 309/328 [09:48<00:14,  1.27it/s]INFO:__main__:Requesting https://erlef.org/
INFO:__main__:Getting metadata for https://erlef.org
 95%|█████████▍| 310/328 [09:48<00:13,  1.35it/s]INFO:__main__:Requesting https://twitter.com/sheharyarn/status/1101306957531570176
INFO:__main__:Getting metadata for https://twitter.com/sheharyarn/status/1101306957531570176
 95%|█████████▍| 311/328 [09:49<00:13,  1.30it/s]INFO:__main__:Requesting https://github.com/dockcross/dockcross#dockcross
INFO:__main__:Getting metadata for https://github.com/dockcross/dockcross#dockcross
 95%|█████████▌| 312/328 [09:50<00:14,  1.07it/s]INFO:__main__:Requesting https://servicelab.org/2018/09/13/platform-aware-docker-images/
ERROR:__main__:Could not reach https://servicelab.org/2018/09/13/platform-aware-docker-images/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 95%|█████████▌| 313/328 [09:51<00:10,  1.43it/s]INFO:__main__:Requesting https://github.com/OpenRCT2/OpenRCT2/blob/develop/dockerfiles/mingw/Dockerfile
INFO:__main__:Getting metadata for https://github.com/OpenRCT2/OpenRCT2/blob/develop/dockerfiles/mingw/Dockerfile
 96%|█████████▌| 314/328 [09:51<00:10,  1.34it/s]INFO:__main__:Requesting https://blog.mozilla.org/blog/2019/02/28/sharing-our-common-voices-mozilla-releases-the-largest-to-date-public-domain-transcribed-voice-dataset/
INFO:__main__:Getting metadata for https://blog.mozilla.org/blog/2019/02/28/sharing-our-common-voices-mozilla-releases-the-largest-to-date-public-domain-transcribed-voice-dataset/
 96%|█████████▌| 315/328 [09:52<00:08,  1.47it/s]INFO:__main__:Requesting http://www.openslr.org/12/
INFO:__main__:Getting metadata for http://www.openslr.org/12/
 96%|█████████▋| 316/328 [09:53<00:10,  1.14it/s]INFO:__main__:Requesting https://hacks.mozilla.org/2017/11/a-journey-to-10-word-error-rate/
INFO:__main__:Getting metadata for https://hacks.mozilla.org/2017/11/a-journey-to-10-word-error-rate/
 97%|█████████▋| 317/328 [09:54<00:08,  1.28it/s]INFO:__main__:Requesting https://m.youtube.com/watch?v=NMS2VnDveP8
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=NMS2VnDveP8&app=desktop
 97%|█████████▋| 318/328 [09:55<00:08,  1.20it/s]INFO:__main__:Requesting https://discourse.mozilla.org/t/listen-guidance/35608
INFO:__main__:Getting metadata for https://discourse.mozilla.org/t/listen-guidance/35608
 97%|█████████▋| 319/328 [09:55<00:06,  1.39it/s]INFO:__main__:Requesting http://trumped.com
INFO:__main__:Getting metadata for http://trumped.com
 98%|█████████▊| 320/328 [09:56<00:05,  1.48it/s]INFO:__main__:Requesting http://cs.lmu.edu/~ray/notes/nasmtutorial/
INFO:__main__:Getting metadata for http://cs.lmu.edu/~ray/notes/nasmtutorial/
 98%|█████████▊| 321/328 [09:57<00:05,  1.32it/s]INFO:__main__:Requesting https://github.com/JohnSully/KeyDB/blob/unstable/src/fastlock_x64.asm
INFO:__main__:Getting metadata for https://github.com/JohnSully/KeyDB/blob/unstable/src/fastlock_x64.asm
 98%|█████████▊| 322/328 [09:58<00:04,  1.32it/s]INFO:__main__:Requesting https://github.com/skx/math-compiler/
INFO:__main__:Getting metadata for https://github.com/skx/math-compiler/
 98%|█████████▊| 323/328 [09:58<00:03,  1.27it/s]INFO:__main__:Requesting https://github.com/rigetti/quilc
INFO:__main__:Getting metadata for https://github.com/rigetti/quilc
 99%|█████████▉| 324/328 [10:00<00:03,  1.12it/s]INFO:__main__:Requesting https://medium.com/qiskit/how-to-turn-on-your-quantum-computer-fba0a4152d92
INFO:__main__:Getting metadata for https://medium.com/qiskit/how-to-turn-on-your-quantum-computer-fba0a4152d92
 99%|█████████▉| 325/328 [10:00<00:02,  1.25it/s]INFO:__main__:Requesting https://rigetti.com/qcs
INFO:__main__:Getting metadata for https://rigetti.com/qcs
 99%|█████████▉| 326/328 [10:01<00:01,  1.44it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=f9vRcSAneiw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=f9vRcSAneiw
100%|█████████▉| 327/328 [10:01<00:00,  1.38it/s]INFO:__main__:Requesting https://starcity.com/careers/2f0058c7-b3ab-4538-8366-7f7d95118227
INFO:__main__:Getting metadata for https://starcity.com/careers/2f0058c7-b3ab-4538-8366-7f7d95118227
100%|██████████| 328/328 [10:03<00:00,  1.12it/s]
