INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:01<00:33,  1.16s/it] 10%|█         | 3/30 [00:01<00:22,  1.21it/s] 17%|█▋        | 5/30 [00:01<00:16,  1.54it/s] 23%|██▎       | 7/30 [00:02<00:11,  1.99it/s] 30%|███       | 9/30 [00:03<00:12,  1.62it/s] 33%|███▎      | 10/30 [00:03<00:09,  2.15it/s] 37%|███▋      | 11/30 [00:05<00:14,  1.28it/s] 40%|████      | 12/30 [00:05<00:11,  1.62it/s] 43%|████▎     | 13/30 [00:07<00:17,  1.01s/it] 47%|████▋     | 14/30 [00:07<00:11,  1.34it/s] 57%|█████▋    | 17/30 [00:08<00:07,  1.74it/s] 60%|██████    | 18/30 [00:11<00:15,  1.25s/it] 63%|██████▎   | 19/30 [00:13<00:16,  1.51s/it] 77%|███████▋  | 23/30 [00:13<00:07,  1.08s/it] 87%|████████▋ | 26/30 [00:16<00:04,  1.01s/it] 93%|█████████▎| 28/30 [00:17<00:01,  1.04it/s] 97%|█████████▋| 29/30 [00:18<00:00,  1.15it/s]100%|██████████| 30/30 [00:18<00:00,  1.52it/s]
  0%|          | 0/166 [00:00<?, ?it/s]INFO:__main__:Requesting https://www.bloombergquint.com/businessweek/america-s-cities-are-running-on-software-from-the-80s
INFO:__main__:Getting metadata for https://www.bloombergquint.com/businessweek/america-s-cities-are-running-on-software-from-the-80s
  1%|          | 1/166 [00:00<01:31,  1.81it/s]INFO:__main__:Requesting https://www.twincities.com/2019/02/14/mn-dmv-mnlars-report-department-driver-vehicle-services/
INFO:__main__:Getting metadata for https://www.twincities.com/2019/02/14/mn-dmv-mnlars-report-department-driver-vehicle-services/
  1%|          | 2/166 [00:01<01:39,  1.65it/s]INFO:__main__:Requesting https://github.com/cosmos72/gomacro#gomacro---interactive-go-interpreter-and-debugger-with-generics-and-macros
INFO:__main__:Getting metadata for https://github.com/cosmos72/gomacro#gomacro---interactive-go-interpreter-and-debugger-with-generics-and-macros
  2%|▏         | 3/166 [00:02<02:31,  1.08it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=hGY3uBHVVr4
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=hGY3uBHVVr4
  2%|▏         | 4/166 [00:03<02:26,  1.11it/s]INFO:__main__:Requesting https://github.com/kanaka/mal/blob/master/process/guide.md
INFO:__main__:Getting metadata for https://github.com/kanaka/mal/blob/master/process/guide.md
  3%|▎         | 5/166 [00:04<02:34,  1.04it/s]INFO:__main__:Requesting https://github.com/krig/LISP
INFO:__main__:Getting metadata for https://github.com/krig/LISP
  4%|▎         | 6/166 [00:08<04:18,  1.62s/it]INFO:__main__:Requesting https://hacks.mozilla.org/2019/02/rewriting-a-browser-component-in-rust/
INFO:__main__:Getting metadata for https://hacks.mozilla.org/2019/02/rewriting-a-browser-component-in-rust/
  4%|▍         | 7/166 [00:08<03:22,  1.27s/it]INFO:__main__:Requesting https://www.smithsonianmag.com/innovation/will-ai-ever-be-smarter-than-four-year-old-180971259/
INFO:__main__:Getting metadata for https://www.smithsonianmag.com/innovation/will-ai-ever-be-smarter-than-four-year-old-180971259/
  5%|▍         | 8/166 [00:08<02:42,  1.03s/it]INFO:__main__:Requesting https://www.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it?language=en
INFO:__main__:Getting metadata for https://www.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it?language=en
  5%|▌         | 9/166 [00:09<02:20,  1.12it/s]INFO:__main__:Requesting https://rockentry.com/blogs/the-crux/avoiding-problem-paralysis
INFO:__main__:Getting metadata for https://rockentry.com/blogs/the-crux/avoiding-problem-paralysis
  6%|▌         | 10/166 [00:10<02:01,  1.28it/s]INFO:__main__:Requesting https://www.tandfonline.com/doi/full/10.1080/02791072.2019.1580804
INFO:__main__:Getting metadata for https://www.tandfonline.com/doi/full/10.1080/02791072.2019.1580804
  7%|▋         | 11/166 [00:12<03:24,  1.32s/it]INFO:__main__:Requesting https://www.lucasfcosta.com/2019/02/10/terminal-guide-2019.html
INFO:__main__:Getting metadata for https://www.lucasfcosta.com/2019/02/10/terminal-guide-2019.html
  7%|▋         | 12/166 [00:13<03:06,  1.21s/it]INFO:__main__:Requesting https://www.hillelwayne.com/post/formally-specifying-uis/
INFO:__main__:Getting metadata for https://www.hillelwayne.com/post/formally-specifying-uis/
  8%|▊         | 13/166 [00:13<02:19,  1.10it/s]INFO:__main__:Requesting https://github.com/mukeshsoni/statechart-calculator
INFO:__main__:Getting metadata for https://github.com/mukeshsoni/statechart-calculator
  8%|▊         | 14/166 [00:14<02:25,  1.04it/s]INFO:__main__:Requesting https://www.amazon.com/Constructing-User-Interface-Statecharts-Horrocks/dp/0201342782
INFO:__main__:Getting metadata for https://www.amazon.com/Constructing-User-Interface-Statecharts-Horrocks/dp/0201342782
  9%|▉         | 15/166 [00:20<05:48,  2.31s/it]INFO:__main__:Requesting https://medium.com/imandra/constraint-solving-your-uis-8933f4cf8927
INFO:__main__:Getting metadata for https://medium.com/imandra/constraint-solving-your-uis-8933f4cf8927
 10%|▉         | 16/166 [00:21<04:31,  1.81s/it]INFO:__main__:Requesting https://medium.com/imandra/verifying-reasonreact-component-logic-reasonml-imandra-e350d4812a9f
INFO:__main__:Getting metadata for https://medium.com/imandra/verifying-reasonreact-component-logic-reasonml-imandra-e350d4812a9f
 10%|█         | 17/166 [00:21<03:41,  1.49s/it]INFO:__main__:Requesting https://reactjs.org/docs/hooks-reference.html#usereducer
INFO:__main__:Getting metadata for https://reactjs.org/docs/hooks-reference.html#usereducer
 11%|█         | 18/166 [00:22<03:02,  1.23s/it]INFO:__main__:Requesting https://sketch.systems/rgraves-aspiration/sketch/e85b70fd4ec153e7a22137b6070f00ef
INFO:__main__:Getting metadata for https://sketch.systems/rgraves-aspiration/sketch/e85b70fd4ec153e7a22137b6070f00ef
ERROR:__main__:Could not get metadata for https://sketch.systems/rgraves-aspiration/sketch/e85b70fd4ec153e7a22137b6070f00ef
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 11%|█▏        | 19/166 [00:23<03:03,  1.25s/it]INFO:__main__:Requesting https://pudding.cool/2019/02/gyllenhaal/
INFO:__main__:Getting metadata for https://pudding.cool/2019/02/gyllenhaal/
 12%|█▏        | 20/166 [00:23<02:16,  1.07it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Sankey_diagram
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Sankey_diagram
 13%|█▎        | 21/166 [00:24<02:04,  1.17it/s]INFO:__main__:Requesting https://futureofcoding.org/episodes/025.html
INFO:__main__:Getting metadata for https://futureofcoding.org/episodes/025.html
ERROR:__main__:Could not get metadata for https://futureofcoding.org/episodes/025.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 13%|█▎        | 22/166 [00:24<01:38,  1.46it/s]INFO:__main__:Requesting https://elm-lang.org
INFO:__main__:Getting metadata for https://elm-lang.org
ERROR:__main__:Could not get metadata for https://elm-lang.org
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 14%|█▍        | 23/166 [00:25<01:53,  1.26it/s]INFO:__main__:Requesting https://branchfree.org/2019/02/28/paper-hyperscan-a-fast-multi-pattern-regex-matcher-for-modern-cpus/
ERROR:__main__:Could not reach https://branchfree.org/2019/02/28/paper-hyperscan-a-fast-multi-pattern-regex-matcher-for-modern-cpus/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 14%|█▍        | 24/166 [00:26<01:25,  1.66it/s]INFO:__main__:Requesting https://github.com/BurntSushi/ripgrep
INFO:__main__:Getting metadata for https://github.com/BurntSushi/ripgrep
 15%|█▌        | 25/166 [00:27<02:13,  1.06it/s]INFO:__main__:Requesting https://github.com/shenfe/python-hyperscan
INFO:__main__:Getting metadata for https://github.com/shenfe/python-hyperscan
 16%|█▌        | 26/166 [00:28<02:19,  1.00it/s]INFO:__main__:Requesting https://thelri.org/blog-and-news/why-drugs-that-work-in-mice-dont-work-in-humans/
INFO:__main__:Getting metadata for https://thelri.org/blog-and-news/why-drugs-that-work-in-mice-dont-work-in-humans/
 16%|█▋        | 27/166 [00:29<01:55,  1.20it/s]INFO:__main__:Requesting https://www.quora.com/Do-you-agree-with-the-controversial-views-of-Dr-B-M-Hegde-when-it-comes-to-medicine-and-doctors
INFO:__main__:Getting metadata for https://www.quora.com/Do-you-agree-with-the-controversial-views-of-Dr-B-M-Hegde-when-it-comes-to-medicine-and-doctors
 17%|█▋        | 28/166 [00:32<03:42,  1.62s/it]INFO:__main__:Requesting http://dogagingproject.com
 17%|█▋        | 29/166 [00:32<02:41,  1.18s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/28374166/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5411365/
 18%|█▊        | 30/166 [00:34<02:57,  1.30s/it]INFO:__main__:Requesting https://www.leafscience.org/dr-matt-kaeberlein-the-dog-aging-project/
INFO:__main__:Getting metadata for https://www.leafscience.org/dr-matt-kaeberlein-the-dog-aging-project/
 19%|█▊        | 31/166 [00:35<02:29,  1.11s/it]INFO:__main__:Requesting https://europepmc.org/abstract/pmc/pmc1142312
INFO:__main__:Getting metadata for https://europepmc.org/abstract/pmc/pmc1142312
ERROR:__main__:Could not get metadata for https://europepmc.org/abstract/pmc/pmc1142312
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 19%|█▉        | 32/166 [00:40<05:03,  2.27s/it]INFO:__main__:Requesting https://grapesjs.com/
INFO:__main__:Getting metadata for https://grapesjs.com
 20%|█▉        | 33/166 [00:40<03:39,  1.65s/it]INFO:__main__:Requesting https://github.com/artf/grapesjs/tree/dev/test/specs
INFO:__main__:Getting metadata for https://github.com/artf/grapesjs/tree/dev/test/specs
 20%|██        | 34/166 [00:41<03:00,  1.37s/it]INFO:__main__:Requesting https://avatars2.githubusercontent.com/u/11614725?s=400&v=4
INFO:__main__:Getting metadata for https://avatars2.githubusercontent.com/u/11614725?s=400&v=4
ERROR:__main__:Could not get metadata for https://avatars2.githubusercontent.com/u/11614725?s=400&v=4
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 21%|██        | 35/166 [00:42<02:53,  1.33s/it]INFO:__main__:Requesting https://codepen.io/yulian/full/rRNxJx
INFO:__main__:Getting metadata for https://codepen.io/yulian/full/rRNxJx
 22%|██▏       | 36/166 [00:42<02:19,  1.07s/it]INFO:__main__:Requesting https://github.com/ioulian
INFO:__main__:Getting metadata for https://github.com/ioulian
 22%|██▏       | 37/166 [00:44<02:57,  1.38s/it]INFO:__main__:Requesting http://sagartewari01.com/c-macro-magic/
INFO:__main__:Getting metadata for http://sagartewari01.com/c-macro-magic/
 23%|██▎       | 38/166 [00:45<02:27,  1.15s/it]INFO:__main__:Requesting https://ziglang.org/documentation/master/#fieldParentPtr
INFO:__main__:Getting metadata for https://ziglang.org/documentation/master/#fieldParentPtr
 23%|██▎       | 39/166 [00:50<04:38,  2.20s/it]INFO:__main__:Requesting https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/list.h?h=v5.0-rc8
INFO:__main__:Getting metadata for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/list.h?h=v5.0-rc8
ERROR:__main__:Could not get metadata for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/list.h?h=v5.0-rc8
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 24%|██▍       | 40/166 [00:52<04:27,  2.13s/it]INFO:__main__:Requesting https://elixir.bootlin.com/linux/v2.6.11/source/include/linux/list.h
INFO:__main__:Getting metadata for https://elixir.bootlin.com/linux/v2.6.11/source/include/linux/list.h
 25%|██▍       | 41/166 [00:59<07:44,  3.72s/it]INFO:__main__:Requesting https://github.com/freebsd/freebsd/blob/master/sys/sys/queue.h
INFO:__main__:Getting metadata for https://github.com/freebsd/freebsd/blob/master/sys/sys/queue.h
 25%|██▌       | 42/166 [01:01<06:31,  3.16s/it]INFO:__main__:Requesting https://stackoverflow.com/questions/15832301/understanding-container-of-macro-in-the-linux-kernel
INFO:__main__:Getting metadata for https://stackoverflow.com/questions/15832301/understanding-container-of-macro-in-the-linux-kernel
 26%|██▌       | 43/166 [01:01<04:48,  2.35s/it]INFO:__main__:Requesting http://www.catb.org/esr/structure-packing/#_structure_alignment_and_padding
INFO:__main__:Getting metadata for http://www.catb.org/esr/structure-packing/#_structure_alignment_and_padding
 27%|██▋       | 44/166 [01:02<04:01,  1.98s/it]INFO:__main__:Requesting https://github.com/Amanieu/intrusive-rs
INFO:__main__:Getting metadata for https://github.com/Amanieu/intrusive-rs
 27%|██▋       | 45/166 [01:04<03:38,  1.81s/it]INFO:__main__:Requesting http://ccodearchive.net/info/list.html
INFO:__main__:Getting metadata for http://ccodearchive.net/info/list.html
 28%|██▊       | 46/166 [01:07<04:16,  2.13s/it]INFO:__main__:Requesting https://docs.microsoft.com/en-us/windows/desktop/api/ntdef/ns-ntdef-_list_entry
INFO:__main__:Getting metadata for https://docs.microsoft.com/en-us/windows/desktop/api/ntdef/ns-ntdef-_list_entry
 28%|██▊       | 47/166 [01:07<03:18,  1.67s/it]INFO:__main__:Requesting https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=LIST_ENTRY
INFO:__main__:Getting metadata for https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=LIST_ENTRY
ERROR:__main__:Could not get metadata for https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=LIST_ENTRY
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 29%|██▉       | 48/166 [01:19<09:25,  4.79s/it]INFO:__main__:Requesting http://man7.org/linux/man-pages/man3/queue.3.html
INFO:__main__:Getting metadata for http://man7.org/linux/man-pages/man3/queue.3.html
ERROR:__main__:Could not get metadata for http://man7.org/linux/man-pages/man3/queue.3.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 30%|██▉       | 49/166 [01:22<08:01,  4.11s/it]INFO:__main__:Requesting https://gitlab.com/oliver117/ucds/tree/master/src
INFO:__main__:Getting metadata for https://gitlab.com/oliver117/ucds/tree/master/src
 30%|███       | 50/166 [01:23<06:04,  3.14s/it]INFO:__main__:Requesting https://github.com/glouw/andvaranaut/blob/master/src/Theme.c
INFO:__main__:Getting metadata for https://github.com/glouw/andvaranaut/blob/master/src/Theme.c
 31%|███       | 51/166 [01:24<04:43,  2.46s/it]INFO:__main__:Requesting https://randomascii.wordpress.com/2012/12/29/the-surprising-subtleties-of-zeroing-a-register/
ERROR:__main__:Could not reach https://randomascii.wordpress.com/2012/12/29/the-surprising-subtleties-of-zeroing-a-register/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 31%|███▏      | 52/166 [01:24<03:21,  1.76s/it]INFO:__main__:Requesting https://www.realworldtech.com/sandy-bridge/5
INFO:__main__:Getting metadata for https://www.realworldtech.com/sandy-bridge/5/
 32%|███▏      | 53/166 [01:25<03:07,  1.66s/it]INFO:__main__:Requesting https://github.com/KrzysztofSzewczyk/Euboea
INFO:__main__:Getting metadata for https://github.com/KrzysztofSzewczyk/Euboea
 33%|███▎      | 54/166 [01:26<02:51,  1.53s/it]INFO:__main__:Requesting https://arxiv.org/abs/1901.10664
INFO:__main__:Getting metadata for https://arxiv.org/abs/1901.10664
 33%|███▎      | 55/166 [01:28<02:36,  1.41s/it]INFO:__main__:Requesting https://github.com/emmericp/ixy
INFO:__main__:Getting metadata for https://github.com/emmericp/ixy
 34%|███▎      | 56/166 [01:29<02:25,  1.32s/it]INFO:__main__:Requesting https://github.com/emmericp/ixy/pull/14
INFO:__main__:Getting metadata for https://github.com/emmericp/ixy/pull/14
 34%|███▍      | 57/166 [01:32<03:32,  1.95s/it]INFO:__main__:Requesting https://github.com/ixy-languages/ixy-languages
INFO:__main__:Getting metadata for https://github.com/ixy-languages/ixy-languages
 35%|███▍      | 58/166 [01:33<02:57,  1.64s/it]INFO:__main__:Requesting https://media.ccc.de/v/34c3-9159-demystifying_network_cards
INFO:__main__:Getting metadata for https://media.ccc.de/v/34c3-9159-demystifying_network_cards
 36%|███▌      | 59/166 [01:34<02:49,  1.58s/it]INFO:__main__:Requesting https://media.ccc.de/v/35c3-9670-safe_and_secure_drivers_in_high-level_languages
INFO:__main__:Getting metadata for https://media.ccc.de/v/35c3-9670-safe_and_secure_drivers_in_high-level_languages
 36%|███▌      | 60/166 [01:36<02:32,  1.44s/it]INFO:__main__:Requesting https://fosdem.org/2019/schedule/event/writing_network_drivers_in_high_level_languages/
INFO:__main__:Getting metadata for https://fosdem.org/2019/schedule/event/writing_network_drivers_in_high_level_languages/
ERROR:__main__:Could not get metadata for https://fosdem.org/2019/schedule/event/writing_network_drivers_in_high_level_languages/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 37%|███▋      | 61/166 [01:37<02:23,  1.36s/it]INFO:__main__:Requesting http://lion137.blogspot.com/2019/02/fundamental-algorithms-iii.html
INFO:__main__:Getting metadata for http://lion137.blogspot.com/2019/02/fundamental-algorithms-iii.html
 37%|███▋      | 62/166 [01:37<01:48,  1.04s/it]INFO:__main__:Requesting https://expensive.chat
INFO:__main__:Getting metadata for https://expensive.chat
ERROR:__main__:Could not get metadata for https://expensive.chat
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 38%|███▊      | 63/166 [01:40<02:34,  1.50s/it]INFO:__main__:Requesting http://www.milliondollarhomepage.com/
INFO:__main__:Getting metadata for http://www.milliondollarhomepage.com
 39%|███▊      | 64/166 [01:43<03:25,  2.01s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_Million_Dollar_Homepage
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_Million_Dollar_Homepage
 39%|███▉      | 65/166 [01:44<02:53,  1.71s/it]INFO:__main__:Requesting https://www.lingscars.com/
INFO:__main__:Getting metadata for https://www.lingscars.com
 40%|███▉      | 66/166 [01:46<02:59,  1.79s/it]INFO:__main__:Requesting https://www.independent.co.uk/life-style/gadgets-and-tech/ling-s-cars-has-one-of-the-best-websites-on-the-internet-a7492386.html
INFO:__main__:Getting metadata for https://www.independent.co.uk/life-style/gadgets-and-tech/ling-s-cars-has-one-of-the-best-websites-on-the-internet-a7492386.html
 40%|████      | 67/166 [01:47<02:24,  1.46s/it]INFO:__main__:Requesting http://iota.show
INFO:__main__:Getting metadata for https://iota.show:443
 41%|████      | 68/166 [01:50<03:18,  2.02s/it]INFO:__main__:Requesting https://highscore.money
INFO:__main__:Getting metadata for https://highscore.money
 42%|████▏     | 69/166 [01:51<02:50,  1.76s/it]INFO:__main__:Requesting https://beautifuldingbats.com/hey-howd-you-do-that/
INFO:__main__:Getting metadata for https://beautifuldingbats.com/hey-howd-you-do-that/
 42%|████▏     | 70/166 [01:52<02:28,  1.55s/it]INFO:__main__:Requesting https://qaz.wtf/u/convert.cgi?text=sending+unicode+characters+for+fun
INFO:__main__:Getting metadata for https://qaz.wtf/u/convert.cgi?text=sending+unicode+characters+for+fun
 43%|████▎     | 71/166 [01:54<02:23,  1.52s/it]INFO:__main__:Requesting https://typenineapp.com
INFO:__main__:Getting metadata for https://typenineapp.com
 43%|████▎     | 72/166 [01:54<01:58,  1.26s/it]INFO:__main__:Requesting https://medium.com/porsager/a-better-iphone-typing-experience-77c6da52131
INFO:__main__:Getting metadata for https://medium.com/porsager/a-better-iphone-typing-experience-77c6da52131
 44%|████▍     | 73/166 [01:55<01:36,  1.04s/it]INFO:__main__:Requesting https://clarity.fm/
INFO:__main__:Getting metadata for https://clarity.fm
 45%|████▍     | 74/166 [01:55<01:12,  1.27it/s]INFO:__main__:Requesting https://earn.com/
INFO:__main__:Getting metadata for https://earn.com
 45%|████▌     | 75/166 [01:55<01:05,  1.40it/s]INFO:__main__:Requesting https://www.crunchbase.com/organization/whale-3
 46%|████▌     | 76/166 [01:56<00:54,  1.66it/s]INFO:__main__:Requesting https://davidwong.fr/FiveMedium/#/
INFO:__main__:Getting metadata for https://davidwong.fr/FiveMedium/#/
ERROR:__main__:Could not get metadata for https://davidwong.fr/FiveMedium/#/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 46%|████▋     | 77/166 [02:00<02:17,  1.55s/it]INFO:__main__:Requesting https://bitchat.bitdb.network
INFO:__main__:Getting metadata for https://bitchat.bitdb.network
 47%|████▋     | 78/166 [02:00<01:44,  1.19s/it]INFO:__main__:Requesting http://immersivemath.com/ila/index.html
INFO:__main__:Getting metadata for http://immersivemath.com/ila/index.html
 48%|████▊     | 79/166 [02:03<02:25,  1.67s/it]INFO:__main__:Requesting http://joshua.smcvt.edu/linearalgebra/
INFO:__main__:Getting metadata for http://joshua.smcvt.edu/linearalgebra/
ERROR:__main__:Could not get metadata for http://joshua.smcvt.edu/linearalgebra/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 48%|████▊     | 80/166 [02:03<01:53,  1.32s/it]INFO:__main__:Requesting http://webwork.maa.org/
INFO:__main__:Getting metadata for http://webwork.maa.org
 49%|████▉     | 81/166 [02:04<01:29,  1.06s/it]INFO:__main__:Requesting https://crastina.se/theres-no-projects-like-side-projects/
INFO:__main__:Getting metadata for https://crastina.se/theres-no-projects-like-side-projects/
 49%|████▉     | 82/166 [02:12<04:44,  3.38s/it]INFO:__main__:Requesting http://quantumgame.io/
INFO:__main__:Getting metadata for http://quantumgame.io
 50%|█████     | 83/166 [02:14<04:02,  2.92s/it]INFO:__main__:Requesting https://github.com/stared/science-based-games-list;
 51%|█████     | 84/166 [02:14<02:51,  2.09s/it]INFO:__main__:Requesting http://p.migdal.pl/interactive-machine-learning-list/
INFO:__main__:Getting metadata for http://p.migdal.pl/interactive-machine-learning-list/
 51%|█████     | 85/166 [02:15<02:07,  1.57s/it]INFO:__main__:Requesting https://ximera.osu.edu/mooculus
INFO:__main__:Getting metadata for https://ximera.osu.edu/mooculus
 52%|█████▏    | 86/166 [02:16<01:48,  1.36s/it]INFO:__main__:Requesting http://pat.perso.ens-lyon.org/M1P1/
INFO:__main__:Getting metadata for http://pat.perso.ens-lyon.org/M1P1/
 52%|█████▏    | 87/166 [02:18<01:59,  1.52s/it]INFO:__main__:Requesting https://openstax.org/
INFO:__main__:Getting metadata for https://openstax.org
 53%|█████▎    | 88/166 [02:19<01:50,  1.42s/it]INFO:__main__:Requesting https://open.umn.edu/opentextbooks/
INFO:__main__:Getting metadata for https://open.umn.edu/opentextbooks/
 54%|█████▎    | 89/166 [02:21<01:57,  1.53s/it]INFO:__main__:Requesting http://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AlgebraTrigIntro.aspx
INFO:__main__:Getting metadata for http://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AlgebraTrigIntro.aspx
 54%|█████▍    | 90/166 [02:22<02:02,  1.61s/it]INFO:__main__:Requesting https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
INFO:__main__:Getting metadata for https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
 55%|█████▍    | 91/166 [02:26<02:47,  2.24s/it]INFO:__main__:Requesting https://github.com/photonlines/Intuitive-Overview-of-Linear-Algebra-Fundamentals
INFO:__main__:Getting metadata for https://github.com/photonlines/Intuitive-Overview-of-Linear-Algebra-Fundamentals
 55%|█████▌    | 92/166 [02:27<02:23,  1.94s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
 56%|█████▌    | 93/166 [02:28<02:01,  1.66s/it]INFO:__main__:Requesting http://treena.org
INFO:__main__:Getting metadata for https://treena.org
 57%|█████▋    | 94/166 [02:29<01:43,  1.44s/it]INFO:__main__:Requesting https://imgur.com/dzidyuV
INFO:__main__:Getting metadata for https://imgur.com/dzidyuV
ERROR:__main__:Could not get metadata for https://imgur.com/dzidyuV
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 57%|█████▋    | 95/166 [02:30<01:31,  1.29s/it]INFO:__main__:Requesting http://abstract.ups.edu/aata/
INFO:__main__:Getting metadata for http://abstract.ups.edu/aata/
 58%|█████▊    | 96/166 [02:33<01:57,  1.68s/it]INFO:__main__:Requesting http://linear.pugetsound.edu/html/fcla.html
INFO:__main__:Getting metadata for http://linear.pugetsound.edu/html/fcla.html
 58%|█████▊    | 97/166 [02:34<01:41,  1.47s/it]INFO:__main__:Requesting https://physicstoday.scitation.org/doi/full/10.1063/1.1768652
INFO:__main__:Getting metadata for https://physicstoday.scitation.org/action/captchaChallenge?redirectUrl=https%3A%2F%2Fphysicstoday.scitation.org%2Fdoi%2Ffull%2F10.1063%2F1.1768652
 59%|█████▉    | 98/166 [02:38<02:27,  2.17s/it]INFO:__main__:Requesting http://www.math.harvard.edu/~elkies/M55a.17/index.html
INFO:__main__:Getting metadata for http://www.math.harvard.edu/~elkies/M55a.17/index.html
ERROR:__main__:Could not get metadata for http://www.math.harvard.edu/~elkies/M55a.17/index.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 60%|█████▉    | 99/166 [02:39<02:06,  1.89s/it]INFO:__main__:Requesting https://mathigon.org/
INFO:__main__:Getting metadata for https://mathigon.org
 60%|██████    | 100/166 [02:39<01:31,  1.39s/it]INFO:__main__:Requesting https://www.euclidea.xyz/
INFO:__main__:Getting metadata for https://www.euclidea.xyz
 61%|██████    | 101/166 [02:40<01:19,  1.22s/it]INFO:__main__:Requesting http://setosa.io/ev/eigenvectors-and-eigenvalues/
INFO:__main__:Getting metadata for http://setosa.io/ev/eigenvectors-and-eigenvalues/
ERROR:__main__:Could not get metadata for http://setosa.io/ev/eigenvectors-and-eigenvalues/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 61%|██████▏   | 102/166 [02:40<01:00,  1.06it/s]INFO:__main__:Requesting https://www.amazon.com/Visual-Group-Theory-Problem-Book/dp/088385757X
INFO:__main__:Getting metadata for https://www.amazon.com/Visual-Group-Theory-Problem-Book/dp/088385757X
 62%|██████▏   | 103/166 [02:47<02:45,  2.62s/it]INFO:__main__:Requesting https://www6.slac.stanford.edu/news/2018-10-15-missing-gamma-ray-blobs-shed-new-light-dark-matter-cosmic-magnetism.aspx
INFO:__main__:Getting metadata for https://www6.slac.stanford.edu/news/2018-10-15-missing-gamma-ray-blobs-shed-new-light-dark-matter-cosmic-magnetism.aspx
 63%|██████▎   | 104/166 [02:48<02:09,  2.10s/it]INFO:__main__:Requesting https://www.failory.com/interview/park-io
INFO:__main__:Getting metadata for https://www.failory.com/interview/park-io
 63%|██████▎   | 105/166 [02:48<01:43,  1.70s/it]INFO:__main__:Requesting https://www.indiehackers.com/podcast/034-mike-carson-of-park-io
INFO:__main__:Getting metadata for https://www.indiehackers.com/podcast/034-mike-carson-of-park-io
ERROR:__main__:Could not get metadata for https://www.indiehackers.com/podcast/034-mike-carson-of-park-io
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 64%|██████▍   | 106/166 [02:50<01:35,  1.59s/it]INFO:__main__:Requesting https://saasclub.io/podcast/million-dollar-saas-mike-carson/
INFO:__main__:Getting metadata for https://saasclub.io/podcast/million-dollar-saas-mike-carson/
 64%|██████▍   | 107/166 [02:50<01:11,  1.21s/it]INFO:__main__:Requesting https://park.io
INFO:__main__:Getting metadata for https://park.io
 65%|██████▌   | 108/166 [02:52<01:22,  1.41s/it]INFO:__main__:Requesting http://www.openculture.com/2015/10/postage-stamps-from-bhutan-that-double-as-playable-vinyl-records.html
INFO:__main__:Getting metadata for http://www.openculture.com/2015/10/postage-stamps-from-bhutan-that-double-as-playable-vinyl-records.html
 66%|██████▌   | 109/166 [02:52<01:02,  1.09s/it]INFO:__main__:Requesting http://www.otherhand.org/home-page/search-and-rescue/the-hunt-for-the-death-valley-germans/
INFO:__main__:Getting metadata for http://www.otherhand.org/home-page/search-and-rescue/the-hunt-for-the-death-valley-germans/
 66%|██████▋   | 110/166 [02:53<01:01,  1.10s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Death_by_GPS
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Death_by_GPS
 67%|██████▋   | 111/166 [02:54<00:53,  1.03it/s]INFO:__main__:Requesting https://www.theguardian.com/australia-news/2018/nov/08/boy-12-feared-missing-after-three-people-found-dead-near-broken-down-vehicle-in-outback
INFO:__main__:Getting metadata for https://www.theguardian.com/australia-news/2018/nov/08/boy-12-feared-missing-after-three-people-found-dead-near-broken-down-vehicle-in-outback
 67%|██████▋   | 112/166 [02:54<00:42,  1.26it/s]INFO:__main__:Requesting https://www.sbs.com.au/news/what-a-tragic-end-German-couple-die-in-northern-territory-outback
 68%|██████▊   | 113/166 [02:56<00:58,  1.10s/it]INFO:__main__:Requesting https://nypost.com/2018/01/11/tourist-dies-hiking-in-australia-outback-heat/
ERROR:__main__:Could not reach https://nypost.com/2018/01/11/tourist-dies-hiking-in-australia-outback-heat/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 69%|██████▊   | 114/166 [02:56<00:42,  1.24it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=a-KUF-xiV5o
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=a-KUF-xiV5o
 69%|██████▉   | 115/166 [02:57<00:43,  1.18it/s]INFO:__main__:Requesting http://www.otherhand.org/home-page/search-and-rescue/searching-for-bill-ewasko/
INFO:__main__:Getting metadata for http://www.otherhand.org/home-page/search-and-rescue/searching-for-bill-ewasko/
 70%|██████▉   | 116/166 [02:59<00:49,  1.02it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Saxon_Switzerland_climbing_region
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Saxon_Switzerland_climbing_region
 70%|███████   | 117/166 [02:59<00:42,  1.14it/s]INFO:__main__:Requesting https://www.nybooks.com/articles/2019/03/07/sophie-taeuber-arp-master-mute-forms/
INFO:__main__:Getting metadata for https://www.nybooks.com/articles/2019/03/07/sophie-taeuber-arp-master-mute-forms/
 71%|███████   | 118/166 [03:00<00:36,  1.33it/s]INFO:__main__:Requesting https://techcrunch.com/2019/02/26/facebook-vs-patreon/
ERROR:__main__:Could not reach https://techcrunch.com/2019/02/26/facebook-vs-patreon/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 72%|███████▏  | 119/166 [03:00<00:27,  1.73it/s]INFO:__main__:Requesting https://liberapay.com/
INFO:__main__:Getting metadata for https://liberapay.com
 72%|███████▏  | 120/166 [03:01<00:37,  1.22it/s]INFO:__main__:Requesting https://www.theatlantic.com/ideas/archive/2018/10/its-not-free-speech-criticize-muhammad-echr-ruled/574174/
INFO:__main__:Getting metadata for https://www.theatlantic.com/ideas/archive/2018/10/its-not-free-speech-criticize-muhammad-echr-ruled/574174/
 73%|███████▎  | 121/166 [03:01<00:29,  1.52it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Freedom_of_speech_by_country
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Freedom_of_speech_by_country
 73%|███████▎  | 122/166 [03:04<00:55,  1.27s/it]INFO:__main__:Requesting https://ipi.media/despite-danish-repeal-blasphemy-laws-still-common-in-europe/
ERROR:__main__:Could not reach https://ipi.media/despite-danish-repeal-blasphemy-laws-still-common-in-europe/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipi.media', port=443): Max retries exceeded with url: /despite-danish-repeal-blasphemy-laws-still-common-in-europe/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ipi.media', port=443): Max retries exceeded with url: /despite-danish-repeal-blasphemy-laws-still-common-in-europe/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
 74%|███████▍  | 123/166 [03:04<00:39,  1.09it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Blasphemy_law
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Blasphemy_law
 75%|███████▍  | 124/166 [03:10<01:34,  2.26s/it]INFO:__main__:Requesting https://www.ris.bka.gv.at/Dokument.wxe?ResultFunctionToken=a6b29d09-cb5f-43d6-a66a-356d138e19bf&Abfrage=Bundesnormen&Kundmachungsorgan=&Index=&Titel=STGB&Gesetzesnummer=&VonArtikel=&BisArtikel=&VonParagraf=188&BisParagraf=&VonAnlage=&BisAnlage=&Typ=&Kundmachungsnummer=&Unterzeichnungsdatum=&FassungVom=28.02.2019&VonInkrafttretedatum=&BisInkrafttretedatum=&VonAusserkrafttretedatum=&BisAusserkrafttretedatum=&NormabschnittnummerKombination=Und&ImRisSeitVonDatum=&ImRisSeitBisDatum=&ImRisSeit=Undefined&ResultPageSize=100&Suchworte=&Dokumentnummer=NOR12029737
INFO:__main__:Getting metadata for https://www.ris.bka.gv.at/Dokument.wxe?ResultFunctionToken=a6b29d09-cb5f-43d6-a66a-356d138e19bf&Abfrage=Bundesnormen&Kundmachungsorgan=&Index=&Titel=STGB&Gesetzesnummer=&VonArtikel=&BisArtikel=&VonParagraf=188&BisParagraf=&VonAnlage=&BisAnlage=&Typ=&Kundmachungsnummer=&Unterzeichnungsdatum=&FassungVom=28.02.2019&VonInkrafttretedatum=&BisInkrafttretedatum=&VonAusserkrafttretedatum=&BisAusserkrafttretedatum=&NormabschnittnummerKombination=Und&ImRisSeitVonDatum=&ImRisSeitBisDatum=&ImRisSeit=Undefined&ResultPageSize=100&Suchworte=&Dokumentnummer=NOR12029737
 75%|███████▌  | 125/166 [03:13<01:48,  2.64s/it]INFO:__main__:Requesting https://www.cnbc.com/2019/01/23/crowd-funding-platform-patreon-announces-it-will-pay-out-half-a-billion-dollars-to-content-creators-in-2019.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2019/01/23/crowd-funding-platform-patreon-announces-it-will-pay-out-half-a-billion-dollars-to-content-creators-in-2019.html
 76%|███████▌  | 126/166 [03:14<01:21,  2.03s/it]INFO:__main__:Requesting https://www.patreon.com/about
INFO:__main__:Getting metadata for https://www.patreon.com/about
 77%|███████▋  | 127/166 [03:15<01:07,  1.73s/it]INFO:__main__:Requesting https://steamcommunity.com/groups/steamworks/announcements/detail/1697191267930157838
INFO:__main__:Getting metadata for https://steamcommunity.com/groups/steamworks/announcements/detail/1697191267930157838
 77%|███████▋  | 128/166 [03:16<01:01,  1.62s/it]INFO:__main__:Requesting https://www.patreon.com/legal
INFO:__main__:Getting metadata for https://www.patreon.com/legal
 78%|███████▊  | 129/166 [03:17<00:48,  1.30s/it]INFO:__main__:Requesting https://www.facebook.com/business/help/1278167592274041
INFO:__main__:Getting metadata for https://www.facebook.com/business/help/1278167592274041
 78%|███████▊  | 130/166 [03:25<01:59,  3.33s/it]INFO:__main__:Requesting https://twitter.com/ericacbarnett/status/1100809443422302208
INFO:__main__:Getting metadata for https://twitter.com/ericacbarnett/status/1100809443422302208
 79%|███████▉  | 131/166 [03:25<01:29,  2.54s/it]INFO:__main__:Requesting https://www.themuse.com/jobs/themuse/director-of-analytics-and-bi
INFO:__main__:Getting metadata for https://www.themuse.com/jobs/themuse/director-of-analytics-and-bi
 80%|███████▉  | 132/166 [03:26<01:05,  1.92s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence
 80%|████████  | 133/166 [03:27<00:49,  1.51s/it]INFO:__main__:Requesting https://www.oreilly.com/library/view/working-effectively-with/0131177052/
INFO:__main__:Getting metadata for https://www.oreilly.com/library/view/working-effectively-with/0131177052/
 81%|████████  | 134/166 [03:27<00:43,  1.35s/it]INFO:__main__:Requesting http://www.throwcase.com/2014/12/21/that-five-monkeys-and-a-banana-story-is-rubbish/
INFO:__main__:Getting metadata for http://www.throwcase.com/2014/12/21/that-five-monkeys-and-a-banana-story-is-rubbish/
 81%|████████▏ | 135/166 [03:28<00:34,  1.11s/it]INFO:__main__:Requesting https://www.forbes.com/sites/davidbressan/2018/03/11/how-century-old-tsunami-stones-saved-lives-in-the-tohoku-earthquake-of-2011/#681622a244fd
INFO:__main__:Getting metadata for https://www.forbes.com/sites/davidbressan/2018/03/11/how-century-old-tsunami-stones-saved-lives-in-the-tohoku-earthquake-of-2011/#681622a244fd
 82%|████████▏ | 136/166 [03:28<00:26,  1.15it/s]INFO:__main__:Requesting http://www.nbcnews.com/id/43018489/ns/world_news-asia_pacific/t/how-one-japanese-village-defied-tsunami/#.XHdyjYhKjAQ
INFO:__main__:Getting metadata for http://www.nbcnews.com/id/43018489/ns/world_news-asia_pacific/t/how-one-japanese-village-defied-tsunami/#.XHdyjYhKjAQ
 83%|████████▎ | 137/166 [03:29<00:26,  1.08it/s]INFO:__main__:Requesting https://skeptics.stackexchange.com/a/6859
INFO:__main__:Getting metadata for https://skeptics.stackexchange.com/questions/6828/was-the-experiment-with-five-monkeys-a-ladder-a-banana-and-a-water-spray-condu/6859#6859
 83%|████████▎ | 138/166 [03:30<00:21,  1.31it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Hundredth_monkey_effect
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Hundredth_monkey_effect
 84%|████████▎ | 139/166 [03:31<00:20,  1.30it/s]INFO:__main__:Requesting https://github.com/ggreer/the_silver_searcher
INFO:__main__:Getting metadata for https://github.com/ggreer/the_silver_searcher
 84%|████████▍ | 140/166 [03:32<00:23,  1.12it/s]INFO:__main__:Requesting https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/
INFO:__main__:Getting metadata for https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/
 85%|████████▍ | 141/166 [03:32<00:21,  1.18it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Second-system_effect
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Second-system_effect
 86%|████████▌ | 142/166 [03:33<00:20,  1.19it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=TQB0KK2rxcw#t=31m0s
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=TQB0KK2rxcw#t=31m0s
 86%|████████▌ | 143/166 [03:34<00:19,  1.17it/s]INFO:__main__:Requesting https://twitter.com/skamille/status/1004735128726376448
INFO:__main__:Getting metadata for https://twitter.com/skamille/status/1004735128726376448
 87%|████████▋ | 144/166 [03:35<00:19,  1.13it/s]INFO:__main__:Requesting https://github.com/davidmarkclements/0x
INFO:__main__:Getting metadata for https://github.com/davidmarkclements/0x
 87%|████████▋ | 145/166 [03:36<00:18,  1.12it/s]INFO:__main__:Requesting https://github.com/mapbox/flamebearer
INFO:__main__:Getting metadata for https://github.com/mapbox/flamebearer
 88%|████████▊ | 146/166 [03:37<00:19,  1.02it/s]INFO:__main__:Requesting https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052
INFO:__main__:Getting metadata for https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052
 89%|████████▊ | 147/166 [03:45<00:58,  3.06s/it]INFO:__main__:Requesting https://codescene.io/showcase
INFO:__main__:Getting metadata for https://codescene.io/showcase
 89%|████████▉ | 148/166 [03:47<00:46,  2.56s/it]INFO:__main__:Requesting https://empear.com/blog/prioritize-technical-debt/
INFO:__main__:Getting metadata for https://empear.com/blog/prioritize-technical-debt/
 90%|████████▉ | 149/166 [03:47<00:33,  1.97s/it]INFO:__main__:Requesting https://pragprog.com/book/atevol/software-design-x-rays
INFO:__main__:Getting metadata for https://pragprog.com/book/atevol/software-design-x-rays
 90%|█████████ | 150/166 [03:49<00:31,  1.95s/it]INFO:__main__:Requesting https://herbertograca.com/2017/08/03/layered-architecture/
ERROR:__main__:Could not reach https://herbertograca.com/2017/08/03/layered-architecture/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 91%|█████████ | 151/166 [03:49<00:21,  1.41s/it]INFO:__main__:Requesting https://linux.die.net/man/1/tree
INFO:__main__:Getting metadata for https://linux.die.net/man/1/tree
 92%|█████████▏| 152/166 [03:51<00:19,  1.38s/it]INFO:__main__:Requesting http://obdurodon.silvrback.com/navigating-a-large-codebase
INFO:__main__:Getting metadata for http://obdurodon.silvrback.com/navigating-a-large-codebase
 92%|█████████▏| 153/166 [03:51<00:14,  1.10s/it]INFO:__main__:Requesting http://wiki.c2.com/?GodClass
INFO:__main__:Getting metadata for http://wiki.c2.com/?GodClass
ERROR:__main__:Could not get metadata for http://wiki.c2.com/?GodClass
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 93%|█████████▎| 154/166 [03:51<00:10,  1.18it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Software_intelligence
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Software_intelligence
 93%|█████████▎| 155/166 [03:52<00:09,  1.21it/s]INFO:__main__:Requesting https://venturebeat.com/2019/02/26/dry-io-wants-to-democratize-software-development-using-ai/
INFO:__main__:Getting metadata for https://venturebeat.com/2019/02/26/dry-io-wants-to-democratize-software-development-using-ai/
 94%|█████████▍| 156/166 [03:52<00:06,  1.48it/s]INFO:__main__:Requesting https://www.gartner.com/doc/3695317/magic-quadrant-enterprise-highproductivity-application
INFO:__main__:Getting metadata for https://www.gartner.com/doc/3695317/magic-quadrant-enterprise-highproductivity-application
 95%|█████████▍| 157/166 [03:53<00:06,  1.39it/s]INFO:__main__:Requesting https://www.g2crowd.com/categories/low-code-development-platforms
INFO:__main__:Getting metadata for https://www.g2crowd.com/categories/low-code-development-platforms
 95%|█████████▌| 158/166 [03:55<00:07,  1.06it/s]INFO:__main__:Requesting http://aima.cs.berkeley.edu/
INFO:__main__:Getting metadata for http://aima.cs.berkeley.edu
 96%|█████████▌| 159/166 [03:55<00:05,  1.19it/s]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=10&swarmCount=1&unitScale=0.2&ownPhysics=false
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=10&swarmCount=1&unitScale=0.2&ownPhysics=false
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=10&swarmCount=1&unitScale=0.2&ownPhysics=false
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 96%|█████████▋| 160/166 [03:58<00:08,  1.42s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/vWreckingBall/
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/vWreckingBall/
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/vWreckingBall/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 97%|█████████▋| 161/166 [04:00<00:07,  1.49s/it]INFO:__main__:Requesting https://www.codingame.com/multiplayer/bot-programming/coders-strike-back
INFO:__main__:Getting metadata for https://www.codingame.com/multiplayer/bot-programming/coders-strike-back
 98%|█████████▊| 162/166 [04:00<00:04,  1.17s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=10&unitScale=0.1&ownPhysics=false
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=10&unitScale=0.1&ownPhysics=false
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=10&unitScale=0.1&ownPhysics=false
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 98%|█████████▊| 163/166 [04:02<00:03,  1.29s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=20&unitScale=0.2&ownPhysics=false
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=20&unitScale=0.2&ownPhysics=false
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=20&unitScale=0.2&ownPhysics=false
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 99%|█████████▉| 164/166 [04:03<00:02,  1.39s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/million-mutas2.png
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/million-mutas2.png
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/million-mutas2.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 99%|█████████▉| 165/166 [07:33<01:03, 63.88s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d.png
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d.png
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
100%|██████████| 166/166 [08:42<00:00, 65.48s/it]
