INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:01<00:37,  1.28s/it]  7%|▋         | 2/30 [00:01<00:30,  1.09s/it] 10%|█         | 3/30 [00:02<00:22,  1.21it/s] 13%|█▎        | 4/30 [00:05<00:42,  1.64s/it] 17%|█▋        | 5/30 [00:06<00:35,  1.44s/it] 20%|██        | 6/30 [00:08<00:38,  1.60s/it] 23%|██▎       | 7/30 [00:09<00:29,  1.27s/it] 27%|██▋       | 8/30 [00:09<00:22,  1.04s/it] 33%|███▎      | 10/30 [00:09<00:14,  1.34it/s] 37%|███▋      | 11/30 [00:11<00:17,  1.07it/s] 43%|████▎     | 13/30 [00:15<00:22,  1.35s/it] 47%|████▋     | 14/30 [00:18<00:28,  1.76s/it] 50%|█████     | 15/30 [00:18<00:19,  1.31s/it] 53%|█████▎    | 16/30 [00:18<00:13,  1.05it/s] 57%|█████▋    | 17/30 [00:19<00:11,  1.10it/s] 60%|██████    | 18/30 [00:20<00:11,  1.03it/s] 70%|███████   | 21/30 [00:21<00:06,  1.30it/s] 77%|███████▋  | 23/30 [00:21<00:03,  1.75it/s] 80%|████████  | 24/30 [00:22<00:02,  2.00it/s] 83%|████████▎ | 25/30 [00:22<00:02,  2.15it/s] 87%|████████▋ | 26/30 [00:26<00:05,  1.42s/it] 90%|█████████ | 27/30 [00:26<00:03,  1.16s/it] 93%|█████████▎| 28/30 [00:27<00:01,  1.10it/s] 97%|█████████▋| 29/30 [00:27<00:00,  1.50it/s]100%|██████████| 30/30 [00:27<00:00,  1.77it/s]
  0%|          | 0/293 [00:00<?, ?it/s]INFO:__main__:Requesting https://www.universityofcalifornia.edu/press-room/uc-terminates-subscriptions-worlds-largest-scientific-publisher-push-open-access-publicly
INFO:__main__:Getting metadata for https://www.universityofcalifornia.edu/press-room/uc-terminates-subscriptions-worlds-largest-scientific-publisher-push-open-access-publicly
  0%|          | 1/293 [00:00<01:15,  3.85it/s]INFO:__main__:Requesting https://www.theguardian.com/science/2012/apr/24/harvard-university-journal-publishers-prices
INFO:__main__:Getting metadata for https://www.theguardian.com/science/2012/apr/24/harvard-university-journal-publishers-prices
  1%|          | 2/293 [00:00<01:28,  3.29it/s]INFO:__main__:Requesting https://www.projekt-deal.de/vertragskundigungen-elsevier-2018/
INFO:__main__:Getting metadata for https://www.projekt-deal.de/vertragskundigungen-elsevier-2018/
  1%|          | 3/293 [00:05<08:30,  1.76s/it]INFO:__main__:Requesting https://www.projekt-deal.de/
INFO:__main__:Getting metadata for https://www.projekt-deal.de
  1%|▏         | 4/293 [00:11<13:25,  2.79s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=pgUA1tluVmE
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=pgUA1tluVmE
  2%|▏         | 5/293 [00:12<10:49,  2.26s/it]INFO:__main__:Requesting https://ucla.app.box.com/v/acct-pdf-AFR-16-17
INFO:__main__:Getting metadata for https://ucla.app.box.com/v/acct-pdf-AFR-16-17
ERROR:__main__:Could not get metadata for https://ucla.app.box.com/v/acct-pdf-AFR-16-17
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  2%|▏         | 6/293 [00:25<26:58,  5.64s/it]INFO:__main__:Requesting https://trends.collegeboard.org/college-pricing
INFO:__main__:Getting metadata for https://trends.collegeboard.org/college-pricing
  2%|▏         | 7/293 [00:26<19:44,  4.14s/it]INFO:__main__:Requesting https://nces.ed.gov/programs/digest/d17/tables/dt17_334.30.asp
INFO:__main__:Getting metadata for https://nces.ed.gov/programs/digest/d17/tables/dt17_334.30.asp
  3%|▎         | 8/293 [00:29<18:53,  3.98s/it]INFO:__main__:Requesting https://nces.ed.gov/programs/digest/d17/tables/dt17_334.10.asp
INFO:__main__:Getting metadata for https://nces.ed.gov/programs/digest/d17/tables/dt17_334.10.asp
  3%|▎         | 9/293 [00:32<17:24,  3.68s/it]INFO:__main__:Requesting https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-private-nonprofit-four-year-institutions
INFO:__main__:Getting metadata for https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-private-nonprofit-four-year-institutions
  3%|▎         | 10/293 [00:33<13:07,  2.78s/it]INFO:__main__:Requesting https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-public-four-year-institution
INFO:__main__:Getting metadata for https://trends.collegeboard.org/college-pricing/figures-tables/average-net-price-over-time-full-time-students-public-four-year-institution
  4%|▍         | 11/293 [00:34<11:07,  2.37s/it]INFO:__main__:Requesting https://chorasimilarity.wordpress.com/2019/02/28/google-translate-helps-the-scholarly-poor/
ERROR:__main__:Could not reach https://chorasimilarity.wordpress.com/2019/02/28/google-translate-helps-the-scholarly-poor/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  4%|▍         | 12/293 [00:35<07:57,  1.70s/it]INFO:__main__:Requesting https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db
INFO:__main__:Getting metadata for https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db
ERROR:__main__:Could not get metadata for https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  4%|▍         | 13/293 [00:36<07:10,  1.54s/it]INFO:__main__:Requesting https://twitter.com/dgmacarthur/status/1028489457803161600?s=09
INFO:__main__:Getting metadata for https://twitter.com/dgmacarthur/status/1028489457803161600?s=09
  5%|▍         | 14/293 [00:37<06:28,  1.39s/it]INFO:__main__:Requesting https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
INFO:__main__:Getting metadata for https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
  5%|▌         | 15/293 [00:37<04:52,  1.05s/it]INFO:__main__:Requesting https://web.archive.org/web/20190209202821/https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
INFO:__main__:Getting metadata for https://web.archive.org/web/20190209202821/https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/uc-and-elsevier/
  5%|▌         | 16/293 [00:38<04:56,  1.07s/it]INFO:__main__:Requesting https://getpolarized.io/2019/01/23/mendeleys-encrypted-repository-is-fundamentally-anti-science.html
INFO:__main__:Getting metadata for https://getpolarized.io/2019/01/23/mendeleys-encrypted-repository-is-fundamentally-anti-science.html
  6%|▌         | 17/293 [00:38<03:54,  1.17it/s]INFO:__main__:Requesting https://www.zotero.org/support/kb/mendeley_import
INFO:__main__:Getting metadata for https://www.zotero.org/support/kb/mendeley_import
  6%|▌         | 18/293 [00:40<04:15,  1.07it/s]INFO:__main__:Requesting https://github.com/retorquere/zotero-better-bibtex
INFO:__main__:Getting metadata for https://github.com/retorquere/zotero-better-bibtex
  6%|▋         | 19/293 [00:40<04:16,  1.07it/s]INFO:__main__:Requesting https://blog.mendeley.com/2019/01/31/the-importance-of-interoperability/
ERROR:__main__:Could not reach https://blog.mendeley.com/2019/01/31/the-importance-of-interoperability/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  7%|▋         | 20/293 [00:41<03:11,  1.42it/s]INFO:__main__:Requesting https://youtu.be/Sdm698P2AkA?t=88
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=Sdm698P2AkA&feature=youtu.be&t=88
  7%|▋         | 21/293 [00:42<03:24,  1.33it/s]INFO:__main__:Requesting https://www.crui.it/archivio-notizie/i-ricercatori-italiani-potranno-beneficiare-dell%E2%80%99accesso-continuo-al-database-sciencedirect-di-elsevie.html
INFO:__main__:Getting metadata for https://www.crui.it/archivio-notizie/i-ricercatori-italiani-potranno-beneficiare-dell%E2%80%99accesso-continuo-al-database-sciencedirect-di-elsevie.html
  8%|▊         | 22/293 [00:45<07:44,  1.71s/it]INFO:__main__:Requesting https://www.nature.com/articles/d41586-019-00492-4
INFO:__main__:Getting metadata for https://www.nature.com/articles/d41586-019-00492-4
  8%|▊         | 23/293 [00:48<08:14,  1.83s/it]INFO:__main__:Requesting https://www.library.ucdavis.edu/uc-elsevier/
INFO:__main__:Getting metadata for https://www.library.ucdavis.edu/uc-elsevier/
  8%|▊         | 24/293 [00:50<08:48,  1.97s/it]INFO:__main__:Requesting https://openscience.com/green-oa-vs-gold-oa-which-one-to-choose/
INFO:__main__:Getting metadata for https://openscience.com/green-oa-vs-gold-oa-which-one-to-choose/
  9%|▊         | 25/293 [00:51<07:52,  1.76s/it]INFO:__main__:Requesting https://escholarship.org
INFO:__main__:Getting metadata for https://escholarship.org
ERROR:__main__:Could not get metadata for https://escholarship.org
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  9%|▉         | 26/293 [00:52<06:11,  1.39s/it]INFO:__main__:Requesting https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/alternative-access-to-articles/
INFO:__main__:Getting metadata for https://osc.universityofcalifornia.edu/open-access-at-uc/publisher-negotiations/alternative-access-to-articles/
  9%|▉         | 27/293 [00:52<04:34,  1.03s/it]INFO:__main__:Requesting http://libgen.io/scimag/index.php?s=archaeology
INFO:__main__:Getting metadata for http://libgen.io/scimag/index.php?s=archaeology
 10%|▉         | 28/293 [01:31<55:09, 12.49s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5832410/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5832410/
 10%|▉         | 29/293 [01:33<41:22,  9.40s/it]INFO:__main__:Requesting https://unpaywall.org/products/extension
INFO:__main__:Getting metadata for https://unpaywall.org/products/extension
ERROR:__main__:Could not get metadata for https://unpaywall.org/products/extension
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 10%|█         | 30/293 [01:34<30:02,  6.86s/it]INFO:__main__:Requesting https://github.com/nfahlgren/scihub_bookmark
INFO:__main__:Getting metadata for https://github.com/nfahlgren/scihub_bookmark
 11%|█         | 31/293 [01:35<21:46,  4.99s/it]INFO:__main__:Requesting https://medium.com/@gagarine/use-sci-hub-with-zotero-as-a-fall-back-pdf-resolver-cf139eb2cea7
INFO:__main__:Getting metadata for https://medium.com/@gagarine/use-sci-hub-with-zotero-as-a-fall-back-pdf-resolver-cf139eb2cea7
 11%|█         | 32/293 [01:35<15:49,  3.64s/it]INFO:__main__:Requesting https://twitter.com/sci_hub/status/731467465973174273
INFO:__main__:Getting metadata for https://twitter.com/sci_hub/status/731467465973174273
 11%|█▏        | 33/293 [01:36<12:20,  2.85s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=vSPUc70z_Cc
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=vSPUc70z_Cc
 12%|█▏        | 34/293 [01:37<09:54,  2.29s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=bzNowvBmR3g
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=bzNowvBmR3g
 12%|█▏        | 35/293 [01:38<08:00,  1.86s/it]INFO:__main__:Requesting http://thecostofknowledge.com
INFO:__main__:Getting metadata for http://thecostofknowledge.com
 12%|█▏        | 36/293 [01:39<06:26,  1.50s/it]INFO:__main__:Requesting https://www.chronicle.com/article/In-Talks-With-Elsevier-UCLA/245311
 13%|█▎        | 37/293 [01:39<04:43,  1.11s/it]INFO:__main__:Requesting https://www.ucpress.edu/openaccess
INFO:__main__:Getting metadata for https://www.ucpress.edu/openaccess
 13%|█▎        | 38/293 [01:42<07:37,  1.79s/it]INFO:__main__:Requesting https://www.arl.org/focus-areas/scholarly-communication/toward-an-open-monograph-ecosystem
INFO:__main__:Getting metadata for https://www.arl.org/focus-areas/scholarly-communication/toward-an-open-monograph-ecosystem
 13%|█▎        | 39/293 [01:44<07:28,  1.77s/it]INFO:__main__:Requesting http://uc-oa.info
INFO:__main__:Getting metadata for https://osc.universityofcalifornia.edu/open-access-at-uc/open-access-policy/
 14%|█▎        | 40/293 [01:45<05:59,  1.42s/it]INFO:__main__:Requesting http://www.lib.berkeley.edu/using-the-libraries/interlibrary-loan
INFO:__main__:Getting metadata for http://www.lib.berkeley.edu/using-the-libraries/interlibrary-loan
 14%|█▍        | 41/293 [01:47<06:35,  1.57s/it]INFO:__main__:Requesting http://tonsky.me/blog/github-redesign/
INFO:__main__:Getting metadata for http://tonsky.me/blog/github-redesign/
 14%|█▍        | 42/293 [01:47<04:45,  1.14s/it]INFO:__main__:Requesting http://tonsky.me/blog/github-redesign/160_files_buttons.png
INFO:__main__:Getting metadata for http://tonsky.me/blog/github-redesign/160_files_buttons.png
ERROR:__main__:Could not get metadata for http://tonsky.me/blog/github-redesign/160_files_buttons.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 15%|█▍        | 43/293 [01:55<13:03,  3.13s/it]INFO:__main__:Requesting https://github.com/robertaboukhalil/aioli/
INFO:__main__:Getting metadata for https://github.com/robertaboukhalil/aioli/
 15%|█▌        | 44/293 [01:56<10:15,  2.47s/it]INFO:__main__:Requesting https://github.com/robertaboukhalil/fastq.bio
INFO:__main__:Getting metadata for https://github.com/robertaboukhalil/fastq.bio
 15%|█▌        | 45/293 [01:56<08:13,  1.99s/it]INFO:__main__:Requesting https://www.tesla.com/blog/35000-tesla-model-3-available-now
INFO:__main__:Getting metadata for https://www.tesla.com/blog/35000-tesla-model-3-available-now
 16%|█▌        | 46/293 [01:57<05:57,  1.45s/it]INFO:__main__:Requesting https://www.tesla.com/drive
INFO:__main__:Getting metadata for https://www.tesla.com/drive
 16%|█▌        | 47/293 [01:57<04:22,  1.07s/it]INFO:__main__:Requesting https://www.cnbc.com/amp/2019/02/21/tesla-refund-and-return-problems-detailed.html
INFO:__main__:Getting metadata for https://www.cnbc.com/amp/2019/02/21/tesla-refund-and-return-problems-detailed.html
 16%|█▋        | 48/293 [01:57<03:46,  1.08it/s]INFO:__main__:Requesting https://forums.tesla.com/forum/forums/why-does-it-take-months-repair-tesla
INFO:__main__:Getting metadata for https://forums.tesla.com/forum/forums/why-does-it-take-months-repair-tesla
 17%|█▋        | 49/293 [01:58<03:46,  1.08it/s]INFO:__main__:Requesting https://teslamotorsclub.com/tmc/threads/repair-time-6-months.112515/
INFO:__main__:Getting metadata for https://teslamotorsclub.com/tmc/threads/repair-time-6-months.112515/
 17%|█▋        | 50/293 [01:59<03:54,  1.04it/s]INFO:__main__:Requesting https://www.driving.co.uk/news/features/tesla-owners-facing-extended-wait-repairs/
INFO:__main__:Getting metadata for https://www.driving.co.uk/news/features/tesla-owners-facing-extended-wait-repairs/
 17%|█▋        | 51/293 [02:03<06:56,  1.72s/it]INFO:__main__:Requesting https://www.sfchronicle.com/business/article/Tesla-owners-fume-about-delays-for-service-13112104.php
INFO:__main__:Getting metadata for https://www.sfchronicle.com/business/article/Tesla-owners-fume-about-delays-for-service-13112104.php
 18%|█▊        | 52/293 [02:03<05:34,  1.39s/it]INFO:__main__:Requesting https://www.libertytax.com/tax-lounge/electric-car-and-vehicle-tax-credit-what-to-know-and-how-to-claim-it/
INFO:__main__:Getting metadata for https://www.libertytax.com/tax-lounge/electric-car-and-vehicle-tax-credit-what-to-know-and-how-to-claim-it/
 18%|█▊        | 53/293 [02:04<04:13,  1.06s/it]INFO:__main__:Requesting https://3.tesla.com/model3/design#battery
INFO:__main__:Getting metadata for https://3.tesla.com/model3/design#battery
 18%|█▊        | 54/293 [02:07<06:24,  1.61s/it]INFO:__main__:Requesting https://www.theverge.com/2019/2/28/18245165/tesla-model-3-price-lower-cost-elon-musk-news
INFO:__main__:Getting metadata for https://www.theverge.com/2019/2/28/18245165/tesla-model-3-price-lower-cost-elon-musk-news
 19%|█▉        | 55/293 [02:07<04:44,  1.19s/it]INFO:__main__:Requesting https://www.paulolyslager.com/decoy-effect-price-tables/
INFO:__main__:Getting metadata for https://www.paulolyslager.com/decoy-effect-price-tables/
 19%|█▉        | 56/293 [02:07<03:34,  1.10it/s]INFO:__main__:Requesting https://darkpatterns.org/
INFO:__main__:Getting metadata for https://darkpatterns.org
 19%|█▉        | 57/293 [02:08<03:26,  1.14it/s]INFO:__main__:Requesting https://www.chevrolet.com/electric/bolt-ev-electric-car
INFO:__main__:Getting metadata for https://www.chevrolet.com/electric/bolt-ev-electric-car
 20%|█▉        | 58/293 [02:10<05:10,  1.32s/it]INFO:__main__:Requesting https://electrek.co/2018/04/14/tesla-battery-degradation-data/
INFO:__main__:Getting metadata for https://electrek.co/2018/04/14/tesla-battery-degradation-data/
 20%|██        | 59/293 [02:11<04:16,  1.10s/it]INFO:__main__:Requesting https://cleanvehiclerebate.org/eng/income-eligibility
INFO:__main__:Getting metadata for https://cleanvehiclerebate.org/eng/income-eligibility
 20%|██        | 60/293 [02:11<03:29,  1.11it/s]INFO:__main__:Requesting https://3.tesla.com/model3/design?redirect=no#battery
INFO:__main__:Getting metadata for https://3.tesla.com/model3/design?redirect=no#battery
 21%|██        | 61/293 [02:14<05:15,  1.36s/it]INFO:__main__:Requesting https://www.businessinsider.com/tesla-to-pay-march-convertible-debt-cash-stock-report-2018-12?r=US&IR=T
INFO:__main__:Getting metadata for https://www.businessinsider.com/tesla-to-pay-march-convertible-debt-cash-stock-report-2018-12?r=US&IR=T
 21%|██        | 62/293 [02:14<03:57,  1.03s/it]INFO:__main__:Requesting https://electrek.co/2018/11/20/tesla-gigafactory-battery-cells-made-cost-advantage-panasonic-lg-report/
INFO:__main__:Getting metadata for https://electrek.co/2018/11/20/tesla-gigafactory-battery-cells-made-cost-advantage-panasonic-lg-report/
 22%|██▏       | 63/293 [02:15<03:39,  1.05it/s]INFO:__main__:Requesting https://insideevs.com/tesla-cheapest-battery-pack-costs/
INFO:__main__:Getting metadata for https://insideevs.com/tesla-cheapest-battery-pack-costs/
 22%|██▏       | 64/293 [02:16<03:35,  1.06it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Tesla_Model_3
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Tesla_Model_3
 22%|██▏       | 65/293 [02:18<05:10,  1.36s/it]INFO:__main__:Requesting https://3.tesla.com/model3/design?redirect=no
INFO:__main__:Getting metadata for https://3.tesla.com/model3/design?redirect=no
 23%|██▎       | 66/293 [02:21<07:04,  1.87s/it]INFO:__main__:Requesting https://mazdasla.com/wp-content/uploads/2018/10/Mazda-Protege-2019-Interior.png
INFO:__main__:Getting metadata for https://mazdasla.com/wp-content/uploads/2018/10/Mazda-Protege-2019-Interior.png
ERROR:__main__:Could not get metadata for https://mazdasla.com/wp-content/uploads/2018/10/Mazda-Protege-2019-Interior.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 23%|██▎       | 67/293 [02:31<16:32,  4.39s/it]INFO:__main__:Requesting http://gtcarlot.com/data/Mazda/Protege/1999/12552040/Dashboard-70858347.html
INFO:__main__:Getting metadata for http://gtcarlot.com/data/Mazda/Protege/1999/12552040/Dashboard-70858347.html
ERROR:__main__:Could not get metadata for http://gtcarlot.com/data/Mazda/Protege/1999/12552040/Dashboard-70858347.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 23%|██▎       | 68/293 [02:32<11:56,  3.18s/it]INFO:__main__:Requesting https://www.stoddard.com/media/catalog/category/IMG_1365.jpg
INFO:__main__:Getting metadata for https://www.stoddard.com/media/catalog/category/IMG_1365.jpg
ERROR:__main__:Could not get metadata for https://www.stoddard.com/media/catalog/category/IMG_1365.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 24%|██▎       | 69/293 [02:34<11:15,  3.01s/it]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2019-02-27/musk-s-tweets-all-but-assure-cash-payout-for-920-million-bond
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=efa5a9a0-3bbd-11e9-9d9c-3ff041da630a&url=L25ld3MvYXJ0aWNsZXMvMjAxOS0wMi0yNy9tdXNrLXMtdHdlZXRzLWFsbC1idXQtYXNzdXJlLWNhc2gtcGF5b3V0LWZvci05MjAtbWlsbGlvbi1ib25k
 24%|██▍       | 70/293 [02:35<08:26,  2.27s/it]INFO:__main__:Requesting http://www.quantwolf.com/calculators/bonddefaultcalc.html
INFO:__main__:Getting metadata for http://www.quantwolf.com/calculators/bonddefaultcalc.html
ERROR:__main__:Could not get metadata for http://www.quantwolf.com/calculators/bonddefaultcalc.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 24%|██▍       | 71/293 [02:35<06:31,  1.76s/it]INFO:__main__:Requesting https://markets.businessinsider.com/bonds/tesla_incdl-notes_201717-25_regs-bond-2025-usu8810laa18
INFO:__main__:Getting metadata for https://markets.businessinsider.com/bonds/tesla_incdl-notes_201717-25_regs-bond-2025-usu8810laa18
ERROR:__main__:Could not get metadata for https://markets.businessinsider.com/bonds/tesla_incdl-notes_201717-25_regs-bond-2025-usu8810laa18
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 25%|██▍       | 72/293 [02:36<05:26,  1.48s/it]INFO:__main__:Requesting https://pagedraw.io/
INFO:__main__:Getting metadata for https://pagedraw.io
 25%|██▍       | 73/293 [02:37<04:57,  1.35s/it]INFO:__main__:Requesting https://medium.com/@gabriel_20625/technical-lessons-from-building-a-compiler-startup-for-3-years-4473405161cd
INFO:__main__:Getting metadata for https://medium.com/@gabriel_20625/technical-lessons-from-building-a-compiler-startup-for-3-years-4473405161cd
 25%|██▌       | 74/293 [02:38<03:59,  1.09s/it]INFO:__main__:Requesting https://medium.com/@jaredpochtar/on-performance-and-software-engineering-44eefa90d46f
INFO:__main__:Getting metadata for https://medium.com/@jaredpochtar/on-performance-and-software-engineering-44eefa90d46f
 26%|██▌       | 75/293 [02:38<03:13,  1.13it/s]INFO:__main__:Requesting https://medium.com/@gabriel_20625/technical-lessons-from-building-a-compiler-startup-for-3-years-4473405161cd*
 26%|██▌       | 76/293 [02:38<02:25,  1.49it/s]INFO:__main__:Requesting https://norvig.com/spell-correct.html
INFO:__main__:Getting metadata for https://norvig.com/spell-correct.html
 26%|██▋       | 77/293 [02:40<03:35,  1.00it/s]INFO:__main__:Requesting https://ourincrediblejourney.tumblr.com/
INFO:__main__:Getting metadata for https://ourincrediblejourney.tumblr.com
 27%|██▋       | 78/293 [02:41<03:25,  1.05it/s]INFO:__main__:Requesting https://youtu.be/hgFkzrqxDcs
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=hgFkzrqxDcs&feature=youtu.be
 27%|██▋       | 79/293 [02:42<03:20,  1.07it/s]INFO:__main__:Requesting https://youtu.be/IpX47gAe150
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=IpX47gAe150&feature=youtu.be
 27%|██▋       | 80/293 [02:43<03:13,  1.10it/s]INFO:__main__:Requesting https://youtu.be/u6uV2X1MGeY
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=u6uV2X1MGeY&feature=youtu.be
 28%|██▊       | 81/293 [02:44<03:11,  1.11it/s]INFO:__main__:Requesting https://youtu.be/s2dYVret-Ck
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=s2dYVret-Ck&feature=youtu.be
 28%|██▊       | 82/293 [02:44<03:03,  1.15it/s]INFO:__main__:Requesting https://youtu.be/X6pL0St6NM4
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=X6pL0St6NM4&feature=youtu.be
 28%|██▊       | 83/293 [02:45<03:06,  1.13it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw/tree/master/src
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw/tree/master/src
 29%|██▊       | 84/293 [02:46<03:02,  1.14it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw/blob/master/package.json
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw/blob/master/package.json
 29%|██▉       | 85/293 [02:47<02:57,  1.17it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw/blob/master/src/editor/edit-page.cjsx
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw/blob/master/src/editor/edit-page.cjsx
 29%|██▉       | 86/293 [02:49<04:17,  1.24s/it]INFO:__main__:Requesting http://www.paulgraham.com/avg.html
INFO:__main__:Getting metadata for http://www.paulgraham.com/avg.html
ERROR:__main__:Could not get metadata for http://www.paulgraham.com/avg.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 30%|██▉       | 87/293 [02:50<03:36,  1.05s/it]INFO:__main__:Requesting https://reactstudio.com
INFO:__main__:Getting metadata for https://reactstudio.com
 30%|███       | 88/293 [02:51<03:34,  1.04s/it]INFO:__main__:Requesting https://www.modulz.app/
INFO:__main__:Getting metadata for https://www.modulz.app
 30%|███       | 89/293 [02:51<02:57,  1.15it/s]INFO:__main__:Requesting https://github.com/Pagedraw/pagedraw
INFO:__main__:Getting metadata for https://github.com/Pagedraw/pagedraw
 31%|███       | 90/293 [02:52<02:58,  1.14it/s]INFO:__main__:Requesting https://hacks.mozilla.org/2019/02/rewriting-a-browser-component-in-rust/
INFO:__main__:Getting metadata for https://hacks.mozilla.org/2019/02/rewriting-a-browser-component-in-rust/
 31%|███       | 91/293 [02:53<02:33,  1.32it/s]INFO:__main__:Requesting https://doc.rust-lang.org/nightly/edition-guide/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.html
INFO:__main__:Getting metadata for https://doc.rust-lang.org/nightly/edition-guide/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.html
 31%|███▏      | 92/293 [02:53<02:42,  1.23it/s]INFO:__main__:Requesting https://www.adaic.org/resources/add_content/standards/05rat/html/Rat-3-2.html
ERROR:__main__:Could not reach https://www.adaic.org/resources/add_content/standards/05rat/html/Rat-3-2.html
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.adaic.org', port=443): Max retries exceeded with url: /resources/add_content/standards/05rat/html/Rat-3-2.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.adaic.org', port=443): Max retries exceeded with url: /resources/add_content/standards/05rat/html/Rat-3-2.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
 32%|███▏      | 93/293 [02:54<02:22,  1.40it/s]INFO:__main__:Requesting https://yoric.github.io/post/rust-typestate/
INFO:__main__:Getting metadata for https://yoric.github.io/post/rust-typestate/
 32%|███▏      | 94/293 [02:54<01:51,  1.78it/s]INFO:__main__:Requesting https://docs.adacore.com/spark2014-docs/html/ug/en/source/concurrency.html#preventing-data-races
INFO:__main__:Getting metadata for https://docs.adacore.com/spark2014-docs/html/ug/en/source/concurrency.html#preventing-data-races
 32%|███▏      | 95/293 [02:59<06:24,  1.94s/it]INFO:__main__:Requesting https://docs.adacore.com/spark2014-docs/html/ug/en/source/co..
 33%|███▎      | 96/293 [03:00<05:00,  1.52s/it]INFO:__main__:Requesting https://en.cppreference.com/w/cpp/container/vector/operator_at
ERROR:__main__:Could not reach https://en.cppreference.com/w/cpp/container/vector/operator_at
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='en.cppreference.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='en.cppreference.com', port=443): Read timed out. (read timeout=6)
 33%|███▎      | 97/293 [03:06<09:36,  2.94s/it]INFO:__main__:Requesting https://docs.microsoft.com/en-us/cpp/standard-library/checked-iterators?view=vs-2017
INFO:__main__:Getting metadata for https://docs.microsoft.com/en-us/cpp/standard-library/checked-iterators?view=vs-2017
ERROR:__main__:Could not get metadata for https://docs.microsoft.com/en-us/cpp/standard-library/checked-iterators?view=vs-2017
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 33%|███▎      | 98/293 [03:07<07:16,  2.24s/it]INFO:__main__:Requesting https://github.com/dropbox/rust-brotli-decompressor/blob/master/src/memory.rs#L71-L76
INFO:__main__:Getting metadata for https://github.com/dropbox/rust-brotli-decompressor/blob/master/src/memory.rs#L71-L76
 34%|███▍      | 99/293 [03:08<05:48,  1.80s/it]INFO:__main__:Requesting https://github.com/dropbox/rust-brotli-decompressor/blob/master/src/memory.rs#L18-L23
INFO:__main__:Getting metadata for https://github.com/dropbox/rust-brotli-decompressor/blob/master/src/memory.rs#L18-L23
 34%|███▍      | 100/293 [03:08<04:51,  1.51s/it]INFO:__main__:Requesting https://www.reddit.com/r/programming/comments/atyzz4/halley_a_lightweight_game_engine_written_in_c14/eh69lz7/
INFO:__main__:Getting metadata for https://www.reddit.com/r/programming/comments/atyzz4/halley_a_lightweight_game_engine_written_in_c14/eh69lz7/
 34%|███▍      | 101/293 [03:09<04:12,  1.32s/it]INFO:__main__:Requesting https://www.reddit.com/r/programming/comments/atyzz4/halley_a_lightweight_game_engine_written_in_c14/eh5kdqv/
INFO:__main__:Getting metadata for https://www.reddit.com/r/programming/comments/atyzz4/halley_a_lightweight_game_engine_written_in_c14/eh5kdqv/
 35%|███▍      | 102/293 [03:10<03:40,  1.15s/it]INFO:__main__:Requesting https://blogs.dropbox.com/tech/2016/06/lossless-compression-with-brotli/
INFO:__main__:Getting metadata for https://blogs.dropbox.com/tech/2016/06/lossless-compression-with-brotli/
ERROR:__main__:Could not get metadata for https://blogs.dropbox.com/tech/2016/06/lossless-compression-with-brotli/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 35%|███▌      | 103/293 [03:11<03:53,  1.23s/it]INFO:__main__:Requesting https://developer.android.com/reference/android/util/FloatMath.html
INFO:__main__:Getting metadata for https://developer.android.com/reference/android/util/FloatMath.html
ERROR:__main__:Could not get metadata for https://developer.android.com/reference/android/util/FloatMath.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 35%|███▌      | 104/293 [03:17<07:44,  2.46s/it]INFO:__main__:Requesting https://github.com/Microsoft/cppwinrt
INFO:__main__:Getting metadata for https://github.com/Microsoft/cppwinrt
 36%|███▌      | 105/293 [03:18<06:19,  2.02s/it]INFO:__main__:Requesting https://blog.rust-lang.org/2015/05/11/traits.html
INFO:__main__:Getting metadata for https://blog.rust-lang.org/2015/05/11/traits.html
 36%|███▌      | 106/293 [03:18<04:35,  1.47s/it]INFO:__main__:Requesting https://blog.mozilla.org/blog/2019/02/28/sharing-our-common-voices-mozilla-releases-the-largest-to-date-public-domain-transcribed-voice-dataset/
INFO:__main__:Getting metadata for https://blog.mozilla.org/blog/2019/02/28/sharing-our-common-voices-mozilla-releases-the-largest-to-date-public-domain-transcribed-voice-dataset/
 37%|███▋      | 107/293 [03:18<03:44,  1.21s/it]INFO:__main__:Requesting http://www.openslr.org/12/
INFO:__main__:Getting metadata for http://www.openslr.org/12/
 37%|███▋      | 108/293 [03:20<03:58,  1.29s/it]INFO:__main__:Requesting https://hacks.mozilla.org/2017/11/a-journey-to-10-word-error-rate/
INFO:__main__:Getting metadata for https://hacks.mozilla.org/2017/11/a-journey-to-10-word-error-rate/
 37%|███▋      | 109/293 [03:20<03:10,  1.04s/it]INFO:__main__:Requesting https://m.youtube.com/watch?v=NMS2VnDveP8
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=NMS2VnDveP8&app=desktop
 38%|███▊      | 110/293 [03:22<03:14,  1.06s/it]INFO:__main__:Requesting http://trumped.com
INFO:__main__:Getting metadata for http://trumped.com
 38%|███▊      | 111/293 [03:22<02:54,  1.04it/s]INFO:__main__:Requesting https://www.sendthemtomir.com/blog/cli-2-factor-authentication
INFO:__main__:Getting metadata for https://www.sendthemtomir.com/blog/cli-2-factor-authentication
 38%|███▊      | 112/293 [03:23<03:05,  1.03s/it]INFO:__main__:Requesting https://support.yubico.com/support/solutions/articles/15000012643-yubikey-manager-cli-ykman-user-manual#ykman_oathwicpwc
INFO:__main__:Getting metadata for https://support.yubico.com/support/solutions/articles/15000012643-yubikey-manager-cli-ykman-user-manual#ykman_oathwicpwc
 39%|███▊      | 113/293 [03:27<05:11,  1.73s/it]INFO:__main__:Requesting https://github.com/w8rbt/oathgen
INFO:__main__:Getting metadata for https://github.com/w8rbt/oathgen
 39%|███▉      | 114/293 [03:28<04:21,  1.46s/it]INFO:__main__:Requesting https://github.com/w8rbt/goathgen
INFO:__main__:Getting metadata for https://github.com/w8rbt/goathgen
 39%|███▉      | 115/293 [03:28<03:39,  1.24s/it]INFO:__main__:Requesting https://github.com/tadfisher/pass-otp
INFO:__main__:Getting metadata for https://github.com/tadfisher/pass-otp
 40%|███▉      | 116/293 [03:29<03:13,  1.09s/it]INFO:__main__:Requesting https://github.com/browserpass/browserpass
INFO:__main__:Getting metadata for https://github.com/browserpass/browserpass
 40%|███▉      | 117/293 [03:30<03:07,  1.07s/it]INFO:__main__:Requesting https://github.com/zeapo/Android-Password-Store
INFO:__main__:Getting metadata for https://github.com/zeapo/Android-Password-Store
 40%|████      | 118/293 [03:31<02:53,  1.01it/s]INFO:__main__:Requesting https://bitbucket.org/devinmartin/keeotp/wiki/Home
INFO:__main__:Getting metadata for https://bitbucket.org/devinmartin/keeotp/wiki/Home
 41%|████      | 119/293 [03:32<03:19,  1.15s/it]INFO:__main__:Requesting https://sourceforge.net/projects/traytotp-kp2/
INFO:__main__:Getting metadata for https://sourceforge.net/projects/traytotp-kp2/
 41%|████      | 120/293 [03:33<03:11,  1.11s/it]INFO:__main__:Requesting https://gitlab.com/elagost/linux-2fa
INFO:__main__:Getting metadata for https://gitlab.com/elagost/linux-2fa
 41%|████▏     | 121/293 [03:34<03:01,  1.06s/it]INFO:__main__:Requesting https://www.clockworkpi.com/
INFO:__main__:Getting metadata for https://www.clockworkpi.com
 42%|████▏     | 122/293 [03:37<04:24,  1.55s/it]INFO:__main__:Requesting https://www.idontplaydarts.com/2011/07/google-totp-two-factor-authentication-for-php/
INFO:__main__:Getting metadata for https://www.idontplaydarts.com/2011/07/google-totp-two-factor-authentication-for-php/
 42%|████▏     | 123/293 [03:38<04:01,  1.42s/it]INFO:__main__:Requesting https://otp.codebro.org
INFO:__main__:Getting metadata for https://otp.codebro.org
 42%|████▏     | 124/293 [03:39<03:09,  1.12s/it]INFO:__main__:Requesting https://pastebin.com/9CLhPiff
INFO:__main__:Getting metadata for https://pastebin.com/9CLhPiff
ERROR:__main__:Could not get metadata for https://pastebin.com/9CLhPiff
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 43%|████▎     | 125/293 [03:39<02:22,  1.18it/s]INFO:__main__:Requesting https://bitbucket.org/blog/meet-bitbucket-pipes-30-ways-to-automate-your-ci-cd-pipeline
 43%|████▎     | 126/293 [03:39<01:46,  1.57it/s]INFO:__main__:Requesting https://phys.org/news/2019-02-million-year-old-worm-superhighway-canada.html
INFO:__main__:Getting metadata for https://phys.org/news/2019-02-million-year-old-worm-superhighway-canada.html
 43%|████▎     | 127/293 [03:39<01:33,  1.78it/s]INFO:__main__:Requesting https://www.mathieustern.com/blog/2018/10/22/l437fjpq58g619vlkm6t1iwhk8s6dr
INFO:__main__:Getting metadata for https://www.mathieustern.com/blog/2018/10/22/l437fjpq58g619vlkm6t1iwhk8s6dr
 44%|████▎     | 128/293 [03:40<01:39,  1.66it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=bUHcCHbgX_o
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=bUHcCHbgX_o
 44%|████▍     | 129/293 [03:41<02:09,  1.27it/s]INFO:__main__:Requesting https://www.studioneat.com/products/neaticekit
INFO:__main__:Getting metadata for https://www.studioneat.com/products/neaticekit
 44%|████▍     | 130/293 [03:42<01:51,  1.47it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=sNohIFrbkXM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=sNohIFrbkXM
 45%|████▍     | 131/293 [03:43<02:05,  1.29it/s]INFO:__main__:Requesting http://www.laurawaller.com/opticsfun/sugarGRINlens.htm
 45%|████▌     | 132/293 [03:43<01:35,  1.69it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Fresnel_lens
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Fresnel_lens
 45%|████▌     | 133/293 [03:44<02:01,  1.32it/s]INFO:__main__:Requesting https://www.medicalnewstoday.com/articles/302550.php
INFO:__main__:Getting metadata for https://www.medicalnewstoday.com/articles/302550.php
 46%|████▌     | 134/293 [03:45<02:13,  1.19it/s]INFO:__main__:Requesting https://www.ted.com/talks/josh_silver_demos_adjustable_liquid_filled_eyeglasses?language=en
INFO:__main__:Getting metadata for https://www.ted.com/talks/josh_silver_demos_adjustable_liquid_filled_eyeglasses?language=en
 46%|████▌     | 135/293 [03:46<02:06,  1.25it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Liquid_mirror_telescope
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Liquid_mirror_telescope
 46%|████▋     | 136/293 [03:47<02:16,  1.15it/s]INFO:__main__:Requesting https://www.imaging-resource.com/news/2015/10/05/this-smartphone-camera-uses-liquid-crystal-and-electrical-currents-to-focus
INFO:__main__:Getting metadata for https://www.imaging-resource.com/news/2015/10/05/this-smartphone-camera-uses-liquid-crystal-and-electrical-currents-to-focus
 47%|████▋     | 137/293 [03:50<04:19,  1.66s/it]INFO:__main__:Requesting https://kottke.org/19/02/a-camera-lens-made-from-an-iceberg
INFO:__main__:Getting metadata for https://kottke.org/19/02/a-camera-lens-made-from-an-iceberg
 47%|████▋     | 138/293 [03:51<03:12,  1.24s/it]INFO:__main__:Requesting https://github.com/dockcross/dockcross#dockcross
INFO:__main__:Getting metadata for https://github.com/dockcross/dockcross#dockcross
 47%|████▋     | 139/293 [03:52<03:04,  1.20s/it]INFO:__main__:Requesting https://servicelab.org/2018/09/13/platform-aware-docker-images/
ERROR:__main__:Could not reach https://servicelab.org/2018/09/13/platform-aware-docker-images/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 48%|████▊     | 140/293 [03:52<02:15,  1.13it/s]INFO:__main__:Requesting https://www.bbc.co.uk/news/technology-47408969
INFO:__main__:Getting metadata for https://www.bbc.co.uk/news/technology-47408969
 48%|████▊     | 141/293 [03:54<03:10,  1.26s/it]INFO:__main__:Requesting https://twitter.com/chrisulmer/status/1099366622329036801
INFO:__main__:Getting metadata for https://twitter.com/chrisulmer/status/1099366622329036801
 48%|████▊     | 142/293 [03:55<02:55,  1.16s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=O13G5A5w5P0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=O13G5A5w5P0
 49%|████▉     | 143/293 [03:56<02:45,  1.11s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=FMNJuSl91qY
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=FMNJuSl91qY
 49%|████▉     | 144/293 [03:57<02:32,  1.03s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/I_know_it_when_I_see_it
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/I_know_it_when_I_see_it
 49%|████▉     | 145/293 [03:57<02:20,  1.05it/s]INFO:__main__:Requesting https://slatestarcodex.com/2019/02/22/rip-culture-war-thread/
INFO:__main__:Getting metadata for https://slatestarcodex.com/2019/02/22/rip-culture-war-thread/
 50%|████▉     | 146/293 [03:59<02:52,  1.17s/it]INFO:__main__:Requesting https://www.eff.org/cyberspace-independence
INFO:__main__:Getting metadata for https://www.eff.org/cyberspace-independence
 50%|█████     | 147/293 [03:59<02:12,  1.10it/s]INFO:__main__:Requesting https://en.wikiquote.org/wiki/John_Gilmore
INFO:__main__:Getting metadata for https://en.wikiquote.org/wiki/John_Gilmore
 51%|█████     | 148/293 [04:00<02:04,  1.17it/s]INFO:__main__:Requesting https://youtube-creators.googleblog.com/2019/02/more-updates-on-our-actions-related-to.html
INFO:__main__:Getting metadata for https://youtube-creators.googleblog.com/2019/02/more-updates-on-our-actions-related-to.html
 51%|█████     | 149/293 [04:00<01:34,  1.53it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=hXfWU_ER3Mg
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=hXfWU_ER3Mg
 51%|█████     | 150/293 [04:01<01:51,  1.28it/s]INFO:__main__:Requesting https://d.tube/
INFO:__main__:Getting metadata for https://d.tube
ERROR:__main__:Could not get metadata for https://d.tube
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 52%|█████▏    | 151/293 [04:02<01:45,  1.35it/s]INFO:__main__:Requesting https://about.d.tube/
INFO:__main__:Getting metadata for https://about.d.tube
 52%|█████▏    | 152/293 [04:03<01:36,  1.46it/s]INFO:__main__:Requesting https://youtu.be/oeI0-ijIotk?t=504
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=oeI0-ijIotk&feature=youtu.be&t=504
 52%|█████▏    | 153/293 [04:04<01:50,  1.27it/s]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/herp-derp-for-youtube/ioomnmgjblnnolpdgdhebainmfbipjoh?hl=en-US
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/herp-derp-for-youtube/ioomnmgjblnnolpdgdhebainmfbipjoh?hl=en-US
 53%|█████▎    | 154/293 [04:04<01:23,  1.66it/s]INFO:__main__:Requesting https://definitions.uslegal.com/c/child-enticement/
INFO:__main__:Getting metadata for https://definitions.uslegal.com/c/child-enticement/
 53%|█████▎    | 155/293 [04:07<03:07,  1.36s/it]INFO:__main__:Requesting https://www.theatlantic.com/national/archive/2013/08/government-knocking-doors-because-google-searches/312599/
INFO:__main__:Getting metadata for https://www.theatlantic.com/national/archive/2013/08/government-knocking-doors-because-google-searches/312599/
 53%|█████▎    | 156/293 [04:08<02:36,  1.14s/it]INFO:__main__:Requesting https://dothemath.ucsd.edu/2012/06/heat-pumps-work-miracles/
INFO:__main__:Getting metadata for https://dothemath.ucsd.edu/2012/06/heat-pumps-work-miracles/
 54%|█████▎    | 157/293 [04:10<03:20,  1.47s/it]INFO:__main__:Requesting https://flair.co/pages/mini-splits-and-window-units
INFO:__main__:Getting metadata for https://flair.co/pages/mini-splits-and-window-units
 54%|█████▍    | 158/293 [04:10<02:31,  1.12s/it]INFO:__main__:Requesting https://www.drawdown.org/solutions/materials/refrigerant-management
INFO:__main__:Getting metadata for https://www.drawdown.org/solutions/materials/refrigerant-management
 54%|█████▍    | 159/293 [04:11<02:19,  1.04s/it]INFO:__main__:Requesting https://www.researchgate.net/publication/270646164_Efficiency_of_a_thermoelectric_heat_pump
 55%|█████▍    | 160/293 [04:11<01:47,  1.23it/s]INFO:__main__:Requesting https://www.energy.gov/eere/buildings/downloads/high-efficiency-solid-state-heat-pump-module
 55%|█████▍    | 161/293 [04:11<01:22,  1.60it/s]INFO:__main__:Requesting https://arpa-e.energy.gov/?q=slick-sheet-project/high-efficiency-solid-state-cooling-technologies
INFO:__main__:Getting metadata for https://arpa-e.energy.gov/?q=slick-sheet-project/high-efficiency-solid-state-cooling-technologies
ERROR:__main__:Could not get metadata for https://arpa-e.energy.gov/?q=slick-sheet-project/high-efficiency-solid-state-cooling-technologies
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 55%|█████▌    | 162/293 [04:14<02:30,  1.15s/it]INFO:__main__:Requesting http://www.johnsonems.com/about/
INFO:__main__:Getting metadata for http://www.johnsonems.com/about/
ERROR:__main__:Could not get metadata for http://www.johnsonems.com/about/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 56%|█████▌    | 163/293 [04:17<03:43,  1.72s/it]INFO:__main__:Requesting http://www.johnsonems.com/benefits/
INFO:__main__:Getting metadata for http://www.johnsonems.com/benefits/
ERROR:__main__:Could not get metadata for http://www.johnsonems.com/benefits/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 56%|█████▌    | 164/293 [04:20<04:27,  2.07s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=F6FUk2E9-68
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=F6FUk2E9-68
 56%|█████▋    | 165/293 [04:21<03:38,  1.70s/it]INFO:__main__:Requesting https://www.energystar.gov/newhomes
INFO:__main__:Getting metadata for https://www.energystar.gov/newhomes
 57%|█████▋    | 166/293 [04:22<03:22,  1.60s/it]INFO:__main__:Requesting https://www.energielabel.nl
INFO:__main__:Getting metadata for https://www.energielabel.nl
 57%|█████▋    | 167/293 [04:25<04:25,  2.11s/it]INFO:__main__:Requesting https://freshome.com/2014/10/09/what-is-a-leed-certified-home/
INFO:__main__:Getting metadata for https://freshome.com/2014/10/09/what-is-a-leed-certified-home/
 57%|█████▋    | 168/293 [04:25<03:12,  1.54s/it]INFO:__main__:Requesting https://www.buildingscience.com/documents/digests/bsd-106-understanding-vapor-barriers
INFO:__main__:Getting metadata for https://www.buildingscience.com/documents/digests/bsd-106-understanding-vapor-barriers
ERROR:__main__:Could not get metadata for https://www.buildingscience.com/documents/digests/bsd-106-understanding-vapor-barriers
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 58%|█████▊    | 169/293 [04:33<07:03,  3.42s/it]INFO:__main__:Requesting https://www.statista.com/statistics/702735/household-natural-gas-prices-in-selected-countries/
INFO:__main__:Getting metadata for https://www.statista.com/statistics/702735/household-natural-gas-prices-in-selected-countries/
 58%|█████▊    | 170/293 [04:34<05:18,  2.59s/it]INFO:__main__:Requesting https://www.buildingscience.com/documents/insights/bsi-001-the-perfect-wall
INFO:__main__:Getting metadata for https://www.buildingscience.com/documents/insights/bsi-001-the-perfect-wall
ERROR:__main__:Could not get metadata for https://www.buildingscience.com/documents/insights/bsi-001-the-perfect-wall
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 58%|█████▊    | 171/293 [04:39<06:47,  3.34s/it]INFO:__main__:Requesting https://greenbuildingadvisor.com
INFO:__main__:Getting metadata for https://www.greenbuildingadvisor.com
 59%|█████▊    | 172/293 [04:40<05:08,  2.55s/it]INFO:__main__:Requesting https://www.architectsjournal.co.uk/buildings/airtightness-blamed-for-health-risks-in-homes/10014252.article
INFO:__main__:Getting metadata for https://www.architectsjournal.co.uk/buildings/airtightness-blamed-for-health-risks-in-homes/10014252.article
 59%|█████▉    | 173/293 [04:43<05:34,  2.79s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=CIcrXut_EFA
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=CIcrXut_EFA
 59%|█████▉    | 174/293 [04:44<04:32,  2.29s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Heat_recovery_ventilation
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Heat_recovery_ventilation
 60%|█████▉    | 175/293 [04:45<03:51,  1.97s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Blower_door
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Blower_door
 60%|██████    | 176/293 [04:47<03:25,  1.75s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Cogeneration
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Cogeneration
 60%|██████    | 177/293 [04:48<03:14,  1.67s/it]INFO:__main__:Requesting https://www.withouthotair.com/c21/page_152.shtml
INFO:__main__:Getting metadata for https://www.withouthotair.com/c21/page_152.shtml
ERROR:__main__:Could not get metadata for https://www.withouthotair.com/c21/page_152.shtml
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 61%|██████    | 178/293 [04:51<03:46,  1.97s/it]INFO:__main__:Requesting https://www.google.com/amp/s/amp.theguardian.com/cities/2017/nov/16/japan-reusable-housing-revolution
INFO:__main__:Getting metadata for https://www.theguardian.com/cities/2017/nov/16/japan-reusable-housing-revolution
 61%|██████    | 179/293 [04:52<03:13,  1.70s/it]INFO:__main__:Requesting https://www.bbc.com/news/uk-england-london-10645700
INFO:__main__:Getting metadata for https://www.bbc.com/news/uk-england-london-10645700
 61%|██████▏   | 180/293 [04:53<03:02,  1.61s/it]INFO:__main__:Requesting https://www.bgs.ac.uk/discoveringgeology/hazards/earthquakes/uk.html
INFO:__main__:Getting metadata for https://www.bgs.ac.uk/discoveringgeology/hazards/earthquakes/uk.html
 62%|██████▏   | 181/293 [04:57<03:57,  2.12s/it]INFO:__main__:Requesting https://www.theguardian.com/travel/2013/jul/27/history-of-englands-forests
INFO:__main__:Getting metadata for https://www.theguardian.com/travel/2013/jul/27/history-of-englands-forests
 62%|██████▏   | 182/293 [04:57<03:04,  1.66s/it]INFO:__main__:Requesting https://www.demilec.com/
INFO:__main__:Getting metadata for https://www.demilec.com
 62%|██████▏   | 183/293 [05:00<03:26,  1.88s/it]INFO:__main__:Requesting http://renewability.com/#learn-more
INFO:__main__:Getting metadata for http://renewability.com/#learn-more
 63%|██████▎   | 184/293 [05:00<02:34,  1.42s/it]INFO:__main__:Requesting https://www.energy.gov/energysaver/water-heating/drain-water-heat-recovery
 63%|██████▎   | 185/293 [05:00<01:52,  1.04s/it]INFO:__main__:Requesting https://www.energystar.gov/about/federal_tax_credits/air_source_heat_pumps
INFO:__main__:Getting metadata for https://www.energystar.gov/about/federal_tax_credits/air_source_heat_pumps
 63%|██████▎   | 186/293 [05:01<01:32,  1.15it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Joule–Thomson_effect
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Joule%E2%80%93Thomson_effect
 64%|██████▍   | 187/293 [05:02<01:45,  1.00it/s]INFO:__main__:Requesting https://www.thisoldhouse.com/watch/jamestown-net-zero-house
INFO:__main__:Getting metadata for https://www.thisoldhouse.com/watch/jamestown-net-zero-house
ERROR:__main__:Could not get metadata for https://www.thisoldhouse.com/watch/jamestown-net-zero-house
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 64%|██████▍   | 188/293 [05:02<01:33,  1.13it/s]INFO:__main__:Requesting https://www.youtube.com/user/MattRisinger
INFO:__main__:Getting metadata for https://www.youtube.com/user/MattRisinger
 65%|██████▍   | 189/293 [05:05<02:30,  1.45s/it]INFO:__main__:Requesting https://dandelionenergy.com/
INFO:__main__:Getting metadata for https://dandelionenergy.com
 65%|██████▍   | 190/293 [05:06<02:00,  1.17s/it]INFO:__main__:Requesting https://www.rheem.com/innovations/innovation_residential/integrated_systems/
INFO:__main__:Getting metadata for https://www.rheem.com/innovations/innovation_residential/integrated_systems/
 65%|██████▌   | 191/293 [05:10<03:44,  2.20s/it]INFO:__main__:Requesting https://techcrunch.com/2011/06/12/air-conditioning-water-heater/
ERROR:__main__:Could not reach https://techcrunch.com/2011/06/12/air-conditioning-water-heater/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 66%|██████▌   | 192/293 [05:10<02:39,  1.58s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Clothes_dryer#Heat_pump_dryers
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Clothes_dryer#Heat_pump_dryers
 66%|██████▌   | 193/293 [05:12<02:21,  1.42s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Absorption_refrigerator
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Absorption_refrigerator
 66%|██████▌   | 194/293 [05:12<01:55,  1.16s/it]INFO:__main__:Requesting https://begriffs.com/posts/2019-02-21-browsing-remote-git.html
INFO:__main__:Getting metadata for https://begriffs.com/posts/2019-02-21-browsing-remote-git.html
 67%|██████▋   | 195/293 [05:13<01:32,  1.06it/s]INFO:__main__:Requesting https://github.com/ros-infrastructure/rosdistro/tree/master/src/rosdistro/manifest_provider
INFO:__main__:Getting metadata for https://github.com/ros-infrastructure/rosdistro/tree/master/src/rosdistro/manifest_provider
 67%|██████▋   | 196/293 [05:13<01:22,  1.17it/s]INFO:__main__:Requesting https://github.com/ros-infrastructure/rosinstall_generator/blob/master/src/rosinstall_generator/distro.py#L144
INFO:__main__:Getting metadata for https://github.com/ros-infrastructure/rosinstall_generator/blob/master/src/rosinstall_generator/distro.py#L144
 67%|██████▋   | 197/293 [05:14<01:21,  1.18it/s]INFO:__main__:Requesting https://github.com/user/repo`
 68%|██████▊   | 198/293 [05:14<01:00,  1.58it/s]INFO:__main__:Requesting https://github.com/rigetti/quilc
INFO:__main__:Getting metadata for https://github.com/rigetti/quilc
 68%|██████▊   | 199/293 [05:15<01:05,  1.43it/s]INFO:__main__:Requesting https://medium.com/qiskit/how-to-turn-on-your-quantum-computer-fba0a4152d92
INFO:__main__:Getting metadata for https://medium.com/qiskit/how-to-turn-on-your-quantum-computer-fba0a4152d92
 68%|██████▊   | 200/293 [05:16<01:02,  1.50it/s]INFO:__main__:Requesting https://rigetti.com/qcs
INFO:__main__:Getting metadata for https://rigetti.com/qcs
 69%|██████▊   | 201/293 [05:16<00:48,  1.88it/s]INFO:__main__:Requesting https://github.com/cosmos72/gomacro#gomacro---interactive-go-interpreter-and-debugger-with-generics-and-macros
INFO:__main__:Getting metadata for https://github.com/cosmos72/gomacro#gomacro---interactive-go-interpreter-and-debugger-with-generics-and-macros
 69%|██████▉   | 202/293 [05:17<01:00,  1.51it/s]INFO:__main__:Requesting https://golang.org/doc/faq#implements_interface
INFO:__main__:Getting metadata for https://golang.org/doc/faq#implements_interface
 69%|██████▉   | 203/293 [05:17<00:53,  1.68it/s]INFO:__main__:Requesting https://github.com/golang/go/issues/15292#issuecomment-210085246
INFO:__main__:Getting metadata for https://github.com/golang/go/issues/15292#issuecomment-210085246
 70%|██████▉   | 204/293 [05:22<02:36,  1.76s/it]INFO:__main__:Requesting https://media.ccc.de/v/35c3-9783-the_mars_rover_on-board_computer
INFO:__main__:Getting metadata for https://media.ccc.de/v/35c3-9783-the_mars_rover_on-board_computer
 70%|██████▉   | 205/293 [05:23<02:25,  1.65s/it]INFO:__main__:Requesting https://dlang.org/spec/template.html
INFO:__main__:Getting metadata for https://dlang.org/spec/template.html
 70%|███████   | 206/293 [05:25<02:23,  1.65s/it]INFO:__main__:Requesting https://tour.dlang.org/tour/en/basics/templates
INFO:__main__:Getting metadata for https://tour.dlang.org/tour/en/basics/templates
 71%|███████   | 207/293 [05:26<02:09,  1.50s/it]INFO:__main__:Requesting https://dlang.org/articles/templates-revisited.html
INFO:__main__:Getting metadata for https://dlang.org/articles/templates-revisited.html
 71%|███████   | 208/293 [05:27<02:01,  1.42s/it]INFO:__main__:Requesting https://www.jetbrains.com/help/go/debugging-code.html#924cf9d3
INFO:__main__:Getting metadata for https://www.jetbrains.com/help/go/debugging-code.html#924cf9d3
 71%|███████▏  | 209/293 [05:29<02:00,  1.44s/it]INFO:__main__:Requesting https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=query
INFO:__main__:Getting metadata for https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=query
 72%|███████▏  | 210/293 [05:30<01:48,  1.30s/it]INFO:__main__:Requesting https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=plaintext
INFO:__main__:Getting metadata for https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=plaintext
 72%|███████▏  | 211/293 [05:31<01:39,  1.21s/it]INFO:__main__:Requesting https://www.quora.com/Is-he-looses-an-arrow-grammatically-correct
INFO:__main__:Getting metadata for https://www.quora.com/Is-he-looses-an-arrow-grammatically-correct
 72%|███████▏  | 212/293 [05:33<02:14,  1.66s/it]INFO:__main__:Requesting https://golang.org/doc/devel/release.html
INFO:__main__:Getting metadata for https://golang.org/doc/devel/release.html
 73%|███████▎  | 213/293 [05:34<01:39,  1.24s/it]INFO:__main__:Requesting https://github.com/golang/go/commit/d72c550f1c7e13c323f4507b57d741ed00f0b0cd
INFO:__main__:Getting metadata for https://github.com/golang/go/commit/d72c550f1c7e13c323f4507b57d741ed00f0b0cd
 73%|███████▎  | 214/293 [05:34<01:28,  1.12s/it]INFO:__main__:Requesting https://cyclingtips.com/2019/02/did-strava-copy-its-mobile-route-builder-from-another-app/
INFO:__main__:Getting metadata for https://cyclingtips.com/2019/02/did-strava-copy-its-mobile-route-builder-from-another-app/
 73%|███████▎  | 215/293 [05:37<01:59,  1.53s/it]INFO:__main__:Requesting http://footpathapp.com
INFO:__main__:Getting metadata for https://footpathapp.com
 74%|███████▎  | 216/293 [05:37<01:27,  1.13s/it]INFO:__main__:Requesting https://techcrunch.com/2016/08/02/silicon-copy/
ERROR:__main__:Could not reach https://techcrunch.com/2016/08/02/silicon-copy/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 74%|███████▍  | 217/293 [05:37<01:02,  1.21it/s]INFO:__main__:Requesting https://twitter.com/iamnunocaldeira/status/1101105269793308673
INFO:__main__:Getting metadata for https://twitter.com/iamnunocaldeira/status/1101105269793308673
 74%|███████▍  | 218/293 [05:38<01:02,  1.20it/s]INFO:__main__:Requesting https://www.wnycstudios.org/story/the_buried_bodies_case
INFO:__main__:Getting metadata for https://www.wnycstudios.org/story/the_buried_bodies_case
 75%|███████▍  | 219/293 [05:38<00:53,  1.39it/s]INFO:__main__:Requesting https://footpathapp.com/privacy
INFO:__main__:Getting metadata for https://footpathapp.com/privacy/
 75%|███████▌  | 220/293 [05:39<00:42,  1.72it/s]INFO:__main__:Requesting https://www.ip2location.com/demo/12.131.20.242
INFO:__main__:Getting metadata for https://www.ip2location.com/demo/12.131.20.242
 75%|███████▌  | 221/293 [05:39<00:37,  1.94it/s]INFO:__main__:Requesting https://www.maxmind.com/en/geoip-demo
INFO:__main__:Getting metadata for https://www.maxmind.com/en/geoip-demo
 76%|███████▌  | 222/293 [05:40<00:49,  1.43it/s]INFO:__main__:Requesting http://disq.us/p/202igai
INFO:__main__:Getting metadata for https://cyclingtips.com/2019/02/did-strava-copy-its-mobile-route-builder-from-another-app/#comment-4357784826
 76%|███████▌  | 223/293 [05:43<01:27,  1.25s/it]INFO:__main__:Requesting https://www.gmap-pedometer.com/
INFO:__main__:Getting metadata for https://www.gmap-pedometer.com
 76%|███████▋  | 224/293 [05:43<01:15,  1.09s/it]INFO:__main__:Requesting https://pando.com/2012/02/26/steve-jobs-was-right-dropbox-is-a-feature-not-a-product/
INFO:__main__:Getting metadata for https://pando.com/2012/02/26/steve-jobs-was-right-dropbox-is-a-feature-not-a-product/
 77%|███████▋  | 225/293 [05:45<01:12,  1.07s/it]INFO:__main__:Requesting https://www.maps.ie/map-my-route/
 77%|███████▋  | 226/293 [05:45<00:56,  1.18it/s]INFO:__main__:Requesting https://support.google.com/mymaps/answer/3433053
INFO:__main__:Getting metadata for https://support.google.com/mymaps/answer/3433053
 77%|███████▋  | 227/293 [05:46<00:56,  1.17it/s]INFO:__main__:Requesting https://www.hive.co/l/blog-job-feb-26
INFO:__main__:Getting metadata for http://app.hive.co/l/blog-job-feb-26
ERROR:__main__:Could not get metadata for http://app.hive.co/l/blog-job-feb-26
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 78%|███████▊  | 228/293 [05:46<00:52,  1.23it/s]INFO:__main__:Requesting https://www.solipsys.co.uk/new/TheOtherWrappingTheEarthProblem.html?sb27h
INFO:__main__:Getting metadata for https://www.solipsys.co.uk/new/TheOtherWrappingTheEarthProblem.html?sb27h
 78%|███████▊  | 229/293 [05:50<01:41,  1.58s/it]INFO:__main__:Requesting https://xref.com/
INFO:__main__:Getting metadata for https://xref.com
 78%|███████▊  | 230/293 [05:52<01:57,  1.86s/it]INFO:__main__:Requesting https://workgrades.com
INFO:__main__:Getting metadata for https://workgrades.com
ERROR:__main__:Could not get metadata for https://workgrades.com
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 79%|███████▉  | 231/293 [05:53<01:38,  1.59s/it]INFO:__main__:Requesting https://www.searchlight.ai
INFO:__main__:Getting metadata for https://www.searchlight.ai
ERROR:__main__:Could not get metadata for https://www.searchlight.ai
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 79%|███████▉  | 232/293 [05:54<01:24,  1.38s/it]INFO:__main__:Requesting https://ai.googleblog.com/2019/02/long-range-robotic-navigation-via.html
INFO:__main__:Getting metadata for https://ai.googleblog.com/2019/02/long-range-robotic-navigation-via.html
 80%|███████▉  | 233/293 [05:54<01:03,  1.06s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=hGY3uBHVVr4
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=hGY3uBHVVr4
 80%|███████▉  | 234/293 [05:55<01:00,  1.03s/it]INFO:__main__:Requesting https://github.com/kanaka/mal/blob/master/process/guide.md
INFO:__main__:Getting metadata for https://github.com/kanaka/mal/blob/master/process/guide.md
 80%|████████  | 235/293 [05:56<00:58,  1.00s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/ELIZA
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/ELIZA
 81%|████████  | 236/293 [05:57<00:58,  1.02s/it]INFO:__main__:Requesting https://github.com/norvig/paip-lisp/blob/master/README.md
INFO:__main__:Getting metadata for https://github.com/norvig/paip-lisp/blob/master/README.md
 81%|████████  | 237/293 [05:58<00:52,  1.07it/s]INFO:__main__:Requesting https://www.non-kinetic-effects.co.uk/blog/2019/01/21/MAL-2
INFO:__main__:Getting metadata for https://www.non-kinetic-effects.co.uk/blog/2019/01/21/MAL-2
 81%|████████  | 238/293 [05:58<00:40,  1.34it/s]INFO:__main__:Requesting http://web.sonoma.edu/users/l/luvisi/
INFO:__main__:Getting metadata for http://web.sonoma.edu/users/l/luvisi/
ERROR:__main__:Could not get metadata for http://web.sonoma.edu/users/l/luvisi/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 82%|████████▏ | 239/293 [05:59<00:37,  1.43it/s]INFO:__main__:Requesting https://github.com/krig/LISP
INFO:__main__:Getting metadata for https://github.com/krig/LISP
 82%|████████▏ | 240/293 [06:00<00:38,  1.37it/s]INFO:__main__:Requesting https://github.com/rigetti/qvm
INFO:__main__:Getting metadata for https://github.com/rigetti/qvm
 82%|████████▏ | 241/293 [06:01<00:40,  1.28it/s]INFO:__main__:Requesting https://discovery.princeton.edu/2018/12/02/beyond-einstein-physicists-find-surprising-connections-in-the-cosmos/
INFO:__main__:Getting metadata for https://discovery.princeton.edu/2018/12/02/beyond-einstein-physicists-find-surprising-connections-in-the-cosmos/
 83%|████████▎ | 242/293 [06:02<00:48,  1.04it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=3HYw6vPR9qU
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=3HYw6vPR9qU
 83%|████████▎ | 243/293 [06:03<00:49,  1.01it/s]INFO:__main__:Requesting https://arxiv.org/abs/1801.08160
INFO:__main__:Getting metadata for https://arxiv.org/abs/1801.08160
 83%|████████▎ | 244/293 [06:04<00:52,  1.08s/it]INFO:__main__:Requesting https://www.quora.com/What-percentage-of-subatomic-particles-are-quantum-entangled
INFO:__main__:Getting metadata for https://www.quora.com/What-percentage-of-subatomic-particles-are-quantum-entangled
 84%|████████▎ | 245/293 [06:07<01:12,  1.51s/it]INFO:__main__:Requesting https://physics.stackexchange.com/questions/251385/an-explanation-of-hawking-radiation
INFO:__main__:Getting metadata for https://physics.stackexchange.com/questions/251385/an-explanation-of-hawking-radiation
 84%|████████▍ | 246/293 [06:07<00:54,  1.17s/it]INFO:__main__:Requesting https://profmattstrassler.com/articles-and-posts/particle-physics-basics/virtual-particles-what-are-they/
ERROR:__main__:Could not reach https://profmattstrassler.com/articles-and-posts/particle-physics-basics/virtual-particles-what-are-they/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 84%|████████▍ | 247/293 [06:08<00:39,  1.16it/s]INFO:__main__:Requesting https://blog.rust-lang.org/2019/02/28/Rust-1.33.0.html
INFO:__main__:Getting metadata for https://blog.rust-lang.org/2019/02/28/Rust-1.33.0.html
 85%|████████▍ | 248/293 [06:08<00:29,  1.54it/s]INFO:__main__:Requesting https://github.com/rust-lang/rust/pull/56568
INFO:__main__:Getting metadata for https://github.com/rust-lang/rust/pull/56568
 85%|████████▍ | 249/293 [06:12<01:11,  1.62s/it]INFO:__main__:Requesting https://github.com/rust-lang/rust/issues/49150
INFO:__main__:Getting metadata for https://github.com/rust-lang/rust/issues/49150
 85%|████████▌ | 250/293 [06:15<01:36,  2.25s/it]INFO:__main__:Requesting https://github.com/rust-lang-nursery/reference/blob/master/src/items/functions.md#const-functions
INFO:__main__:Getting metadata for https://github.com/rust-lang-nursery/reference/blob/master/src/items/functions.md#const-functions
 86%|████████▌ | 251/293 [06:16<01:15,  1.80s/it]INFO:__main__:Requesting https://newrustacean.com/show_notes/news/rust_1_31/part_2/index.html
INFO:__main__:Getting metadata for https://newrustacean.com/show_notes/news/rust_1_31/part_2/index.html
 86%|████████▌ | 252/293 [06:17<01:03,  1.54s/it]INFO:__main__:Requesting http://b.atch.se/posts/non-constant-constant-expressions/
INFO:__main__:Getting metadata for http://b.atch.se/posts/non-constant-constant-expressions/
 86%|████████▋ | 253/293 [06:19<01:04,  1.62s/it]INFO:__main__:Requesting http://wg21.link/p1073r3
INFO:__main__:Getting metadata for http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1073r3.html
 87%|████████▋ | 254/293 [06:23<01:34,  2.43s/it]INFO:__main__:Requesting https://thanks.rust-lang.org/rust/1.33.0
INFO:__main__:Getting metadata for https://thanks.rust-lang.org/rust/1.33.0
 87%|████████▋ | 255/293 [06:25<01:27,  2.30s/it]INFO:__main__:Requesting http://arewegameyet.com
INFO:__main__:Getting metadata for http://arewegameyet.com
 87%|████████▋ | 256/293 [06:28<01:26,  2.35s/it]INFO:__main__:Requesting http://arewemetayet.com/
INFO:__main__:Getting metadata for http://arewemetayet.com
ERROR:__main__:Could not get metadata for http://arewemetayet.com
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 88%|████████▊ | 257/293 [06:28<01:04,  1.80s/it]INFO:__main__:Requesting http://www.arewewebyet.org/
INFO:__main__:Getting metadata for http://www.arewewebyet.org
 88%|████████▊ | 258/293 [06:29<00:48,  1.40s/it]INFO:__main__:Requesting https://areweasyncyet.rs/
INFO:__main__:Getting metadata for https://areweasyncyet.rs
 88%|████████▊ | 259/293 [06:29<00:40,  1.20s/it]INFO:__main__:Requesting https://docs.rust-embedded.org/
INFO:__main__:Getting metadata for https://docs.rust-embedded.org
 89%|████████▊ | 260/293 [06:30<00:31,  1.03it/s]INFO:__main__:Requesting https://github.com/rust-embedded/wg/issues/15
INFO:__main__:Getting metadata for https://github.com/rust-embedded/wg/issues/15
 89%|████████▉ | 261/293 [06:32<00:40,  1.28s/it]INFO:__main__:Requesting https://wiki.mozilla.org/Areweyet
INFO:__main__:Getting metadata for https://wiki.mozilla.org/Areweyet
 89%|████████▉ | 262/293 [06:33<00:40,  1.29s/it]INFO:__main__:Requesting https://areweasyncyet.rs
INFO:__main__:Getting metadata for https://areweasyncyet.rs
 90%|████████▉ | 263/293 [06:34<00:31,  1.06s/it]INFO:__main__:Requesting https://www.bloombergquint.com/businessweek/america-s-cities-are-running-on-software-from-the-80s
INFO:__main__:Getting metadata for https://www.bloombergquint.com/businessweek/america-s-cities-are-running-on-software-from-the-80s
 90%|█████████ | 264/293 [06:34<00:23,  1.22it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/The_Story_of_Mel
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/The_Story_of_Mel
 90%|█████████ | 265/293 [06:34<00:20,  1.35it/s]INFO:__main__:Requesting https://mentalhealthdaily.com/2015/02/18/at-what-age-is-the-brain-fully-developed/
INFO:__main__:Getting metadata for https://mentalhealthdaily.com/2015/02/18/at-what-age-is-the-brain-fully-developed/
 91%|█████████ | 266/293 [06:36<00:26,  1.03it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Typeahead
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Typeahead
 91%|█████████ | 267/293 [06:37<00:23,  1.08it/s]INFO:__main__:Requesting https://images.hdsydsvenskan.se/980x588/KoHYjzCi_hdzfPAF4xY_j0PR9ls.jpg
INFO:__main__:Getting metadata for https://images.hdsydsvenskan.se/980x588/KoHYjzCi_hdzfPAF4xY_j0PR9ls.jpg
ERROR:__main__:Could not get metadata for https://images.hdsydsvenskan.se/980x588/KoHYjzCi_hdzfPAF4xY_j0PR9ls.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 91%|█████████▏| 268/293 [06:38<00:27,  1.11s/it]INFO:__main__:Requesting https://www.twincities.com/2019/02/14/mn-dmv-mnlars-report-department-driver-vehicle-services/
INFO:__main__:Getting metadata for https://www.twincities.com/2019/02/14/mn-dmv-mnlars-report-department-driver-vehicle-services/
 92%|█████████▏| 269/293 [06:39<00:27,  1.14s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Phoenix_pay_system
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Phoenix_pay_system
 92%|█████████▏| 270/293 [06:40<00:22,  1.03it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Clock_of_the_Long_Now
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Clock_of_the_Long_Now
 92%|█████████▏| 271/293 [06:41<00:21,  1.04it/s]INFO:__main__:Requesting https://www.comeetie.fr/galerie/BatiParis/#12/48.8589/2.3491
INFO:__main__:Getting metadata for https://www.comeetie.fr/galerie/BatiParis/#12/48.8589/2.3491
 93%|█████████▎| 272/293 [06:43<00:29,  1.42s/it]INFO:__main__:Requesting https://www.cnn.com/2016/05/26/us/pentagon-floppy-disks-nuclear/index.html
INFO:__main__:Getting metadata for https://www.cnn.com/2016/05/26/us/pentagon-floppy-disks-nuclear/index.html
 93%|█████████▎| 273/293 [06:45<00:28,  1.45s/it]INFO:__main__:Requesting https://simple.m.wikipedia.org/wiki/Sustainability
INFO:__main__:Getting metadata for https://simple.m.wikipedia.org/wiki/Sustainability
 94%|█████████▎| 274/293 [06:46<00:23,  1.24s/it]INFO:__main__:Requesting https://www.cbsnews.com/news/mta-why-has-the-nyc-subway-gone-off-the-rails-60-minutes/
INFO:__main__:Getting metadata for https://www.cbsnews.com/news/mta-why-has-the-nyc-subway-gone-off-the-rails-60-minutes/
 94%|█████████▍| 275/293 [06:46<00:18,  1.03s/it]INFO:__main__:Requesting https://twitter.com/dongho_chang/status/960645535311937538
INFO:__main__:Getting metadata for https://twitter.com/dongho_chang/status/960645535311937538
 94%|█████████▍| 276/293 [06:47<00:15,  1.10it/s]INFO:__main__:Requesting https://beta.nyc/
INFO:__main__:Getting metadata for https://beta.nyc
ERROR:__main__:Could not get metadata for https://beta.nyc
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 95%|█████████▍| 277/293 [06:48<00:13,  1.20it/s]INFO:__main__:Requesting https://www.tandfonline.com/doi/full/10.1080/02791072.2019.1580804
INFO:__main__:Getting metadata for https://www.tandfonline.com/doi/full/10.1080/02791072.2019.1580804
 95%|█████████▍| 278/293 [06:50<00:18,  1.26s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Active_placebo
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Active_placebo
 95%|█████████▌| 279/293 [06:51<00:15,  1.10s/it]INFO:__main__:Requesting https://branchfree.org/2019/02/28/paper-hyperscan-a-fast-multi-pattern-regex-matcher-for-modern-cpus/
ERROR:__main__:Could not reach https://branchfree.org/2019/02/28/paper-hyperscan-a-fast-multi-pattern-regex-matcher-for-modern-cpus/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 96%|█████████▌| 280/293 [06:51<00:10,  1.21it/s]INFO:__main__:Requesting http://matt.might.net/articles/parsing-with-derivatives/
INFO:__main__:Getting metadata for http://matt.might.net/articles/parsing-with-derivatives/
 96%|█████████▌| 281/293 [06:51<00:08,  1.35it/s]INFO:__main__:Requesting https://github.com/kevinaangstadt/MNCaRT
INFO:__main__:Getting metadata for https://github.com/kevinaangstadt/MNCaRT
 96%|█████████▌| 282/293 [06:52<00:08,  1.34it/s]INFO:__main__:Requesting https://github.com/shenfe/python-hyperscan
INFO:__main__:Getting metadata for https://github.com/shenfe/python-hyperscan
 97%|█████████▋| 283/293 [06:53<00:07,  1.33it/s]INFO:__main__:Requesting https://github.com/nemequ/simde
INFO:__main__:Getting metadata for https://github.com/nemequ/simde
 97%|█████████▋| 284/293 [06:54<00:06,  1.31it/s]INFO:__main__:Requesting https://github.com/BurntSushi/ripgrep
INFO:__main__:Getting metadata for https://github.com/BurntSushi/ripgrep
 97%|█████████▋| 285/293 [06:55<00:07,  1.05it/s]INFO:__main__:Requesting https://github.com/rust-lang/regex/commit/203c509df9e1dcba61eaa60ba9c09be9ca0c4b25
INFO:__main__:Getting metadata for https://github.com/rust-lang/regex/commit/203c509df9e1dcba61eaa60ba9c09be9ca0c4b25
 98%|█████████▊| 286/293 [06:56<00:07,  1.00s/it]INFO:__main__:Requesting https://github.blog/2018-10-17-behind-the-scenes-of-github-token-scanning/
INFO:__main__:Getting metadata for https://github.blog/2018-10-17-behind-the-scenes-of-github-token-scanning/
 98%|█████████▊| 287/293 [06:57<00:05,  1.08it/s]INFO:__main__:Requesting https://github.com/zricethezav/gitleaks
INFO:__main__:Getting metadata for https://github.com/zricethezav/gitleaks
 98%|█████████▊| 288/293 [06:58<00:04,  1.05it/s]INFO:__main__:Requesting https://slideslive.com/38913519/topological-approaches-for-unsupervised-learning
INFO:__main__:Getting metadata for https://slideslive.com/38913519/topological-approaches-for-unsupervised-learning
 99%|█████████▊| 289/293 [06:59<00:03,  1.15it/s]INFO:__main__:Requesting https://arxiv.org/abs/1802.03426
INFO:__main__:Getting metadata for https://arxiv.org/abs/1802.03426
 99%|█████████▉| 290/293 [06:59<00:02,  1.13it/s]INFO:__main__:Requesting https://github.com/lmcinnes/umap
INFO:__main__:Getting metadata for https://github.com/lmcinnes/umap
 99%|█████████▉| 291/293 [07:00<00:01,  1.10it/s]INFO:__main__:Requesting https://johnhw.github.io/umap_primes/index.md.html
INFO:__main__:Getting metadata for https://johnhw.github.io/umap_primes/index.md.html
ERROR:__main__:Could not get metadata for https://johnhw.github.io/umap_primes/index.md.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
100%|█████████▉| 292/293 [07:01<00:00,  1.34it/s]INFO:__main__:Requesting https://unintendedconsequenc.es/uyghurs-xinjiang-onward-to-the-inevitable/
100%|██████████| 293/293 [07:01<00:00,  1.63it/s]
