INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:06,  4.53it/s]  7%|▋         | 2/30 [00:01<00:11,  2.34it/s] 10%|█         | 3/30 [00:01<00:13,  2.01it/s] 13%|█▎        | 4/30 [00:01<00:10,  2.55it/s] 20%|██        | 6/30 [00:02<00:08,  2.95it/s] 23%|██▎       | 7/30 [00:03<00:10,  2.28it/s] 27%|██▋       | 8/30 [00:03<00:07,  2.91it/s] 40%|████      | 12/30 [00:03<00:04,  4.01it/s] 47%|████▋     | 14/30 [00:03<00:04,  3.64it/s] 53%|█████▎    | 16/30 [00:04<00:04,  2.96it/s] 57%|█████▋    | 17/30 [00:05<00:03,  3.25it/s] 60%|██████    | 18/30 [00:05<00:03,  3.43it/s] 63%|██████▎   | 19/30 [00:05<00:03,  3.52it/s] 70%|███████   | 21/30 [00:05<00:01,  4.56it/s] 80%|████████  | 24/30 [00:05<00:01,  5.84it/s] 87%|████████▋ | 26/30 [00:06<00:00,  7.37it/s] 93%|█████████▎| 28/30 [00:06<00:00,  7.60it/s]100%|██████████| 30/30 [00:06<00:00,  7.68it/s]
  0%|          | 0/127 [00:00<?, ?it/s]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2019-03-08/china-s-gdp-growth-pace-was-inflated-for-nine-years-study-finds
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=8d4658a0-42f1-11e9-9003-e39fd5cd0cae&url=L25ld3MvYXJ0aWNsZXMvMjAxOS0wMy0wOC9jaGluYS1zLWdkcC1ncm93dGgtcGFjZS13YXMtaW5mbGF0ZWQtZm9yLW5pbmUteWVhcnMtc3R1ZHktZmluZHM=
  1%|          | 1/127 [00:00<01:11,  1.76it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Li_Keqiang_index
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Li_Keqiang_index
  2%|▏         | 2/127 [00:01<01:10,  1.78it/s]INFO:__main__:Requesting https://foreignpolicy.com/2009/03/10/beijings-gdp-numerology/
ERROR:__main__:Could not reach https://foreignpolicy.com/2009/03/10/beijings-gdp-numerology/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  2%|▏         | 3/127 [00:01<00:54,  2.26it/s]INFO:__main__:Requesting https://khn.org/news/gofundme-ceo-gigantic-gaps-in-health-system-showing-up-in-crowdfunding/
ERROR:__main__:Could not reach https://khn.org/news/gofundme-ceo-gigantic-gaps-in-health-system-showing-up-in-crowdfunding/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  3%|▎         | 4/127 [00:01<00:43,  2.83it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_Running_Man_(1987_film)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_Running_Man_(1987_film)
  4%|▍         | 5/127 [00:02<01:06,  1.83it/s]INFO:__main__:Requesting https://www.trutv.com/shows/paid-off-with-michael-torpey/index.html
INFO:__main__:Getting metadata for https://www.trutv.com/shows/paid-off-with-michael-torpey/index.html
  5%|▍         | 6/127 [00:02<01:05,  1.85it/s]INFO:__main__:Requesting http://www.antipope.org/charlie/blog-static/2008/09/avalanche.html
INFO:__main__:Getting metadata for http://www.antipope.org/charlie/blog-static/2008/09/avalanche.html
  6%|▌         | 7/127 [00:07<03:34,  1.78s/it]INFO:__main__:Requesting http://www.smbc-comics.com/comic/speciation
INFO:__main__:Getting metadata for http://www.smbc-comics.com/comic/speciation
  6%|▋         | 8/127 [00:09<03:31,  1.78s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Queen_for_a_Day
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Queen_for_a_Day
  7%|▋         | 9/127 [00:10<02:58,  1.51s/it]INFO:__main__:Requesting https://youtu.be/kBP_BMOblzc
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=kBP_BMOblzc&feature=youtu.be
  8%|▊         | 10/127 [00:11<02:39,  1.36s/it]INFO:__main__:Requesting https://youtu.be/wS3-PffLKqM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=wS3-PffLKqM&feature=youtu.be
  9%|▊         | 11/127 [00:12<02:19,  1.20s/it]INFO:__main__:Requesting https://watsi.org/
INFO:__main__:Getting metadata for https://watsi.org
  9%|▉         | 12/127 [00:14<03:05,  1.61s/it]INFO:__main__:Requesting https://www.bmj.com/content/357/bmj.j2097
INFO:__main__:Getting metadata for https://www.bmj.com/content/357/bmj.j2097
 10%|█         | 13/127 [00:17<03:33,  1.87s/it]INFO:__main__:Requesting https://www.nhs.uk/conditions/ivf/availability/
INFO:__main__:Getting metadata for https://www.nhs.uk/conditions/ivf/availability/
 11%|█         | 14/127 [00:17<02:33,  1.36s/it]INFO:__main__:Requesting https://www.axios.com/profits-are-booming-at-health-insurance-companies-1513302495-18f3710a-c0b4-4ce3-8b7f-894a755e6679.html
INFO:__main__:Getting metadata for https://www.axios.com/profits-are-booming-at-health-insurance-companies-1513302495-18f3710a-c0b4-4ce3-8b7f-894a755e6679.html
 12%|█▏        | 15/127 [00:17<02:00,  1.07s/it]INFO:__main__:Requesting https://www.verywellhealth.com/health-insurance-companies-unreasonable-profits-1738941
INFO:__main__:Getting metadata for https://www.verywellhealth.com/health-insurance-companies-unreasonable-profits-1738941
 13%|█▎        | 16/127 [00:18<01:38,  1.13it/s]INFO:__main__:Requesting https://www.gofundme.com/injured-by-scooter-accident
INFO:__main__:Getting metadata for https://www.gofundme.com/injured-by-scooter-accident
 13%|█▎        | 17/127 [00:18<01:24,  1.30it/s]INFO:__main__:Requesting https://www.theatlantic.com/health/archive/2016/11/cuba-health/508859/
INFO:__main__:Getting metadata for https://www.theatlantic.com/health/archive/2016/11/cuba-health/508859/
 14%|█▍        | 18/127 [00:19<01:11,  1.52it/s]INFO:__main__:Requesting https://support.gofundme.com/hc/en-us/articles/203604424-Fees-on-GoFundMe
INFO:__main__:Getting metadata for https://support.gofundme.com/hc/en-us/articles/203604424-Fees-on-GoFundMe
 15%|█▍        | 19/127 [00:19<01:08,  1.57it/s]INFO:__main__:Requesting https://kaiserfamilyfoundation.files.wordpress.com/2018/10/9196-03-figure-3.png
INFO:__main__:Getting metadata for https://kaiserfamilyfoundation.files.wordpress.com/2018/10/9196-03-figure-3.png
 16%|█▌        | 20/127 [00:21<02:01,  1.13s/it]INFO:__main__:Requesting https://img.washingtonpost.com/blogs/ezra-klein/files/2012/09/kff11.png
ERROR:__main__:Could not reach https://img.washingtonpost.com/blogs/ezra-klein/files/2012/09/kff11.png
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='img.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='img.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 17%|█▋        | 21/127 [00:28<04:38,  2.63s/it]INFO:__main__:Requesting https://i2.cdn.turner.com/money/dam/assets/130305161550-chart-productivity-hourly-compensation-1024x576.gif
INFO:__main__:Getting metadata for https://i2.cdn.turner.com/money/dam/assets/130305161550-chart-productivity-hourly-compensation-1024x576.gif
 17%|█▋        | 22/127 [00:30<04:20,  2.48s/it]INFO:__main__:Requesting https://github.com/gotify
INFO:__main__:Getting metadata for https://github.com/gotify
 18%|█▊        | 23/127 [00:30<03:24,  1.96s/it]INFO:__main__:Requesting https://github.com/wybiral/stream-sources
INFO:__main__:Getting metadata for https://github.com/wybiral/stream-sources
 19%|█▉        | 24/127 [00:31<02:45,  1.61s/it]INFO:__main__:Requesting https://pushover.net/
INFO:__main__:Getting metadata for https://pushover.net
 20%|█▉        | 25/127 [00:32<02:27,  1.44s/it]INFO:__main__:Requesting https://github.com/huginn/huginn
INFO:__main__:Getting metadata for https://github.com/huginn/huginn
 20%|██        | 26/127 [00:33<02:14,  1.33s/it]INFO:__main__:Requesting https://gotify.net/
INFO:__main__:Getting metadata for https://gotify.net
 21%|██▏       | 27/127 [00:34<01:41,  1.01s/it]INFO:__main__:Requesting https://gitlab.com/stavros/pysignald/
INFO:__main__:Getting metadata for https://gitlab.com/stavros/pysignald/
 22%|██▏       | 28/127 [00:35<01:37,  1.01it/s]INFO:__main__:Requesting https://gotify.net/api-docs#/message/streamMessages
INFO:__main__:Getting metadata for https://gotify.net/api-docs#/message/streamMessages
 23%|██▎       | 29/127 [00:35<01:18,  1.25it/s]INFO:__main__:Requesting https://github.com/gotify/server/issues/87
INFO:__main__:Getting metadata for https://github.com/gotify/server/issues/87
 24%|██▎       | 30/127 [00:36<01:25,  1.13it/s]INFO:__main__:Requesting https://0xacab.org/leap/bitmask_android/issues/2226#note_92144
INFO:__main__:Getting metadata for https://0xacab.org/leap/bitmask_android/issues/2226#note_92144
 24%|██▍       | 31/127 [00:37<01:35,  1.00it/s]INFO:__main__:Requesting https://www.tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
INFO:__main__:Getting metadata for https://www.tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
 25%|██▌       | 32/127 [00:39<01:44,  1.10s/it]INFO:__main__:Requesting https://blog.golang.org/gopher
INFO:__main__:Getting metadata for https://blog.golang.org/gopher
 26%|██▌       | 33/127 [00:39<01:21,  1.16it/s]INFO:__main__:Requesting https://www.w3.org/TR/push-api/
INFO:__main__:Getting metadata for https://www.w3.org/TR/push-api/
 27%|██▋       | 34/127 [00:41<01:48,  1.17s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Push_technology
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Push_technology
 28%|██▊       | 35/127 [00:42<01:40,  1.10s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Apple_Push_Notification_Service
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Apple_Push_Notification_Service
 28%|██▊       | 36/127 [00:43<01:34,  1.04s/it]INFO:__main__:Requesting https://www.corbinstreehouse.com/blog/2019/03/the-sad-state-of-logging-bugs-for-apple/
INFO:__main__:Getting metadata for https://www.corbinstreehouse.com/blog/2019/03/the-sad-state-of-logging-bugs-for-apple/
 29%|██▉       | 37/127 [00:45<01:58,  1.31s/it]INFO:__main__:Requesting https://www.corbinstreehouse.com/blog/about/
INFO:__main__:Getting metadata for https://www.corbinstreehouse.com/blog/about/
 30%|██▉       | 38/127 [00:46<02:12,  1.48s/it]INFO:__main__:Requesting http://bob.cs.sonoma.edu/IntroCompOrg-RPi/intro-co-rpi.html
INFO:__main__:Getting metadata for http://bob.cs.sonoma.edu/IntroCompOrg-RPi/intro-co-rpi.html
 31%|███       | 39/127 [00:47<01:55,  1.32s/it]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox
 31%|███▏      | 40/127 [00:48<01:42,  1.18s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Web_ARChive
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Web_ARChive
 32%|███▏      | 41/127 [00:49<01:27,  1.01s/it]INFO:__main__:Requesting https://getpolarized.io/
INFO:__main__:Getting metadata for https://getpolarized.io
 33%|███▎      | 42/127 [00:49<01:09,  1.23it/s]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox/wiki/Configuration
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox/wiki/Configuration
 34%|███▍      | 43/127 [00:50<01:06,  1.27it/s]INFO:__main__:Requesting https://launchaco.com
INFO:__main__:Getting metadata for https://www.launchaco.com
 35%|███▍      | 44/127 [00:50<00:58,  1.43it/s]INFO:__main__:Requesting https://github.com/ArchiveTeam/grab-site
INFO:__main__:Getting metadata for https://github.com/ArchiveTeam/grab-site
 35%|███▌      | 45/127 [00:51<01:04,  1.27it/s]INFO:__main__:Requesting https://www.loc.gov/preservation/digital/formats/fdd/fdd000236.shtml
INFO:__main__:Getting metadata for https://www.loc.gov/preservation/digital/formats/fdd/fdd000236.shtml
 36%|███▌      | 46/127 [00:52<01:09,  1.16it/s]INFO:__main__:Requesting https://www.archiveteam.org/index.php?title=Wget_with_WARC_output
INFO:__main__:Getting metadata for https://www.archiveteam.org/index.php?title=Wget_with_WARC_output
 37%|███▋      | 47/127 [00:55<01:38,  1.23s/it]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox/blob/a74d8410f4c3f2f08f75f223c15f8615be85744f/archivebox/archive_methods.py#L208
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox/blob/a74d8410f4c3f2f08f75f223c15f8615be85744f/archivebox/archive_methods.py#L208
 38%|███▊      | 48/127 [00:56<01:38,  1.25s/it]INFO:__main__:Requesting https://github.com/webrecorder/pywb
INFO:__main__:Getting metadata for https://github.com/webrecorder/pywb
 39%|███▊      | 49/127 [00:57<01:35,  1.22s/it]INFO:__main__:Requesting https://freemanagermentors.com
INFO:__main__:Getting metadata for https://www.freemanagermentors.com
 39%|███▉      | 50/127 [00:58<01:35,  1.24s/it]INFO:__main__:Requesting https://jackwelch.strayer.edu/winning/leadership-4es-p-energy-energize-edge-execute-passion/
INFO:__main__:Getting metadata for https://jackwelch.strayer.edu/winning/leadership-4es-p-energy-energize-edge-execute-passion/
 40%|████      | 51/127 [01:02<02:26,  1.93s/it]INFO:__main__:Requesting https://www.amazon.com/Winning-Ultimate-Business-How-Book-ebook/dp/B000FCK3GO/ref=nodl_
INFO:__main__:Getting metadata for https://www.amazon.com/Winning-Ultimate-Business-How-Book-ebook/dp/B000FCK3GO/ref=nodl_
 41%|████      | 52/127 [01:04<02:40,  2.14s/it]INFO:__main__:Requesting https://www.amazon.com/Influence-Psychology-Persuasion-Robert-Cialdini/dp/006124189X/ref=pd_lpo_sbs_14_t_0?_encoding=UTF8&psc=1&refRID=DE7EDQ8WXW5HHGMAVH05
INFO:__main__:Getting metadata for https://www.amazon.com/Influence-Psychology-Persuasion-Robert-Cialdini/dp/006124189X/ref=pd_lpo_sbs_14_t_0?_encoding=UTF8&psc=1&refRID=DE7EDQ8WXW5HHGMAVH05
 42%|████▏     | 53/127 [01:08<02:58,  2.42s/it]INFO:__main__:Requesting https://www.amazon.com/dp/B0053ALPPQ/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1
INFO:__main__:Getting metadata for https://www.amazon.com/dp/B0053ALPPQ/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1
 43%|████▎     | 54/127 [01:10<02:54,  2.40s/it]INFO:__main__:Requesting https://www.amazon.com/How-Win-Friends-Influence-People/dp/0091906350/ref=asc_df_0091906350/?tag=hyprod-20&linkCode=df0&hvadid=241983376253&hvpos=1o1&hvnetw=g&hvrand=16750785035456213073&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9060225&hvtargid=pla-364195442564&psc=1
INFO:__main__:Getting metadata for https://www.amazon.com/How-Win-Friends-Influence-People/dp/0091906350/ref=asc_df_0091906350/?tag=hyprod-20&linkCode=df0&hvadid=241983376253&hvpos=1o1&hvnetw=g&hvrand=16750785035456213073&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9060225&hvtargid=pla-364195442564&psc=1
 43%|████▎     | 55/127 [01:13<03:06,  2.59s/it]INFO:__main__:Requesting http://coleadership.com
INFO:__main__:Getting metadata for http://coleadership.com
 44%|████▍     | 56/127 [01:13<02:13,  1.88s/it]INFO:__main__:Requesting https://www.elitedaily.com/life/motivation/psychopaths-make-the-best-leaders/1108247
INFO:__main__:Getting metadata for https://www.elitedaily.com/life/motivation/psychopaths-make-the-best-leaders/1108247
 45%|████▍     | 57/127 [01:13<01:35,  1.37s/it]INFO:__main__:Requesting https://xkcd.com/1735/
INFO:__main__:Getting metadata for https://xkcd.com/1735/
 46%|████▌     | 58/127 [01:14<01:13,  1.07s/it]INFO:__main__:Requesting https://www.epsilontheory.com/too-clever-by-half/
INFO:__main__:Getting metadata for https://www.epsilontheory.com/too-clever-by-half/
 46%|████▋     | 59/127 [01:14<00:54,  1.26it/s]INFO:__main__:Requesting https://www.ribbonfarm.com/the-gervais-principle/
INFO:__main__:Getting metadata for https://www.ribbonfarm.com/the-gervais-principle/
 47%|████▋     | 60/127 [01:14<00:45,  1.47it/s]INFO:__main__:Requesting https://www.amazon.com/Extreme-Ownership-U-S-Navy-SEALs/dp/1250067057
INFO:__main__:Getting metadata for https://www.amazon.com/Extreme-Ownership-U-S-Navy-SEALs/dp/1250067057
 48%|████▊     | 61/127 [01:17<01:21,  1.23s/it]INFO:__main__:Requesting https://openreview.net/pdf?id=SkfMWhAqYQ
INFO:__main__:Getting metadata for https://openreview.net/pdf?id=SkfMWhAqYQ
 49%|████▉     | 62/127 [08:10<2:15:09, 124.76s/it]INFO:__main__:Requesting https://openreview.net/forum?id=Bygh9j09KX
INFO:__main__:Getting metadata for https://openreview.net/forum?id=Bygh9j09KX
 50%|████▉     | 63/127 [08:10<1:33:12, 87.39s/it] INFO:__main__:Requesting https://openreview.net/forum?id=SkfMWhAqYQ
INFO:__main__:Getting metadata for https://openreview.net/forum?id=SkfMWhAqYQ
 50%|█████     | 64/127 [08:10<1:04:17, 61.22s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=QpptSohzuDo
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=QpptSohzuDo
 51%|█████     | 65/127 [08:11<44:32, 43.11s/it]  INFO:__main__:Requesting https://madison.com/wsj/news/local/doug_moe/lana-about-svetlana-stalin-s-daughter-on-her-life-in/article_85ebc5d0-4978-11df-b181-001cc4c002e0.html
INFO:__main__:Getting metadata for https://madison.com/wsj/news/local/doug_moe/lana-about-svetlana-stalin-s-daughter-on-her-life-in/article_85ebc5d0-4978-11df-b181-001cc4c002e0.html
 52%|█████▏    | 66/127 [08:11<30:46, 30.27s/it]INFO:__main__:Requesting https://towardsdatascience.com/its-only-natural-an-excessively-deep-dive-into-natural-gradient-optimization-75d464b89dbb
INFO:__main__:Getting metadata for https://towardsdatascience.com/its-only-natural-an-excessively-deep-dive-into-natural-gradient-optimization-75d464b89dbb?gi=7b6a589b67c5
 53%|█████▎    | 67/127 [08:13<21:42, 21.71s/it]INFO:__main__:Requesting https://www.exactitudes.org/
INFO:__main__:Getting metadata for https://www.exactitudes.org
 54%|█████▎    | 68/127 [08:16<15:51, 16.12s/it]INFO:__main__:Requesting https://www.exactitudes.org/index.php?/about/
INFO:__main__:Getting metadata for https://www.exactitudes.org/index.php?/about/
 54%|█████▍    | 69/127 [08:19<11:41, 12.09s/it]INFO:__main__:Requesting https://www.cbc.ca/radio/asithappens/man-angry-his-photo-was-used-to-prove-all-hipsters-look-alike-then-learns-it-wasn-t-him-1.5046933
INFO:__main__:Getting metadata for https://www.cbc.ca/radio/asithappens/man-angry-his-photo-was-used-to-prove-all-hipsters-look-alike-then-learns-it-wasn-t-him-1.5046933
 55%|█████▌    | 70/127 [08:19<08:06,  8.54s/it]INFO:__main__:Requesting http://exactitudes.com/index.php?/expo/all/
INFO:__main__:Getting metadata for http://exactitudes.com/index.php?/expo/all/
 56%|█████▌    | 71/127 [08:21<06:08,  6.58s/it]INFO:__main__:Requesting https://www.vice.com/en_uk/article/gqnevx/fashion-uk-interview-ari-versluis-exactitudes
INFO:__main__:Getting metadata for https://www.vice.com/en_uk/article/gqnevx/fashion-uk-interview-ari-versluis-exactitudes
 57%|█████▋    | 72/127 [08:21<04:17,  4.68s/it]INFO:__main__:Requesting https://dhruvp.netlify.com/2019/02/25/eigenvectors/
INFO:__main__:Getting metadata for https://dhruvp.netlify.com/2019/02/25/eigenvectors/
 57%|█████▋    | 73/127 [08:25<03:52,  4.31s/it]INFO:__main__:Requesting https://0xax.gitbooks.io/linux-insides/Booting/linux-bootstrap-1.html
INFO:__main__:Getting metadata for https://0xax.gitbooks.io/linux-insides/Booting/linux-bootstrap-1.html
 58%|█████▊    | 74/127 [08:26<03:03,  3.46s/it]INFO:__main__:Requesting https://www.scott-a-s.com/the-linux-boot-process-of-2004/
INFO:__main__:Getting metadata for https://www.scott-a-s.com/the-linux-boot-process-of-2004/
 59%|█████▉    | 75/127 [08:27<02:20,  2.71s/it]INFO:__main__:Requesting https://www.latimes.com/business/technology/la-fi-tn-lyft-ipo-drivers-20190309-story.html
INFO:__main__:Getting metadata for https://www.latimes.com/business/technology/la-fi-tn-lyft-ipo-drivers-20190309-story.html
 60%|█████▉    | 76/127 [08:28<01:41,  2.00s/it]INFO:__main__:Requesting https://www.tesla.com/blog/misfortune
INFO:__main__:Getting metadata for https://www.tesla.com/blog/misfortune
 61%|██████    | 77/127 [08:28<01:13,  1.48s/it]INFO:__main__:Requesting https://hackaday.com/2019/03/09/speedrunning-windows-95/
ERROR:__main__:Could not reach https://hackaday.com/2019/03/09/speedrunning-windows-95/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 61%|██████▏   | 78/127 [08:28<00:53,  1.09s/it]INFO:__main__:Requesting https://vimeo.com/220071855
INFO:__main__:Requesting https://mobile.twitter.com/Foone/status/1103384684812255233
INFO:__main__:Getting metadata for https://mobile.twitter.com/Foone/status/1103384684812255233
 63%|██████▎   | 80/127 [08:30<00:49,  1.05s/it]INFO:__main__:Requesting https://www.speedrun.com/cp#Banned
INFO:__main__:Getting metadata for https://www.speedrun.com/cp#Banned
 64%|██████▍   | 81/127 [08:32<00:56,  1.24s/it]INFO:__main__:Requesting https://www.pcgamer.com/getting-banned-from-club-penguin-is-now-a-speedrunning-competition/
INFO:__main__:Getting metadata for https://www.pcgamer.com/getting-banned-from-club-penguin-is-now-a-speedrunning-competition/
 65%|██████▍   | 82/127 [08:33<00:57,  1.28s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/NetBIOS_Frames_protocol
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/NetBIOS_Frames_protocol
 65%|██████▌   | 83/127 [08:34<00:49,  1.13s/it]INFO:__main__:Requesting https://news.vice.com/en_us/article/7xakd9/windows-31-is-still-alive-and-it-just-killed-a-french-airport
INFO:__main__:Getting metadata for https://news.vice.com/en_us/article/7xakd9/windows-31-is-still-alive-and-it-just-killed-a-french-airport
 66%|██████▌   | 84/127 [08:34<00:36,  1.17it/s]INFO:__main__:Requesting https://msfn.org/board/topic/141402-windows-95-21ghz-cpu-limit-broken/
INFO:__main__:Getting metadata for https://msfn.org/board/topic/141402-windows-95-21ghz-cpu-limit-broken/
 67%|██████▋   | 85/127 [08:36<00:46,  1.10s/it]INFO:__main__:Requesting https://arstechnica.com/information-technology/2017/05/in-a-throwback-to-the-90s-ntfs-bug-lets-anyone-hang-or-crash-windows-7-8-1/
INFO:__main__:Getting metadata for https://arstechnica.com/information-technology/2017/05/in-a-throwback-to-the-90s-ntfs-bug-lets-anyone-hang-or-crash-windows-7-8-1/
 68%|██████▊   | 86/127 [08:36<00:34,  1.20it/s]INFO:__main__:Requesting https://xkcd.com/284/
INFO:__main__:Getting metadata for https://xkcd.com/284/
 69%|██████▊   | 87/127 [08:36<00:29,  1.37it/s]INFO:__main__:Requesting https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md
INFO:__main__:Getting metadata for https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md
 69%|██████▉   | 88/127 [08:37<00:29,  1.32it/s]INFO:__main__:Requesting http://www.annoyances.org/
INFO:__main__:Getting metadata for http://www.annoyances.org
 70%|███████   | 89/127 [08:37<00:22,  1.69it/s]INFO:__main__:Requesting https://www.litepc.com/
INFO:__main__:Getting metadata for https://www.litepc.com
 71%|███████   | 90/127 [08:41<01:00,  1.63s/it]INFO:__main__:Requesting https://forums.virtualbox.org/viewtopic.php?t=82787
INFO:__main__:Getting metadata for https://forums.virtualbox.org/viewtopic.php?t=82787
 72%|███████▏  | 91/127 [08:44<01:04,  1.80s/it]INFO:__main__:Requesting http://www.bell-labs.com/usr/dmr/www/chist.html
INFO:__main__:Getting metadata for http://www.bell-labs.com/usr/dmr/www/chist.html
 72%|███████▏  | 92/127 [08:45<00:56,  1.61s/it]INFO:__main__:Requesting http://www.thedrive.com/news/26842/german-regulators-tell-tesla-to-stop-advertising-cars-with-gas-savings-included-in-price
INFO:__main__:Getting metadata for http://www.thedrive.com/news/26842/german-regulators-tell-tesla-to-stop-advertising-cars-with-gas-savings-included-in-price
 73%|███████▎  | 93/127 [08:45<00:43,  1.28s/it]INFO:__main__:Requesting https://flyingkmachines.wordpress.com/
ERROR:__main__:Could not reach https://flyingkmachines.wordpress.com/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 74%|███████▍  | 94/127 [08:45<00:30,  1.07it/s]INFO:__main__:Requesting http://www.gingerybooks.com
INFO:__main__:Getting metadata for http://www.gingerybooks.com
 75%|███████▍  | 95/127 [08:46<00:24,  1.29it/s]INFO:__main__:Requesting https://mitpress.mit.edu/books/foundations-mechanical-accuracy
INFO:__main__:Getting metadata for https://mitpress.mit.edu/books/foundations-mechanical-accuracy
 76%|███████▌  | 96/127 [08:46<00:20,  1.48it/s]INFO:__main__:Requesting https://www.youtube.com/playlist?list=PLZPW_dvK6ZS-rZsqef3OXERKj9m5P6Jxb
INFO:__main__:Getting metadata for https://www.youtube.com/playlist?list=PLZPW_dvK6ZS-rZsqef3OXERKj9m5P6Jxb
 76%|███████▋  | 97/127 [08:47<00:22,  1.32it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=kANvdzoVUfw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=kANvdzoVUfw
 77%|███████▋  | 98/127 [08:48<00:23,  1.25it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=bx80iYfgXkY
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=bx80iYfgXkY
 78%|███████▊  | 99/127 [08:49<00:22,  1.22it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=BjksLl9xur0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=BjksLl9xur0
 79%|███████▊  | 100/127 [08:50<00:22,  1.21it/s]INFO:__main__:Requesting https://www.sciencemag.org/news/2019/03/black-death-may-have-transformed-medieval-societies-sub-saharan-africa
INFO:__main__:Getting metadata for https://www.sciencemag.org/news/2019/03/black-death-may-have-transformed-medieval-societies-sub-saharan-africa
 80%|███████▉  | 101/127 [08:50<00:19,  1.36it/s]INFO:__main__:Requesting https://www.deviantart.com/arminius1871/art/Population-loss-in-the-30-years-war-729172832
INFO:__main__:Getting metadata for https://www.deviantart.com/arminius1871/art/Population-loss-in-the-30-years-war-729172832
 80%|████████  | 102/127 [08:51<00:20,  1.19it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Medieval_renaissances
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Medieval_renaissances
 81%|████████  | 103/127 [08:52<00:20,  1.18it/s]INFO:__main__:Requesting https://news.ycombinator.com/newsguidelines.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/newsguidelines.html
 82%|████████▏ | 104/127 [08:53<00:21,  1.08it/s]INFO:__main__:Requesting https://www.scmp.com/magazines/post-magazine/long-reads/article/2188216/last-king-xinjiang-how-bertram-sheldrake-went
INFO:__main__:Getting metadata for https://www.scmp.com/magazines/post-magazine/long-reads/article/2188216/last-king-xinjiang-how-bertram-sheldrake-went
 83%|████████▎ | 105/127 [08:54<00:20,  1.10it/s]INFO:__main__:Requesting https://pacman128.github.io/pcasm/
INFO:__main__:Getting metadata for https://pacman128.github.io/pcasm/
 83%|████████▎ | 106/127 [08:55<00:15,  1.35it/s]INFO:__main__:Requesting https://twitter.com/x86instructions
INFO:__main__:Getting metadata for https://twitter.com/x86instructions
 84%|████████▍ | 107/127 [08:57<00:26,  1.35s/it]INFO:__main__:Requesting https://www.sciencealert.com/it-s-official-octopus-and-squid-evolution-is-weirder-than-we-could-have-ever-imagined
INFO:__main__:Getting metadata for https://www.sciencealert.com/it-s-official-octopus-and-squid-evolution-is-weirder-than-we-could-have-ever-imagined
 85%|████████▌ | 108/127 [08:58<00:20,  1.09s/it]INFO:__main__:Requesting https://news.yahoo.com/japanese-woman-confirmed-worlds-oldest-person-aged-116-094645090.html
INFO:__main__:Getting metadata for https://news.yahoo.com/japanese-woman-confirmed-worlds-oldest-person-aged-116-094645090.html
 86%|████████▌ | 109/127 [08:59<00:22,  1.24s/it]INFO:__main__:Requesting https://medium.com/@ThingMaker/in-my-culture-29c6464072b2
INFO:__main__:Getting metadata for https://medium.com/@ThingMaker/in-my-culture-29c6464072b2
 87%|████████▋ | 110/127 [09:00<00:16,  1.00it/s]INFO:__main__:Requesting https://probablydance.com/2019/03/09/a-programmers-take-on-six-memos-for-the-next-millenium/
ERROR:__main__:Could not reach https://probablydance.com/2019/03/09/a-programmers-take-on-six-memos-for-the-next-millenium/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 87%|████████▋ | 111/127 [09:00<00:11,  1.35it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/List_of_emerging_technologies
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/List_of_emerging_technologies
 88%|████████▊ | 112/127 [09:02<00:18,  1.24s/it]INFO:__main__:Requesting https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone
INFO:__main__:Getting metadata for https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone
 89%|████████▉ | 113/127 [09:05<00:23,  1.65s/it]INFO:__main__:Requesting https://www.borgbase.com/
INFO:__main__:Getting metadata for https://www.borgbase.com
 90%|████████▉ | 114/127 [09:05<00:16,  1.27s/it]INFO:__main__:Requesting https://borgbackup.readthedocs.io/en/stable/usage/notes.html#drawbacks
INFO:__main__:Getting metadata for https://borgbackup.readthedocs.io/en/stable/usage/notes.html#drawbacks
 91%|█████████ | 115/127 [09:06<00:14,  1.21s/it]INFO:__main__:Requesting https://torsion.org/borgmatic/
INFO:__main__:Getting metadata for https://torsion.org/borgmatic/
 91%|█████████▏| 116/127 [09:08<00:14,  1.29s/it]INFO:__main__:Requesting http://www.squidi.net/three/index.php
 92%|█████████▏| 117/127 [09:08<00:09,  1.05it/s]INFO:__main__:Requesting http://www.squidi.net/three/entry.php?id=207
INFO:__main__:Requesting https://techcrunch.com/2010/08/25/scvngr-game-mechanics/
ERROR:__main__:Could not reach https://techcrunch.com/2010/08/25/scvngr-game-mechanics/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 94%|█████████▎| 119/127 [09:08<00:05,  1.44it/s]INFO:__main__:Requesting http://virt10.itu.chalmers.se/index.php
INFO:__main__:Getting metadata for http://virt10.itu.chalmers.se/index.php/Main_Page
 94%|█████████▍| 120/127 [09:11<00:09,  1.40s/it]INFO:__main__:Requesting http://www.squidi.net/comic/amd/
INFO:__main__:Requesting http://davidad.github.io/blog/2014/04/24/an-osi-layer-model-for-the-21st-century/
INFO:__main__:Getting metadata for http://davidad.github.io/blog/2014/04/24/an-osi-layer-model-for-the-21st-century/
 96%|█████████▌| 122/127 [09:12<00:05,  1.05s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/TM_Forum#OSI/Network_Management_Forum
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/TM_Forum#OSI/Network_Management_Forum
 97%|█████████▋| 123/127 [09:13<00:04,  1.02s/it]INFO:__main__:Requesting https://books.google.com/books?id=k9sFgIM-z6UC&lpg=PT152&ots=UhrSdDRSdD&pg=PT150#v=onepage&q=Green%20Side%20Up&f=false
INFO:__main__:Getting metadata for https://books.google.com/books?id=k9sFgIM-z6UC&lpg=PT152&ots=UhrSdDRSdD&pg=PT150#v=onepage&q=Green%20Side%20Up&f=false
 98%|█████████▊| 124/127 [09:13<00:02,  1.20it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Videotex
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Videotex
 98%|█████████▊| 125/127 [09:14<00:01,  1.11it/s]INFO:__main__:Requesting https://www.itu.int/pub/T-REC
INFO:__main__:Getting metadata for https://www.itu.int/pub/T-REC
 99%|█████████▉| 126/127 [09:25<00:03,  3.83s/it]INFO:__main__:Requesting https://cgmnt-achilles-tortoise-piglet.netlify.com
INFO:__main__:Getting metadata for https://cgmnt-achilles-tortoise-piglet.netlify.com
100%|██████████| 127/127 [09:26<00:00,  2.89s/it]
